tasks:
  - name: HTML generation
    command: docker run --rm -it -v $PWD:/documents/ asciidoctor/docker-asciidoctor asciidoctor -B /documents/ -b html5 --failure-level WARN -v docs/index.adoc
  
  - name: Web server
    command: python -m http.server 8000 --directory docs

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
