tasks:
  - name: Start web server
    init: python -m http.server 8000 --directory docs
  - name: Generate HTML
    command: docker run --rm -it -v $PWD:/documents/ asciidoctor/docker-asciidoctor asciidoctor -B /documents/ -b html5 --failure-level WARN -v docs/index.adoc

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
