= Contributing to this project
:toc:
:toc-placement!:

Please take a moment to review this document in order to make the contribution process easy and effective for everyone involved.

Following these guidelines helps to communicate that you respect the time of the developers managing and developing this open source project.
In return, they should reciprocate that respect in addressing your issue or assessing patches and features.

toc::[]

== Using the issue tracker

The issue tracker is the preferred channel for <<Bug reports>>, <<Feature requests>> and submitting <<Pull requests>>, but please respect the following restrictions:

* Please *do not* use the issue tracker for personal support requests (use http://stackoverflow.com[Stack Overflow]).

* Please *do not* derail or troll issues. Keep the discussion on topic and respect the opinions of others.

== Bug reports

A bug is a _demonstrable problem_ that is caused by the code in the repository.
Good bug reports are extremely helpful - thank you!

Guidelines for bug reports:

. *Use the GitHub issue search* -- check if the issue has already been reported.

. *Check if the issue has been fixed* -- try to reproduce it using the latest `master` or development branch in the repository.

. *Isolate the problem* -- create a reduced test case or example.

A good bug report shouldn't leave others needing to chase you up for more
information. Please try to be as detailed as possible in your report. What is
your environment? What steps will reproduce the issue? What browser(s) and OS
experience the problem? What would you expect to be the outcome? All these
details will help people to fix any potential bugs.

Example:

----
Short and descriptive example bug report title

A summary of the issue and the platform/OS environment in which it occurs. If
suitable, include the steps required to reproduce the bug.

1. This is the first step
2. This is the second step
3. Further steps, etc.

`<url>` - a link to the reduced test case

Any other information you want to share that is relevant to the issue being
reported. This might include the lines of code that you have identified as
causing the bug, and potential solutions (and your opinions on their
merits).
----

== Feature requests

Feature requests are welcome. But take a moment to find out whether your idea fits with the scope and aims of the project.
It's up to *you* to make a strong case to convince the project's developers of the merits of this feature.
Please provide as much detail and context as possible.


== Commit messages

Please follow https://chris.beams.io/posts/git-commit/[the seven rules of a great Git commit message] when committing your changes:

- Separate subject from body with a blank line
- Limit the subject line to 50 characters
- Capitalize the subject line
- Do not end the subject line with a period
- Use the imperative mood in the subject line
- Wrap the body at 72 characters
- Use the body to explain what and why vs. how

For example:

----
Summarize changes in around 50 characters or less

More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of the commit and the rest of the text as the body. The
blank line separating the summary from the body is critical (unless
you omit the body entirely); various tools like `log`, `shortlog`
and `rebase` can get confused if you run the two together.

Explain the problem that this commit is solving. Focus on why you
are making this change as opposed to how (the code explains that).
Are there side effects or other unintuitive consequences of this
change? Here's the place to explain them.

Further paragraphs come after blank lines.

 - Bullet points are okay, too

 - Typically a hyphen or asterisk is used for the bullet, preceded
   by a single space, with blank lines in between, but conventions
   vary here

If you use an issue tracker, put references to them at the bottom,
like this:

Resolves: #123
See also: #456, #789
----

== Pull requests

Good pull requests - patches, improvements, new features - are a fantastic help.
They should remain focused in scope and avoid containing unrelated commits.

*Please ask first* before embarking on any significant pull request (e.g. implementing features, refactoring code, porting to a different language),
otherwise you risk spending a lot of time working on something that the project's developers might not want to merge into the project.

Please adhere to the coding conventions used throughout a project (indentation, accurate comments, etc.) and any other requirements (such as test coverage).

Follow this process if you'd like your work considered for inclusion in the project:

. https://help.github.com/articles/fork-a-repo/[Fork] the project, clone your fork, and configure the remotes:

  # Clone your fork of the repo into the current directory
  git clone https://github.com/<your-username>/<repo-name>
  # Navigate to the newly cloned directory
  cd <repo-name>
  # Assign the original repo to a remote called "upstream"
  git remote add upstream https://github.com/<upstream-owner>/<repo-name>

. If you cloned a while ago, get the latest changes from upstream:

  git checkout <dev-branch>
  git pull upstream <dev-branch>

. Create a new topic branch (off the main project development branch) to contain your feature, change, or fix:

   git checkout -b <topic-branch-name>

. Commit your changes in logical chunks. Please adhere to the above rules when crafting <<Commit messages>> or your code is unlikely be merged into the main project. Use Git's https://help.github.com/articles/about-git-rebase/[interactive rebase] feature to tidy up your commits before making them public.

. Locally merge (or rebase) the upstream development branch into your topic branch:

  git pull [--rebase] upstream <dev-branch>

. Push your topic branch up to your fork:

  git push origin <topic-branch-name>

. https://help.github.com/articles/about-pull-requests/[Open a Pull Request] with a clear title and description.

*IMPORTANT*: By submitting a patch, you agree to allow the project owner to license your work under the same license as that used by the project.

== Branching and versioning

We use the https://nvie.com/posts/a-successful-git-branching-model/[GitFlow] branching model and https://semver.org/[Semantic Versioning] for releases.

- New development is done in _feature branches_

- Feature branches are branched off of the `develop` branch

- Finished features and fixes are merged back into the `develop` branch

- When it is time to make a release, a release branch is created off of `develop`

- When the release is finished, the _release branch_ is merged into `master` and into `develop`

- Commits in the `master` branch are _tagged_ with a version number (e.g. `v2.0.1`)

== Formatting rules

When writing or editing the specification documents please follow the https://asciidoctor.org/docs/asciidoc-recommended-practices/[AsciiDoc Recommended Practices], particularly:

- Use https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line[one sentence per line]

- Use Atx style https://asciidoctor.org/docs/asciidoc-recommended-practices/#section-titles[section titles]

- Use four dashes (`----`) for https://asciidoctor.org/docs/asciidoc-recommended-practices/#delimited-blocks[delimited blocks]

- Use the asterisk (`*`) as marker for nested https://asciidoctor.org/docs/asciidoc-recommended-practices/#lists[lists]

=== Source code

Only the following strings are formatted as literals (using surrounding back ticks):

- source, markup and pseudo code (and parts thereof)
- file names and paths

Quotes must only be included if they are part of the original source or markup code.
