# The Modelica Association Project (MAP) Functional Mock-up Interface (FMI) Corporate Contributor License Agreement ("CCLA")

In order to clarify the intellectual property license granted with respect to Contributions, as further defined, from any person or entity, the Modelica Association Project FMI (the "Project") must have a Corporate Contributor License Agreement (CCLA) on file that has been signed by
each Contributor, indicating agreement to the license terms below.
This license is for your protection as a contributor as well as for the protection of the FMI Project, and for the Modelica Association as publisher of the FMI standard and its users; it does not change your rights to use your own Contributions for any other purpose.
This CCLA allows an entity (the "Corporation") to submit Contributions to the FMI Project, to authorize Contributions submitted by its designated employees to the Project, and to grant copyright and patent licenses thereto.
Please complete and sign, then scan and email a pdf file of this Agreement to projectleader@fmi-standard.org and send the original signed Agreement to:

----
Modelica Association
c/o PELAB, IDA, Linkoepings Universitet
S-58183 Linkoeping
Sweden
----

## Corporate Contributor License Agreement ("CCLA")

----
       Corporation name: ___________________________

    Corporation address: ___________________________

Point of Contact (Name): ___________________________

                 E-Mail: ___________________________

              Telephone: ___________________________
----

You accept and agree to the following terms and conditions for Your Past Contributions as identified in Schedule B, present and future Contributions submitted to the Project for the FMI Specifications.
For any Past Contribution, it will be limited to the Contributions identified in Schedule B here after.
In return, the Project shall not use Your Contributions in a way that is inconsistent with its Project Rules in effect at the time of the Contribution.
Except for the license granted herein to the Modelica Association and licensees of FMI Specifications distributed by
the Modelica Association, You reserve all right, title, and interest in and to Your Contributions.

. Definitions.
+
"You" (or "Your") shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with the Modelica Association.
For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor.
For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
+
"Contribution" shall mean the code, documentation or other original works of authorship, including any modifications or additions thereto, that is intentionally submitted by You to the Modelica Association Project FMI for inclusion in, or documentation of, the FMI Specification managed by the Modelica Association (the "Work").
For the purposes of this definition, "submitted" means all the Works which are proposed by You in the form of an FMI Change Proposal (FCP) as defined within the FMI Development Process Rules of the Project.
+
"Past Contribution" shall mean any Contribution submitted by You before the execution date of this Agreement.

. Grant of Copyright License.
+
To the extent that You hold a copyright interest in Your Contribution, You grant to the Modelica Association a non-exclusive, royalty-free, worldwide copyright license for the whole duration of such copyright protection, with the right to directlyand indirectly sublicense, to copy, publish, and distribute the Contribution in the FMI Specification, and to prepare derivative works that are based on or incorporate all or part of the Contribution solely for the purpose of developing, promoting and distributing the FMI Specification.

. Grant of Patent License.
+
Subject to the terms and conditions of this Agreement, You hereby grant to the Modelica Association and to licensees of FMI Specifications distributed by the Modelica Association, including the C header and XML-schema therein, a worldwide, non-exclusive, no-charge, royalty-free patent license for the whole duration of such patent protection to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Work to which such Contribution(s) were submitted.

. You represent that You are legally entitled to grant the above license.
+
You represent further that each employee of the Corporation (or of any company it controls as defined above) designated on Schedule A below is authorized to submit Contributions on behalf of the Corporation.

. You are not expected to provide support for Your Contributions, except to the extent You desire to provide support. You may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, You provide Your Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, either expressed or implied, including, without limitation, any warranties of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.

. Should You wish to submit work that is not Your original creation, You may submit it to the Project separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as "Submitted on behalf of a third-party: [named here]".

. It is your responsibility to notify the Project when any change is required to the list of designated employees authorized to submit Contributions on behalf of the Corporation, or to the Corporation's Point of Contact with the Project.

. To the extent permitted by applicable law, no claim shall be made against You for direct, indirect, consequential, special, incidental or punitive damages, including, without limitation, loss of use, profit, revenue, or goodwill, whether based in contract, tort, or otherwise, arising out of, resulting from or in any way relating to the use of Your Contribution(s) by Project or any other entity or company.
+
However, in case a claim should be brought by a third party against one or several of the other contributors and/or against members of the Modelica Association Project FMI arising out of, resulting from or in any way relating to the FMI Specification nothing herein shall prevent said contributor and/or member respectively from claiming reimbursement and/or indemnification from You to the extent the third party claim is based on Your Contribution(s).

. This Agreement shall be governed and construed in accordance with the laws of Sweden.
The Courts of Stockholm shall have exclusive jurisdiction to hear any dispute arising out of or in connection with the interpretation and/or performance of this Agreement.
The Modelica Association acknowledges and agrees that the paragraph immediately above shall not prevent, restrict or otherwise limit in any manner Your rights to seek equitable remedies, including injunctive relief before any competent court in any jurisdiction.

----
  Signature: __________________________________ Date: _______________

      Title: __________________________________

Corporation: __________________________________
----

## Schedule A: Initial list of designated employees

## Schedule B: List of Past Contributions

Your Past Contributions are Your contributions in the released FMI specifications.
The last released FMI specifications and all included Works at the execution date of this
Agreement are:

* https://svn.modelica.org/fmi/branches/public/specifications/v1.0/FMI_for_ModelExchange_v1.0.zip[FMI for Model Exchange 1.0]

* https://svn.modelica.org/fmi/branches/public/specifications/v1.0/FMI_for_CoSimulation_v1.0.zip[FMI for Co-Simulation 1.0]

* https://svn.modelica.org/fmi/branches/public/specifications/v2.0/FMI_for_ModelExchange_and_CoSimulation_v2.0.zip[FMI for Model Exchange and Co-Simulation 2.0]

Your Past Contributions also cover Your contributions to the Modelica package FMITest to test connected FMUs as defined here: https://svn.fmi-standard.org/fmi/branches/public/Test_FMUs/_FMIModelicaTest
