image::docs/images/FMI_logo_horizontal.svg[width=30%,align="center"]

= Functional Mock-up Interface

image:https://circleci.com/gh/modelica/fmi-standard/tree/support%2Fv2.0.x.svg?style=svg["CircleCI", link="https://circleci.com/gh/modelica/fmi-standard/tree/support%2Fv2.0.x"]

The Functional Mock-up Interface (FMI) is a free standard that defines an interface to exchange dynamic models using a combination of XML files, binaries and C code.
It's supported by https://fmi-standard.org/tools/[100+] tools and maintained as a https://modelica.org/projects[Modelica Association Project].

== Repository structure

- `docs` -- sources of the specification document
- `headers` -- header files of the C-API
- `schema` -- the XSD schema for the modelDescription.xml

== Branches

- `master` -- development of the next release
- `support/2.0.x` -- maintenance of the 2.0 release
- `feature/*` -- development of features for the next release

== Building the specification document

The FMI Specification is written in http://asciidoc.org/[AsciiDoc], a plain-text mark-up format that can be converted to HTML, PDF and https://asciidoctor.org/docs/convert-documents/#selecting-an-output-format[other formats].
To build the documentation locally

. https://help.github.com/articles/cloning-a-repository/[Clone] the repository
+
  git clone https://github.com/modelica/fmi-standard.git

. Install https://www.docker.com/get-started[Docker]

. Run the https://github.com/asciidoctor/docker-asciidoctor[Asciidoctor Docker Container]
+
  docker run -it -v <docs>:/documents/ asciidoctor/docker-asciidoctor
+
where `<docs>` is the path to the `docs` directory

. Change into the `docs` folder
+
  cd docs

. Generate the HTML document
+
  asciidoctor -b html5 fmi_specification.adoc

The generated `fmi_specification.html` can be viewed with any modern web browser.

== Copyright and license

Code and documentation copyright (C) 2008-2011 the MODELISAR consortium and 2012-2020 the Modelica Association Project "FMI".
Code released under the https://opensource.org/licenses/BSD-2-Clause[2-Clause BSD License].
Docs released under https://creativecommons.org/licenses/by-sa/4.0/[Attribution-ShareAlike 4.0 International].
