image::docs/images/FMI_logo_horizontal.svg[width=30%,align="center"]

= Functional Mock-up Interface

The Functional Mock-up Interface (FMI) is a free standard that defines an interface to exchange dynamic models using a combination of xml files, binaries and C code.
It's supported by https://fmi-standard.org/tools/[100+] tools and maintained as a https://modelica.org/projects[Modelica Association Project].

== Repository structure

- `docs` -- sources of the specification document
- `headers` -- C header files
- `schema` -- the XSD schema for the modelDescription.xml

== Workflow and Branching

We follow the gitflow workflow, see, e.g., https://datasift.github.io/gitflow/IntroducingGitFlow.html

For the current work on the next planned releases of the FMI standard we use

- https://github.com/modelica/fmi-standard[master] only for released versions, i.e., currently for FMI 2.0
- https://github.com/modelica/fmi-standard/tree/release/2.0.1[release/2.0.1] for bugfixes, maintenance of the FMI 2.0 standard (no new features)
- https://github.com/modelica/fmi-standard/tree/develop[develop] for the development of the FMI 3.0 standard, used for merging features
- `feature/XXX` for the development of a new feature (when starting, branch for develop)

== Building the specification document

The FMI specification is written in http://asciidoc.org/[AsciiDoc], a plain-text mark-up format that can be converted to HTML, DocBook, PDF and other formats. To build the documentation locally

. https://www.ruby-lang.org/en/downloads/[Install Ruby]

. Install the https://asciidoctor.org/#installation[AsciiDoctor Ruby gem]

. https://help.github.com/articles/cloning-a-repository/[Clone] the repository

  git clone https://github.com/t-sommer/fmi-standard.git

. Change into the `docs` folder

  cd docs

. Generate the HTML document

  asciidoctor -b html5 fmi_specification.adoc

The generated `fmi_specification.html` can be viewed with any modern web browser.

== Copyright and license

Code and documentation copyright (C) 2008-2011 the MODELISAR consortium and 2012-2018 the Modelica Association Project "FMI". Code released under the https://opensource.org/licenses/bsd-license.html[BSD License].
Docs released under https://creativecommons.org/licenses/by-sa/4.0/[Attribution-ShareAlike 4.0 International].
