image::docs/images/FMI_logo_horizontal.svg[width=30%,align="center"]

= Functional Mock-up Interface

image::https://travis-ci.org/modelica/fmi-standard.svg?branch=master[link="https://travis-ci.org/modelica/fmi-standard"]

The Functional Mock-up Interface (FMI) is a free standard that defines an interface to exchange dynamic models using a combination of XML files, binaries and C code.
It's supported by https://fmi-standard.org/tools/[100+] tools and maintained as a https://modelica.org/projects[Modelica Association Project].

== Repository structure

- `docs` -- sources of the specification document
- `headers` -- header files of the C-API
- `schema` -- XSD schema for the modelDescription.xml
- <<CONTRIBUTING.adoc#,CONTRIBUTING.adoc>> -- info on contributing to the project and building the specification document
- <<README.adoc#,README.adoc>> -- this document

== Branches

- `master` -- development of the next release
- `support/2.0.1` -- maintenance of the 2.0 release
- `feature/*` -- development of features for the next release

== Copyright and license

Code and documentation copyright (C) 2008-2011 the MODELISAR consortium and 2012-2018 the Modelica Association Project "FMI".
Code released under the https://opensource.org/licenses/BSD-3-Clause[3-Clause BSD License].
Docs released under https://creativecommons.org/licenses/by-sa/4.0/[Attribution-ShareAlike 4.0 International].
