image::docs/images/FMI_logo_horizontal.svg[width=30%,align="center"]

= Functional Mock-up Interface

image:https://circleci.com/gh/modelica/fmi-standard.svg?style=svg["CircleCI", link="https://circleci.com/gh/modelica/fmi-standard"]

The Functional Mock-up Interface (FMI) is a free standard that defines an interface to exchange dynamic models using a combination of XML files, binaries and C code.
It's supported by https://fmi-standard.org/tools/[100+] tools and maintained as a https://modelica.org/projects[Modelica Association Project].

https://fmi-standard.org/downloads/[Releases] and the https://fmi-standard.org/docs/3.0-dev/[latest development version] of the specification are available on the https://fmi-standard.org/[FMI website].

== Repository Structure

- `docs` -- sources of the specification document
- `headers` -- header files of the C-API
- `schema` -- XSD schema for the modelDescription.xml
- <<CONTRIBUTING.adoc#,CONTRIBUTING.adoc>> -- info on contributing to the project and building the specification document
- <<README.adoc#,README.adoc>> -- this document

== Branches

- `master` -- development of the next release
- `support/v2.0.x` -- maintenance of the 2.0 release

== Copyright and License

Code and documentation copyright (C) 2008-2011 the MODELISAR consortium and 2012-2022 the Modelica Association Project FMI.
Code released under the https://opensource.org/licenses/BSD-2-Clause[2-Clause BSD License].
Docs released under https://creativecommons.org/licenses/by-sa/4.0/[Attribution-ShareAlike 4.0 International].
