=== Mathematical Notation [[mathematical-definitions]]

This section introduces the mathematical notation used throughout this document to describe:

 * <<ordinary-differential-equation,ordinary differential equations>> in state-space representations with discontinuities (events),
 * algebraic equation systems,
 * discrete-time equations (sampled-data systems).

FMU and <<importer>> use variables to exchange information.
The properties and semantics of variables are described in the <<modelDescription.xml>>.
Access to variable values is possible via appropriate <<API>> functions.

The <<independent>> variable latexmath:[t \in \mathbb{T}] _[typically: time]_ is a tuple latexmath:[t = (t_R,t_I)], where latexmath:[t_R \in \mathbb{R},\ t_{I} \in \mathbb{N} = \{0, 1, 2, \ldots\}].
The real part latexmath:[t_R] of this tuple is the <<independent>> variable of the FMU for describing the continuous-time behavior of the model between events.
During continuous-time integration the integer part of time latexmath:[t_I = 0].
latexmath:[t_I] is a counter to enumerate (and therefore distinguish) the events at the same continuous-time instant latexmath:[t_R].
This time definition is also called "super-dense time" in literature, see, for example, <<LZ07>>.
An ordering is defined on latexmath:[\mathbb{\textsf{T}}] that leads to the notation in <<table-model-exchange-math-notation>>.

.Conventions and notation used for time.
[#table-model-exchange-math-notation]
[cols="1,7,4",options="header"]
|====
|Operation
|Mathematical meaning
|Description

^|latexmath:[t_1 < t_2]
|latexmath:[(t_{\mathit{R}\hspace{0.1em}1},t_{\mathit{I}\hspace{0.1em}1}) < (t_{\mathit{R}\hspace{0.1em}2}, t_{\mathit{I}\hspace{0.1em}2})\ \Leftrightarrow \ t_{\mathit{R}\hspace{0.1em}1} < t_{\mathit{R}\hspace{0.1em}2}\ \textbf{or} \ ( t_{\mathit{R}\hspace{0.1em}1}= t_{\mathit{R}\hspace{0.1em}2} \ \textbf{and} \ t_{\mathit{I}\hspace{0.1em}1} < t_{\mathit{I}\hspace{0.1em}2}] )
|latexmath:[t_1] is before latexmath:[t_2]

^|latexmath:[t_1 = t_2]
|latexmath:[(t_{\mathit{R}\hspace{0.1em}1},t_{\mathit{I}\hspace{0.1em}1}) = (t_{\mathit{R}\hspace{0.1em}2},t_{\mathit{I}\hspace{0.1em}2}) \ \Leftrightarrow  t_{\mathit{R}\hspace{0.1em}1}= t_{\mathit{R}\hspace{0.1em}2}\ \textbf{and} \ t_{\mathit{I}\hspace{0.1em}1} = t_{\mathit{I}\hspace{0.1em}2}]
|latexmath:[t_1] is identical to latexmath:[t_2]

^|latexmath:[t^{+}]
|latexmath:[{(t_R,t_I)}^{+} \Leftrightarrow (\lim_{\mathit{\varepsilon \rightarrow 0}}{\left(t_R + \varepsilon \right),t_{\mathit{Imax}})}]
|right limit at latexmath:[t].
latexmath:[t_{\mathit{Imax}}] is the largest occurring integer index of super-dense time at this latexmath:[t_R]

^|latexmath:[^-t]
|latexmath:[^{-}{(t_R,t_I)} \Leftrightarrow (\lim_{\mathit{\varepsilon \rightarrow 0}}{\left( t_R - \varepsilon \right),0)}]
|left limit at latexmath:[t]

^|latexmath:[v^+(t)]
|latexmath:[v(t^+)]
|value at the right limit of latexmath:[t]

^|latexmath:[^{-}v(t)]
|latexmath:[v(^-t)]
|value at the left limit of latexmath:[t]

^|latexmath:[^{\bullet}v(t)]
|latexmath:[
\begin{cases}
^{\bullet}v(t) \\
^{\bullet}v(\left( t_R,t_I \right))
\end{cases}
\Leftrightarrow
\begin{cases}
 v(^-t) & \textsf{ during } v(\left( t_R, 0 \right)) \textsf{, } v \textsf{ not clocked }  \\
 v(\left( t_R,t_I - 1 \right)) & \textsf{ for } v(\left( t_R,t_I \right)) \textsf{ with } t_I > 0  \textsf{, } v \textsf{ not clocked } \\
 v \textsf{ at previous tick of k } & \textsf{ if } v \textsf{ is a clocked variable of clock k}
\end{cases}
]
a|previous value
|====

[NOTE]
====
Assume that an FMU has an event at latexmath:[t_R=2.1s] and here a variable changes discontinuously.
If no event iteration occurs, the time instant when the event occurs is defined as (2.1, 0), and the time instant when the integration is restarted is defined as (2.1, 1).
====

The hybrid <<ordinary-differential-equation,differential equations>> exposed by FMI for Model Exchange or wrapped by FMI for Co-Simulation are described as piecewise continuous-time systems.
Discontinuities can occur at time instants latexmath:[t_0, t_1, \ldots, t_n] where latexmath:[t_i < t_{i+1}].
These time instants are called `events`.
Events can be known beforehand (<<time event,time events>>), or are defined implicitly (<<state event,state event>> and step events), see below.
Between events, variables are either <<continuous>> or do not change their value.
A variable is called discrete-time, if it changes its value only at events.
Otherwise the variable is called continuous-time.
Only floating point variables can be continuous-time variables.
The following variable subscripts are used to describe the timing behavior of the corresponding variable (for example, latexmath:[\mathbf{v}_d] is a discrete-time variable):

.Conventions and notation used for variable subscripts.
[#table-subscripts]
[cols="5a,20a",options="header"]
|====
|Subscript
|Description

|`c`
|A continuous-time variable is a floating-point variable representing a continuous function of time inside each interval latexmath:[t_i^+ < \ ^-t_{i+1}].

|`d`
|A discrete-time variable changes its value only at event instants latexmath:[t = (t_R, t_I)].
Such a variable can change multiple times at the same continuous-time instant, but only at subsequent super-dense time instants latexmath:[t_I \in \mathbb{N} = \{0, 1, 2, \ldots\}].

|`k`
|A <<clocked-variable,clocked variable>> is a discrete-time variable associated with a <<Clock>>.
<<Clock>> (not clocked) variables synchronize events with the importer and across FMUs, they carry the information that a specific event happens.

|`c+d`
|A set of continuous-time and discrete-time variables.

|`d-k`
|A set of non-clocked, discrete-time variables.

|`u`
|Intermediate variables: a set of variables accessible in <<IntermediateUpdateMode>>.
These variables are continuous-time variables.

|`start`
|A variable at the start time of the simulation as defined by the argument <<startTime>> of <<fmi3EnterInitializationMode>>.

|`attribute = value`
|A set of variables which have an <<XML>> attribute-value combination as defined.

[NOTE]
====
Example: latexmath:[\mathbf{v}_{\mathit{initial=exact}}] are variables defined with attribute <<initial>> = <<exact>> (see <<ModelVariables>>).
====

|====

At every event instant latexmath:[t_i], continuous-time variables might change discontinuously (see <<figure-piecewise-continuous-variables>>):

.Piecewise-continuous variables of an FMU: continuous-time (latexmath:[\mathbf{v}_c]), discrete-time (latexmath:[\mathbf{v}_d]) and clocked (latexmath:[\mathbf{v}_k]).
[#figure-piecewise-continuous-variables]
image::images/PieceWiseContinuousVariables.svg[width=400]

The mathematical description of an FMU uses the following variables, where bold variables (e.g. latexmath:[\mathbf{v}]) indicate vectors and italic variables (e.g. latexmath:[t]) denote scalars:

.Symbols for specific variable types.
[#table-variable-types]
[cols="1,10",options="header"]
|====
|Variable
|Description

a|latexmath:[t]
a|<<independent>> variable

NOTE: typically: time

latexmath:[\in \mathbb{T}].
This variable is defined with <<causality>> = <<independent>>.
All other variables are functions of this independent variable.

For Co-Simulation and Scheduled Execution:

* The i-th communication point is denoted as latexmath:[t_i]. +
* The communication step size is denoted as latexmath:[h_i = t_{i+1} - t_i]. +

|latexmath:[\mathbf{v}]
|All exposed variables as listed in <<ModelVariables>>.
A subset of variables is selected via a <<table-subscripts,subscript>>.

|latexmath:[\mathbf{p}]
|Parameters.
The symbol without a subscript references variables with <<causality>> = <<parameter>>.
A subset of parameters is selected via a <<table-subscripts,subscript>>.

|latexmath:[\mathbf{u}]
|Input variables.
The values of these variables are defined outside of the model.
Variables of this type are defined with attribute <<causality>> = <<input>>.
A subset of inputs is selected via a <<table-subscripts,subscript>>.

|latexmath:[\mathbf{y}] +
latexmath:[\mathbf{y}^{(j)}]
|Output variables.
The values of these variables are computed in the FMU and they are designed to be used outside the FMU.
Variables of this type are defined with attribute <<causality>> = <<output>>.
For <<CS>>: Also j-th derivatives latexmath:[\mathbf{y}^{(j)}(t_{i+1})] can be provided if supported by the FMU.
A subset of outputs is selected via a <<table-subscripts,subscript>>.

|latexmath:[\mathbf{w}]
|Local variables of the FMU that must not be used for FMU connections.
Variables of this type are defined with attribute <<causality>> = <<local>>.
A subset of local variables is selected via a <<table-subscripts,subscript>>.

|latexmath:[\mathbf{k}]
|<<Clock>> variables.

|latexmath:[\mathbf{z}]
|A vector of floating point continuous-time variables representing the <<state-event,event indicators>> used to locate <<state event,state events>>.

|[[state,state]]latexmath:[\mathbf{x}_c] +
latexmath:[\mathbf{\dot{x}}_c]
|A vector of floating point continuous-time variables representing the continuous-time <<state,states>>. +
A vector of floating point continuous-time variables representing the first derivatives of the continuous-time <<state,states>>.

|latexmath:[\mathbf{x}_d] +
latexmath:[^{\bullet}\mathbf{x}_d]
|latexmath:[\mathbf{x}_d] is a vector of (internal) discrete-time variables (of any type) representing the discrete-time states. +
latexmath:[{}^{\bullet}\mathbf{x}_d] is the value of latexmath:[\mathbf{x}_d] at the previous super-dense time instant. +

|latexmath:[T_{\mathit{next}}]
|At an event instant, an FMU can define the next time instant latexmath:[T_{\mathit{next}}], at which the next time event occurs (see also the definition of <<EventMode,events>>).
Every event removes automatically a previous definition of latexmath:[T_{\mathit{next}}], and it must be explicitly defined again, even if a previously defined latexmath:[T_{\mathit{next}}] was not yet reached (see <<fmi3UpdateDiscreteStates>>).

|[[relations,relations]] latexmath:[\mathbf{r}]
a|A vector of Boolean variables representing relations: latexmath:[\mathbf{r}_j := \mathbf{z}_j > 0].
When entering <<ContinuousTimeMode>> all relations reported via the event indicators latexmath:[\mathbf{z}] are fixed and during this mode these relations are replaced by latexmath:[^{\bullet}\mathbf{r}].
Only during <<InitializationMode>> or <<EventMode>> the domains latexmath:[\mathbf{z}_j > 0] can change.

NOTE: For more details, see <<frozen-relations,Remark 3>> below.

|[[buffers,buffers]] latexmath:[\mathbf{b}]
a|Hidden data of the FMU.

NOTE: For example, delay buffers in Model Exchange FMUs that are used in <<ContinuousTimeMode>>.

|====
