=== Mathematical Definitions [[mathematical-definitions]]

The goal of the Model Exchange interface is to numerically solve a system of differential, algebraic and discrete-time equations.
In this version of the interface, ordinary differential equations in state-space representation with events are handled (abbreviated as "hybrid ODE").
Algebraic equation systems might be contained inside the FMU.
Also, the FMU might consist of discrete-time equations only, for example, describing a sampled-data controller.

The <<independent>> variable latexmath:[t \in \mathbb{T}] _[typically: time]_ is a tuple latexmath:[t = (t_R,t_I)], where latexmath:[t_R \in \mathbb{R},\ t_{I} \in \mathbb{N} = \{0, 1, 2, \ldots\}].
The real part latexmath:[t_R] of this tuple is the <<independent>> variable of the FMU for describing the continuous-time behavior of the model between events.
During continuous-time integration latexmath:[t_I = 0].
The integer part latexmath:[t_I] of this tuple is a counter to enumerate (and therefore distinguish) the events at the same continuous-time instant latexmath:[t_R].
This time definition is also called "super-dense time" in literature, see, for example, <<LZ07>>.
An ordering is defined on latexmath:[\mathbb{\text{T}}] that leads to the notation in <<table-model-exchange-math-notation>>.
_[The notation latexmath:[^{\bullet}t] is from <<BCP10,BCP10>>, adapted from non-standard analysis to super-dense time, in order to precisely define the value from the previous event iteration.]_

.Conventions and notation used.
[#table-model-exchange-math-notation]
[cols="1,7,4"]
|====
|Operation
|Mathematical meaning
|Description

^|latexmath:[t_1 < t_2]
|latexmath:[(t_{\mathit{R1}},t_{\mathit{I1}}) < (t_{\mathit{R2}}, t_{\mathit{I2}})\ \Leftrightarrow \ t_{\mathit{R1}} < t_{\mathit{R2}}\ \textbf{or} \ t_{\mathit{R1}}= t_{\mathit{R2}} \ \textbf{and} \ t_{\mathit{I1}} < t_{\mathit{I2}}]
|latexmath:[t_1] is before latexmath:[t_2]

^|latexmath:[t_1 = t_2]
|latexmath:[(t_{\mathit{R1}},t_{\mathit{I1}}) = (t_{\mathit{R2}},t_{\mathit{I2}}) \ \Leftrightarrow  t_{\mathit{R1}}= t_{\mathit{R2}}\ \textbf{and} \ t_{\mathit{I1}} = t_{\mathit{I2}}]
|latexmath:[t_1] is identical to latexmath:[t_2]

^|latexmath:[t^{+}]
|latexmath:[{{(t}_{R},t_{I})}^{+} \Leftrightarrow (\lim_{\mathit{\epsilon \rightarrow 0}}{\left(t_{R} + \varepsilon \right),t_{\mathit{Imax}})}]
|right limit at latexmath:[t].
latexmath:[t_{\mathit{Imax}}] is the largest occurring integer index of super-dense time

^|latexmath:[^-t]
|latexmath:[^{-}{{(t}_{R},t_{I})} \Leftrightarrow (\lim_{\mathit{\epsilon \rightarrow 0}}{\left( t_{R} - \varepsilon \right),0)}]
|left limit at latexmath:[t]

^|latexmath:[^{\bullet}t]
|latexmath:[^{\bullet}{\left( t_{R},t_{I} \right)\ } \Leftrightarrow \left\{ \begin{matrix} ^-t \ & \mathbf{if} \ t_I = 0 \\ (t_R, t_I - 1) \ & \mathbf{if} \ t_I > 0 \\ \end{matrix} \right.]
|previous time instant (= either left limit or previous event instant).

^|latexmath:[v^+]
|latexmath:[v(t^+)]
|value at the right limit of latexmath:[t]

^|latexmath:[^{-}v]
|latexmath:[v(^-t)]
|value at the left limit of latexmath:[t]

^|latexmath:[^{\bullet}v]
|latexmath:[v(^{\bullet}t)]
|previous value (= either left limit or value from the previous event)
|====

_[Assume that an FMU has an event at latexmath:[t_R=2.1s] and here a signal changes discontinuously._
_If no event iteration occurs, the time instant when the event occurs is defined as (2.1, 0), and the time instant when the integration is restarted is defined as (2.1, 1).]_

The hybrid ODEs supported by FMI are described as piecewise continuous-time systems.
Discontinuities can occur at time instants latexmath:[t_0, t_1, \ldots, t_n] where latexmath:[t_i < t_{i+1}].
These time instants are called `events`.
Events can be known before hand (= <<time event>>), or are defined implicitly (= <<state event,`state`>> and <<step event,`step events`>>), see below.
Between events, variables are either <<continuous>> or do not change their value.
A variable is called discrete-time, if it changes its value only at an event instant.
Otherwise the variable is called continuous-time.
Only floating point variables can be continuous-time.
The following variable indices are used to describe the timing behavior of the corresponding variable (for example, latexmath:[v_d] is a discrete-time variable):

[cols="1,10"]
|====
|Index
|Description

|`x`
|A continuous-time variable latexmath:[x(t)],
is a continuous function of time inside each interval latexmath:[t_i^+ < \ ^-t_{i+1}]

|`m`
|A piece-wise <<constant>> variable latexmath:[m(t)], is constant inside each interval latexmath:[t_i^+ < \ ^-t_{i+1}].

|`c`
| A *Clock* variable latexmath:[c(t)], is active only at particular time instants.

|`r`
|A *Clocked* variable latexmath:[r(t)], is a variable of a numeric type, string or enumeration associated to a <<clock>> latexmath:[c(t)] and therefore active only at particular time instants.

|====
At every event instant latexmath:[t_i], variables might be discontinuous (see <<figure-piecewise-continuous-variables>>).

.Piecewise-continuous variables of an FMU: continuous-time (latexmath:[v_c]) and discrete-time (latexmath:[v_d]).
[#figure-piecewise-continuous-variables]
image::images/PieceWiseContinuousVariables.svg[width=60%]

The next event instance latexmath:[t_i] is defined by the earliest occurrence of one of the following conditions:

. The environment of the FMU triggers an event at the current time instant because at least one discrete-time <<input>> changes its value, a continuous-time <<input>> has a discontinuous change, or a <<tunable>> <<parameter>> changes its value.
_[Note that if an FMU A is connected to an FMU B, and an event is triggered for A, then potentially all <<output,`outputs`>> of A will be discontinuous at this time instant._
_It is therefore advisable to move B into *Event Mode* at this time instant too if an <<output>> of A is connected to B._
_This means to call <<fmi3EnterEventMode>> on B.]_ +
+
All the following events are internal events:

. At a predefined time instant latexmath:[t_i=T_{\mathit{next}}(t_{i-1}, 0)] that was defined at the previous event instant latexmath:[t_{i-1}] by the FMU.
Such an event is called <<time event>>.

. At a time instant, where an event indicator latexmath:[z_j(t)] changes its domain from latexmath:[z_j > 0] to latexmath:[z_j \leq 0] or from latexmath:[z_j \leq 0] to latexmath:[z_j > 0] (see <<figure-events>>).
More precisely: An event latexmath:[t = t_i] occurs at the smallest time instant latexmath:[t] with latexmath:[t>t_{i-1}] where latexmath:[(z_j(t)>0) \neq (z_j(t_{i-1}) >0)].
Such an event is called <<state event>>.
_[This definition is slightly different from the standard definition of <<state event,`state events`>>: _ latexmath:[z_j(t) \cdot z_j(t_{i-1}) \leq 0] _._
_This often used definition has the severe drawback that_ latexmath:[z_j(t_{i-1}) \neq 0] _is required in order to be well-defined and this condition cannot be guaranteed.]._
All event indicators are piecewise continuous and are collected together in one vector of floating point numbers latexmath:[\mathbf{z(t)}]. +

.An event occurs when the event indicator changes its domain from latexmath:[z>0] to latexmath:[z\leq 0] or vice versa.
[#figure-events]
image::images/Event.svg[width=60%, align="center"]

[start=4]
. At every completed step of an integrator, <<fmi3CompletedIntegratorStep>> must be called (provided the capability flag `completedIntegratorStepNotNeeded` of `<fmiModelDescription>` is `false`).
An event occurs at this time instant, if indicated by the return argument `enterEventMode == fmi3True`.
Such an event is called <<step event>>.
_[<<step event,`Step events`>> are, for example, used to dynamically change the (continuous) <<state,`states`>> of a model internally in the FMU, because the previous states are no longer suited numerically.]_

An FMI Model-Exchange model is described by the following variables:

[cols="1,10"]
|====
|Variable
|Description

|latexmath:[t]
|<<independent>> variable _[typically: time]_ latexmath:[\in \mathbb{T}].
(Variable defined with <<causality>> = <<independent>>).

|latexmath:[\mathbf{v}]
|A vector of all exposed variables (all variables defined in element `<ModelVariables>`, see <<definition-of-model-variables>>).
A subset of the variables is selected via a subscript.
Example: latexmath:[\mathbf{v}_{\mathit{initial=exact}}] are variables defined with attribute <<initial>> = <<exact>> (see <<definition-of-model-variables>>).
These are <<parameter,`parameters`>> and start values of other variables, such as initial values for <<state,`states`>>, state derivatives or <<output,`outputs`>>.

|latexmath:[\mathbf{p}]
|Parameters that are constant during simulation.
The symbol without a subscript references <<parameter,`parameters`>> (variables with <<causality>> = <<parameter>>).
Dependent <<parameter,`parameters`>> (variables with <<causality>> = <<calculatedParameter>>) are denoted as latexmath:[\mathbf{p}_{\mathit{calculated}}].

|latexmath:[\mathbf{u}(t)]
|Input variables.
The values of these variables are defined outside of the model.
Variables of this type are defined with attribute <<causality>> = <<input>>.
Whether the <<input>> is a discrete-time or continuous-time variable is defined via attribute <<variability>> = <<discrete>> or <<continuous>> (see <<definition-of-model-variables>>).

|latexmath:[\mathbf{y}(t)]
|Output variables.
The values of these variables are computed in the FMU and they are designed to be used in a model connection.
For instance, output variables might be used in the environment as input values to other FMUs or other submodels.
Variables of this type are defined with attribute <<causality>> = <<output>>.
Whether the <<output>> is a discrete-time or continuous-time variable is defined via attribute <<variability>> = <<discrete>> or <<continuous>> (see <<definition-of-model-variables>>).

|latexmath:[\mathbf{w}(t)]
|Local variables of the FMU that cannot be used for FMU connections.
Variables of this type are defined with attribute <<causality>> = <<local>>, see <<definition-of-model-variables>>.

|latexmath:[\mathbf{z}(t)]
|A vector of floating point continuous-time variables representing the event indicators used to define <<state event,`state events`>> (recall <<figure-events>>).
For notational convenience, an event indicator is conceptually treated as a different type of variable as an <<output>> or a <<local>> variable for the mathematical description in <<table-math-model-exchange>>.
In reality, event indicator is however part of the <<output,`outputs`>> latexmath:[\mathbf{y}] or the <<local>> variables latexmath:[\mathbf{w}] of an FMU.

|latexmath:[\mathbf{x}_c(t)]
|A vector of floating point continuous-time variables representing the continuous-time <<state,`states`>>.
For notational convenience, a continuous-time <<state>> is conceptually treated as a different type of variable as an <<output>> or a <<local>> variable for the mathematical description in <<table-math-model-exchange>>.
In reality, a continuous-time <<state>> is however part of the <<output,`outputs`>> latexmath:[\mathbf{y}] or the <<local>> variables latexmath:[\mathbf{w}] of an FMU.

|latexmath:[\mathbf{x}_d(t)] +
latexmath:[^{\bullet}\mathbf{x}_d(t)]
|latexmath:[\mathbf{x}_d(t)] is a vector of (internal) discrete-time variables (of any type) representing the discrete-time states. +
latexmath:[{}^{\bullet}\mathbf{x}_d(t)] is the value of latexmath:[\mathbf{x}_d(t)] at the previous super-dense time instant, so latexmath:[{}^{\bullet}\mathbf{x}_d(t)=\mathbf{x}_d({}^{\bullet}t)].
Given the previous values of the discrete-time states, latexmath:[{}^{\bullet}\mathbf{x}_d(t)], at the actual time instant latexmath:[t], all other discrete-time variables, especially the discrete-time states latexmath:[\mathbf{x}_d(t)], can be computed. +
Discrete-time states are not visible in the interface of an FMU and are only introduced here to clarify the mathematical description.
In reality, a discrete-time state is part of the <<output,`outputs`>> latexmath:[\mathbf{y}] or the <<local>> variables latexmath:[\mathbf{w}] of an FMU.

|latexmath:[T_{\mathit{next}}(t_{i})]
|At initialization or at an event instant, an FMU can define the next time instant latexmath:[T_{\mathit{next}}], at which the next time event occurs (see also the definition of events above).
Every event removes automatically a previous definition of latexmath:[T_{\mathit{next}}], and it must be explicitly defined again, event if a previously defined latexmath:[T_{\mathit{next}}] was not triggered at the current event instant.

|latexmath:[\mathbf{r}(t_i)]
|A vector of Boolean variables with latexmath:[r_{j} := z_{j} > 0].
When entering *Continuous-Time Mode* all relations reported via the event indicators latexmath:[\mathbf{z}] are fixed and during this mode these relations are replaced by latexmath:[\mathbf{r}].
Only during *Initialization Mode* or *Event Mode* the domains latexmath:[z_{j} > 0] can be changed.
For notational convenience, latexmath:[\mathbf{r} := \mathbf{z} > 0] is an abbreviation for latexmath:[\mathbf{r}:=\{z_1>0, z_2>0, \ldots \}].
_[For more details, see <<Remark3,Remark 3>> below.]_
|====
