=== FMU Distribution

An FMU description consists of several files. 
n FMU implementation may be distributed in source code and/or in binary format.
All relevant files are stored in a ZIP file with a pre-defined structure.
The implementation must either implement all the functions of FMI for Model Exchange
or all the functions of FMI for Co-Simulation or both.
The extension of the ZIP file must be "**.fmu**",
for example, "HybridVehicle.fmu".
The compression method used for the ZIP file must be "deflate" _[(most free tools,
such as zlib, offer only the common compression method "deflate")]_.

Every FMU is distributed with its own ZIP file.
This ZIP file has the following structure:

----
// Structure of ZIP file of an FMU
modelDescription.xml      // Description of FMU (required file)
model.png                 // Optional image file of FMU icon
documentation             // Optional directory containing the FMU documentation
index.html                // Entry point of the documentation
<other documentation files>
sources                   // Optional directory containing all C sources
   // all needed C sources and C header files to compile and link the FMU
   // with exception of: fmi2TypesPlatform.h , fmi2FunctionTypes.h and fmi2Functions.h
   // The files to be compiled (but not the files included from these files)
   // have to be reported in the XML file under the structure
   // <ModelExchange><SourceFiles> ... and <CoSimulation><SourceFiles>
binaries                     // Optional directory containing the binaries win32 // Optional binaries for 32-bit Windows
   win32                     // Optional binaries for 32-bit Windows
      <modelIdentifier>.dll  // DLL of the FMI implementation
                             // (build with option "MT" to include run-time environment)
      <other DLLs>           // The DLL can include other DLLs
      // Optional object Libraries for a particular compiler VisualStudio8
      VisualStudio8        // Binaries for 32-bit Windows generated with
                           // Microsoft Visual Studio 8 (2005)
         <modelIdentifier>.lib   // Binary libraries
      gcc3.1               // Binaries for gcc 3.1.
         ...
  win64      // Optional binaries for 64-bit Windows
     ...
  linux32    // Optional binaries for 32-bit Linux
     <modelIdentifier>.so    // Shared library of the FMI implementation
     ...
  linux64    // Optional binaries for 64-bit Linux
     ...
resources    // Optional resources needed by the FMU
   < data in FMU specific files which will be read during initialization;
     also more folders can be added under resources (tool/model specific).
     In order for the FMU to access these resource files, the resource directory
     must be available in unzipped form and the absolute path to this directory
     must be reported via argument "fmuResourceLocation" via fmi2Instantiate.
   >
----

An FMU has to implement all common functions (according to tables in sections 3.2.3 and 4.2.4).
ModelExchange FMUs have to provide additionally the respective Model Exchange function,
CoSimulation FMUs the Co-Simulation functions.

The FMU must be distributed with [underline]#at least# one implementation,
in other words, either [underline]#sources# or one of the [underline]#binaries# for a particular machine.
It is also possible to provide the sources and binaries for different target machines together in one ZIP file.
The following names are standardized: for Windows: "win32",
"win64"- for Linux: "linux32", "linux64", for Mac: "darwin32", "darwin64".
Furthermore, also the names "VisualStudioX" and "gccX" are standardized and define
the compiler with which the binary has been generated _[, for example, VisualStudio8]_.
Further names can be introduced by vendors.
Dynamic link libraries must include all referenced resources that are not available
on a standard target machine
_[for example, DLLs on Windows machines must be built with option "MT" to include
the run-time environment of VisualStudio in the DLL,
and not use the option "MD" where this is not the case]_.
When compiling a shared object on Linux,
`RPATH="$ORIGIN"` has to be set when generating the shared object in order that shared objects used from it,
can be dynamically loaded.

Typical scenarios are to provide binaries only for one machine type (for example, on the machine where the target simulator is running and for which licenses of run-time libraries are available) or to provide only sources (for example, for translation and download for a particular micro-processor).
If run-time libraries cannot be shipped due to licensing,
special handling is needed,
for example, by providing the run-time libraries at appropriate places by the receiver.

FMI provides the means for two kinds of implementation: `needsExecutionTool = "true"` and `needsExecutionTool = "false"`.
In the first case a tool specific wrapper DLL/SharedObject has to be provided as the binary,
in the second a compiled or source code version of the model with its solver is stored (see section 4.3.1 for details).

In an FMU both a version for ModelExchange and for CoSimulation might be present.
If in both cases the executable part is provided as DLL/SharedObject,
then two different or only one library can be provided.
The library names are defined in the `modelIdentifier` attribute of elements
`fmiModelDescription.ModelExchange` and `fmiModelDescription.CoSimulation`:

----
[Example for different libraries:
  binaries
     win32
        MyModel_ModelExchange.dll   // ModelExchange.modelIdentifier =
                                    //    "MyModel_ModelExchange"
        MyModel_CoSimulation.dll    // CoSimulation.modelIdentifier =
                                    //    "MyModel_CoSimulation"
]
----

The usual distribution of an FMU will be with DLLs/SharedObjects because then
further automatic processing _[(for example, importing into another tool)]_ is possible. +
If run-time libraries are needed by the FMU that have to be present on the target machine,
then automatic processing is likely impossible.
The requirements and the expected processing should be documented in the `documentation` directory in this case. +
A source-based distribution might require manual interaction in order that it can be utilized.
The intention is to support platforms that are not known in advance (such as HIL-platforms or micro-controllers).
Typically, in such a case the complete source code in ANSI-C is provided
(for example, one C source file that includes all other needed C files with the `#include` directive).
All C source file names that need to be defined in a compiler directive have to
be defined in the XML file under structure `<ModelExchange><SourceFiles>`
and `<CoSimulation><SourceFiles>`.
These files may include other files.
`#include` directive with `""` should be used for header-filers distributed
in the FMU instead of using `<...>`.
If default options of the compiler are sufficient,
it might then be possible to automatically process such source code FMUs.
An exporting tool should give documentation on how to build an executable,
either via a documentation file and/or via a template makefile for a particular platform,
from which a user can construct the makefile for his/her target platform.
This documentation should be stored in the `documentation` directory,
possibly with a link to the template makefile (stored in the `sources` directory).
_[As template makefile, CMake (http://www.cmake.org), a cross- platform,
open-source build system might be used.]_ +
In directory `resources`,
additional data can be provided in FMU specific formats,
typically for tables and maps used in the FMU.
This data must be read into the model at the latest during initialization
(that is, before `fmi2ExitInitializationMode` is called).
The actual file names in the ZIP file to access the data files can either
be hard-coded in the generated FMU functions,
or the file names can be provided as string parameters via the `fmi2SetString` function.
_[Note that the absolute file name of the resource directory
is provided by the initialization functions]_.
In the case of a co-simulation implementation of `needsExecutionTool = "true"` type,
the `resources` directory can contain the model file in the tool specific file format.

_[Note that the header files `fmi2TypesPlatform.h` and `fmi2FunctionTypes.h/fmi2Functions.h`
are not included in the FMU due to the following reasons:_

_`fmi2TypesPlatform.h` makes no sense in the `sources` directory,
because if sources are provided,
then the target simulator defines this header file and not the FMU. +
This header file is not included in the `binaries` directory,
because it is implicitly defined by the platform directory
(for example, win32 for 32-bit machine or linux64 for 64-bit machine).
Furthermore, the version that was used to construct the FMU can also
be inquired via function `fmi2GetTypesPlatform()`._

_`fmi2FunctionTypes.h/fmi2Functions.h` are not needed in the `sources` directory,
because they are implicitly defined by attribute `fmiVersion` in file `modelDescription.xml`.
Furthermore, in order that the C compiler can check for consistent function arguments,
the header file from the target simulator should be used when compiling the C sources.
It would therefore be counter-productive (unsafe)
if this header file was present. +
These header files are not included in the `binaries` directory,
since they are already utilized to build the target simulator executable.
The version number of the header file used to construct
the FMU can be deduced via attribute `fmiVersion` in file
`modelDescription.xml` or via function call `fmi2GetVersion()`.]_

