=== FMU Distribution

An FMU description consists of several files.
An FMU implementation may be distributed in source code and/or in binary format.
All relevant files are stored in a ZIP file with a pre-defined structure.
The implementation must either implement all the functions of FMI for Model Exchange or all the functions of FMI for Co-Simulation or both.
Specifically it is required that all functions specified for Model Exchange and/or Co-Simulation are present, even if they are only needed for capabilities that the FMU does not support.
The behavior of those functions is unspecified, so while calling environments can rely on the functions being present, they cannot rely on any particular behavior for functions only needed for capabilities the FMU does not support.
The extension of the ZIP file must be "**.fmu**",
for example, "HybridVehicle.fmu".

The compression method for all files stored in the ZIP archive must be either 8 (`deflate`), or 0 (`store`).
Only files stored using compression method 8 (`deflate`) may be stored with general purpose bit 3 set.
The field `version needed to extract` of the archive must not be higher than 2.0, and encryption must not be employed.
The archive must not be a split or spanned ZIP archive.
Links must not be used inside the ZIP archive.
 _[These restrictions ensure broad compatibility of the archive with common ZIP processing tools and libraries.]_
 
The zip format specification can be found here https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
_[Note especially section 4.4.17 states that backslashes "\" are forbidden as path separator only forward slashes "/" are allowed.]_

_[Note: non-ASCII directory names are not explicitly forbidden, but might pose a problem on different operating systems and are thus dicouraged.]_

Every FMU is distributed with its own ZIP file.
This ZIP file has the following structure:

----
// Structure of ZIP file of an FMU
modelDescription.xml      // Description of FMU (required file)
model.png                 // Optional image file of FMU icon
documentation             // Optional directory containing the FMU documentation
    index.html            // Entry point of the documentation
    externalDependencies.{txt|html}  // documentation of external resources required to load or simulate the FMU
    <other documentation files>
    licenses                    // Optional directory for licenses
        license.{txt,html}      // Entry point for license information
        <license files>         // For example BSD licenses
sources                   // Optional directory containing all C sources
   // all needed C sources and C header files to compile and link the FMU
   // with exception of: fmi2TypesPlatform.h , fmi2FunctionTypes.h and fmi2Functions.h
   // The files to be compiled (but not the files included from these files)
   // have to be reported in the XML file under the structure
   // <ModelExchange><SourceFiles> ... and <CoSimulation><SourceFiles>
   buildDescription.xml      // Optional build description file
binaries                     // Optional directory containing the binaries win32 // Optional binaries for 32-bit Windows
   win32                     // Optional binaries for 32-bit Windows
      <modelIdentifier>.dll  // DLL of the FMI implementation
                             // (build with option "MT" to include run-time environment)
      <other DLLs>           // The DLL can include other DLLs
      // Optional object Libraries for a particular compiler VisualStudio8
      VisualStudio8        // Binaries for 32-bit Windows generated with
                           // Microsoft Visual Studio 8 (2005)
         <modelIdentifier>.lib   // Binary libraries
      gcc3.1               // Binaries for gcc 3.1.
         ...
  win64      // Optional binaries for 64-bit Windows
     ...
  linux32    // Optional binaries for 32-bit Linux
     <modelIdentifier>.so    // Shared library of the FMI implementation
     ...
  linux64    // Optional binaries for 64-bit Linux
     ...
  aarch64-darwin  // Optional binaries for macOS on Apple Silicon
     <modelIdentifier>.dylib
     ...
  < If an FMU is run through one of its binaries all items in that binary folder is recommended to be unpacked at the same location as the binary < modelIdentifier >.* is unpacked.
   If not it's likely that, if the FMU has dependencies on those items, it will not be able to find them and run >
resources    // Optional resources needed by the FMU
   < data in FMU specific files which will be read during initialization;
     also more folders can be added under resources (tool/model specific).
     In order for the FMU to access these resource files, the resource directory
     must be available in unzipped form and the absolute path to this directory
     must be reported via argument "fmuResourceLocation" via fmi2Instantiate.
extra                         // Additional (meta-)data of the FMU (optional)
   // additional (meta-)data that is supposed to travel with the FMU;
   // see below for structure and content definition.
   >
terminalsAndIcons          // Optional directory containing Terminals and Icons resources
    terminalsAndIcons.xml  // Optional file defining the Terminals and Icons
----

An FMU has to implement all common functions (according to tables in sections 3.2.3 and 4.2.4).
ModelExchange FMUs have to provide additionally the respective Model Exchange function,
CoSimulation FMUs the Co-Simulation functions.

The FMU must be distributed with [underline]#at least# one implementation,
in other words, either [underline]#sources# or one of the [underline]#binaries# for a particular machine.
It is also possible to provide the sources and binaries for different target machines together in one ZIP file.
The following names are standardized: for Windows: "win32",
"win64"- for Linux: "linux32", "linux64", for Macintosh: "darwin32", "darwin64" where "32" stands for "32-bit x86" and "64" for "64-bit x86" respectively.
For any other platforms the "platform tuples" defined in the FMI 3.0 Specification, 2.5.1.4.1. Platform Tuple Definition, or any updated "platform tuples" published by MAP FMI on fmi-standard.org, should be used.
Furthermore, also the names "VisualStudioX" and "gccX" are standardized and define
the compiler with which the binary has been generated _[, for example, VisualStudio8]_.
Further names can be introduced by vendors.
FMUs should contain all resources that are required to load and execute a shared library, link against a static library, or compile from source.
Shared libraries should be statically linked against their dependencies _[e.g. the Visual Studio C Runtime on Windows]_.
`RPATH="$ORIGIN"` should be set when building ELF binaries to allow dynamic loading of dependencies on the target machine.
If the FMU depends on external resources _[e.g. shared libraries, files, or servers]_ to be loaded or simulated `documentation/externalDependencies.{txt|html}` should be present to document these dependencies and how to provide them.

Typical scenarios are to provide binaries only for one machine type (for example, on the machine where the target simulator is running and for which licenses of run-time libraries are available) or to provide only sources (for example, for translation and download for a particular micro-processor).
If run-time libraries cannot be shipped due to licensing,
special handling is needed,
for example, by providing the run-time libraries at appropriate places by the receiver.

FMI provides the means for two kinds of implementation: `needsExecutionTool = "true"` and `needsExecutionTool = "false"`.
In the first case a tool specific wrapper DLL/SharedObject has to be provided as the binary,
in the second a compiled or source code version of the model with its solver is stored (see section 4.3.1 for details).

In an FMU both a version for ModelExchange and for CoSimulation might be present.
If in both cases the executable part is provided as DLL/SharedObject,
then two different or only one library can be provided.
The library names are defined in the `modelIdentifier` attribute of elements
`fmiModelDescription.ModelExchange` and `fmiModelDescription.CoSimulation`:

----
[Example for different libraries:
  binaries
     win32
        MyModel_ModelExchange.dll   // ModelExchange.modelIdentifier =
                                    //    "MyModel_ModelExchange"
        MyModel_CoSimulation.dll    // CoSimulation.modelIdentifier =
                                    //    "MyModel_CoSimulation"
]
----

The usual distribution of an FMU will be with DLLs/SharedObjects because then
further automatic processing _[(for example, importing into another tool)]_ is possible. +
If run-time libraries are needed by the FMU that have to be present on the target machine,
then automatic processing is likely impossible.
The requirements and the expected processing should be documented in the `documentation` directory in this case. +
A source-based distribution might require manual interaction in order that it can be utilized.
The intention is to support platforms that are not known in advance (such as HIL-platforms or micro-controllers).
Typically, in such a case the complete source code in ANSI-C is provided
(for example, one C source file that includes all other needed C files with the `#include` directive).
All C source file names that need to be defined in a compiler directive have to
be defined in the XML file under structure `<ModelExchange><SourceFiles>`
and `<CoSimulation><SourceFiles>`.
These files may include other files.
The `#include` directive with `""` should be used for header-files distributed
in the FMU instead of using angle brackets`<>`.
If default options of the compiler are sufficient,
it might then be possible to automatically process such source code FMUs.
An exporting tool should give documentation on how to build an executable,
either via a documentation file and/or via a template makefile for a particular platform,
from which a user can construct the makefile for his/her target platform.
This documentation should be stored in the `documentation` directory,
possibly with a link to the template makefile (stored in the `sources` directory).
_[As template makefile, CMake (http://www.cmake.org), a cross- platform,
open-source build system might be used.]_ +
In addtition to the `<SourceFiles>` element a `buildDescription.xml` can be supplied in the sources directory (as defined in the FMI 3.0 Specification, 2.4.10. Build Configurations).
_[New in FMI 2.0.4:]_ If a `buildDescription.xml` file is present in the `sources` directory it should take precedence over the `<SourceFiles>` element in the `modelDescription.xml`. +
The sub-directory `licenses` can be used to bundle all license files.
_[It is strongly recommended to include all license and copyright related
information in the licenses folder of an FMU (especially but not only
for contained open source software) - the license.{html,txt} file can serve
as an entry point for describing the contained licenses. This will help the users
to comply with license conditions when passing source or binary code
contained in an an FMU to other persons or organizations.]_

In directory `resources`,
additional data can be provided in FMU specific formats,
typically for tables and maps used in the FMU.
This data must be read into the model at the latest during initialization
(that is, before `fmi2ExitInitializationMode` is called).
The actual file names in the ZIP file to access the data files can either
be hard-coded in the generated FMU functions,
or the file names can be provided as string parameters via the `fmi2SetString` function.
_[Note that the absolute file name of the resource directory
is provided by the initialization functions]_.
In the case of a co-simulation implementation of `needsExecutionTool = "true"` type,
the `resources` directory can contain the model file in the tool specific file format.

_[Note that the header files `fmi2TypesPlatform.h` and `fmi2FunctionTypes.h/fmi2Functions.h`
are not included in the FMU due to the following reasons:_

_`fmi2TypesPlatform.h` makes no sense in the `sources` directory,
because if sources are provided,
then the target simulator defines this header file and not the FMU. +
This header file is not included in the `binaries` directory,
because it is implicitly defined by the platform directory
(for example, win32 for 32-bit machine or linux64 for 64-bit machine).
Furthermore, the version that was used to construct the FMU can also
be inquired via function `fmi2GetTypesPlatform()`._

_`fmi2FunctionTypes.h/fmi2Functions.h` are not needed in the `sources` directory,
because they are implicitly defined by attribute `fmiVersion` in file `modelDescription.xml`.
Furthermore, in order that the C compiler can check for consistent function arguments,
the header file from the target simulator should be used when compiling the C sources.
It would therefore be counter-productive (unsafe)
if this header file was present. +
These header files are not included in the `binaries` directory,
since they are already utilized to build the target simulator executable.
The version number of the header file used to construct
the FMU can be deduced via attribute `fmiVersion` in file
`modelDescription.xml` or via function call `fmi2GetVersion()`.]_

_[New in FMI 2.0.2:]_
==== Extra Directory [[extra-directory]]

The ZIP archive may contain additional entries with the prefix `extra/` that can be used to store additional data and meta-data.
In order to avoid ambiguities and conflicts, the extra files should be provided in subdirectories using a reverse domain notation of a domain that is controlled by the entity defining the semantics and content of the additional entries _[(for example `extra/com.example/SimTool/meta.xml` or `extra/org.example.stdname/data.asd`)]_.
The use of subdirectories beginning with `org.modelica` and `org.fmi-standard` is explicitly reserved for use by MAP FMI-defined layered standards, i.e. other uses must not use subdirectory names beginning with these prefixes.
It is explicitly allowed for tools and users other than the original creator of an FMU to modify, add or delete entries in the `extra/` directory without affecting the validity of the FMU in all other aspects.
Specifically all validation or digital signature schemes used to protect the content of the FMU should take the variability of extra file content into account _[(for example by having separate checksums or signatures for FMU core content and extra content, or not having signatures at all for extra content)]_.


_[New in FMI 2.0.4:]_
==== Terminals and Icons

The optional directory `terminalsAndIcons` contains the definition of the Ports and Icons of the FMU as defined in the FMI 3.0 Specification, 2.4.9. Terminals and Icons.
