=== FMU Distribution [[fmu-distribution]]

An FMU consists of several files, that are stored in a ZIP file with a pre-defined structure.
The implementation of the simulation model represented by the FMU may be distributed in source code and/or in binary format.
The FMU must be distributed with at least one implementation, in other words, either sources or one of the binaries for a particular machine.
It is also possible to provide the sources and binaries for different target machines together in one ZIP file.
The FMU must implement all common API functions according to <<general-mechanisms>> and the functions for at least one of the FMI interface types.
Especially it is required that all functions that are part of the specified FMI interface type are present, even if they are only needed for optional capabilities that the FMU does not support.
The behavior of those functions is unspecified, so while calling environments can rely on the functions being present, they cannot rely on any particular behavior for functions only needed for capabilities the FMU does not support.
The extension of the ZIP file must be `.fmu` _[, for example, `HybridVehicle.fmu`]_.
The compression method used for the ZIP file must be `deflate` _[(most free tools, such as zlib, offer only the common compression method `deflate`)]_.


_[Note: especially section 4.4.17 of https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT[the ZIP format specification] states that backslashes "\" are forbidden as path separator, only forward slashes "/" are allowed._ +
_Non-ASCII directory names are not explicitly forbidden, but might pose a problem on different operating systems and are thus discouraged.]_

Every FMU is distributed with its own ZIP file.

==== Structure of the ZIP file [[structure-of-zip]]

.Structure of the ZIP file
[[figure-zip-structure]]
----
// Structure of ZIP file of an FMU
modelDescription.xml          // description of FMU (required file)
documentation                 // directory containing the documentation (optional)
   index.html                 // entry point of the documentation
   diagram.png                // descriptive diagram view of the model (optional)
   diagram.svg                // if existing the diagram.png is required (optional)
   <other documentation files>
   licenses                   // directory for licenses (optional)
      license.{txt|html}      // Entry point for license information
      <license files>         // For example BSD licenses
icons                         // FMU and terminal icons (optional)
   terminalsAndIcons.xml      // description of terminals and icons (optional)
   icon.png                   // image file of icon without terminals (optional)
   icon.svg                   // if existing the icon.png is required (optional)
   // all terminal and fmu icons referenced in the graphical representation
sources                       // directory containing the C sources (optional)
   buildDescription.xml
   // All needed C sources and header files to compile and link the FMU
   // except fmi3PlatformTypes.h, fmi3FunctionTypes.h, and fmi3Functions.h.
   // The files to be compiled (but not the files included from these files)
   // have to be reported in the buildDescription.xml.
binaries                      // directory containing the binaries (optional)
   x86_64-windows             // binaries for Windows on Intel 64-bit
      <modelIdentifier>.dll   // shared library of the FMI implementation
      <other DLLs>            // the DLL can include other DLLs
   x86_64-windows-msvc140mt   // static libraries for 64-bit Windows generated
      <modelIdentifier>.lib   // with Visual Studio 2015 with /MT flag
   i686-linux                 // binaries for Linux on Intel 32-bit
      <modelIdentifier>.so    // shared library of the FMI implementation
   aarch32-linux              // binaries for Linux on ARM 32-bit
      <modelIdentifier>.so    // shared library of the FMI implementation
   x86_64-darwin              // binaries for macOS
      <modelIdentifier>.dylib // shared library of the FMI implementation
   // If an FMU is run through one of its binaries all items in that binary
   // folder are recommended to be unpacked at the same location as the binary
   // < modelIdentifier >.* is unpacked. If not it is likely that, if the FMU
   // has dependencies on those items, it will not be able to find them.
resources                     // resources used by the FMU (optional)
   // data in FMU specific files which will be read during initialization;
   // also more folders can be added under resources (tool/model specific).
   // In order for the FMU to access these resource files, the resource directory
   // shall be available in unzipped form and the absolute path to this directory
   // should be reported via argument "resourceLocation" of fmi3InstantiateXXX.
extra                         // Additional (meta-)data of the FMU (optional)
   // additional (meta-)data that is supposed to travel with the FMU;
   // see below for structure and content definition.
----

===== Directory Documentation [[documentation-directory]]

<<figure-zip-structure>> defines the files expected in the `documentation` directory.

====== Directory Licenses [[license-information]]
This optional subdirectory can be used to bundle all license texts for the code, binaries or other material (documentation, content of resources folder) contained tin the FMU.
If it is present, it must contain either a https://spdx.dev[license.spdx], `license.txt` or `license.html` file as entry point.

_[It is strongly recommended to include all license and copyright related information in the licenses folder of an FMU (especially but not only for contained open source software) - the `license.{txt|html}` file can serve as an entry point for describing the contained licenses._
_This will help the users to comply with license conditions when passing source or binary code contained in an FMU to other persons or organizations.]_

===== Directory Icons [[Icons-directory]]

See <<fmiTerminalsAndIcons>> for a definition of the directory `icons`.

===== Directory Sources [[sources-directory]]

[[BuildConfiguration,`<BuildConfiguration>`]]
A source code FMU contains the sources of the model in the `sources` directory together with a `buildDescription.xml` that contains at least one <<BuildConfiguration>> element for the supported platforms.
Each <<BuildConfiguration>> provides the necessary information to compile and link the sources of the model into a dynamic library or as part of an executable.
An FMU importing tool may not regard more than one <<BuildConfiguration>> when building the FMU for a specific <<platform>>.
The importer chooses the matching <<BuildConfiguration>> based on the <<platform>> and <<modelIdentifier>> attributes.

.BuildConfiguration attribute details.
[[table-BuildConfiguration-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|[[modelIdentifier,`modelIdentifier`]]`modelIdentifier`
|The attribute <<modelIdentifier>> of the `<ModelExchange>`, `<CoSimulation>` or `<ScheduledExecution>` elements this build configuration is associated with.

|[[platform,`platform`]]`platform`
|Platform tuple of the platform the <<BuildConfiguration>> is intended for (e.g. `x86_64-linux`).
All <<platform>> attributes defined in the <<BuildConfiguration>> elements for the same `<modelIdentifier>` must be unique.
For each <<platform>> there can only be one matching <<BuildConfiguration>>.
This attribute is optional.
Thus there must not be more than one <<BuildConfiguration>> without a <<platform>> attribute.
If a <<BuildConfiguration>> without a <<platform>> attribute is provided this is the fallback <<BuildConfiguration>> an importer can use if it cannot find any other <<BuildConfiguration>> with a matching <<platform>> attribute.

|`description`
|Description of the build configuration
|====

====== SourceFileSet

The `<SourceFileSet>` element groups source files that can be compiled with the same compiler and compiler options.
Every build configuration must contain at least one `<SourceFileSet>`.
An importer of the FMU has to regard every `<SourceFileSet>` of the matching <<BuildConfiguration>>.

.SourceFileSet attribute details.
[[table-SourceFileSet-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Name of the `<SourceFileSet>`

|`language`
|Language of the source files (e.g. `C99`, `C++11`)

|`compiler`
|The compiler to compile the sources (e.g. `VisualC`, `gcc`, `clang++`)

|`compilerOptions`
|The compiler flags that have to be used when compiling the sources (e.g. `-fno-rtti`, `/Od`)
|====

====== SourceFile

.SourceFile attribute details.
[[table-SourceFile-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Path of the source file relative to the `sources` directory
|====

====== PreprocessorDefinition

The `<PreprocessorDefinition>` element defines a preprocessor definition that needs to be passed to the compiler when compiling the source files in the `<SourceFileSet>`.

.ProcessorDefintition attribute details.
[[table-ProcessorDefinition-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Name of the preprocessor definition

|`value`
|Value of the preprocessor definition

|`optional`
|Determines wether the definition is optional (default is `false`)

|`description`
|Description of the preprocessor definition
|====

====== PreprocessorDefinition/Option

The `<Option>` element defines a possible value for the `<PreprocessorDefinition>`.
If a `<PreprocessorDefinition>` contains `<Option>` elements, its default value must be contained in the options.

.PreprocessorDefintition attribute details.
[[table-PreprocessorDefinition-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`value`
|Value of the preprocessor definition option

|`description`
|Description of the preprocessor definition option
|====

====== IncludeDirectory

The `<IncludeDirectory>` element defines the include directories that need to be passed to the compiler when compiling the source files in the `<SourceFileSet>`.

.IncludeDirectory attribute details.
[[table-IncludeDirectory-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Path of the include directory relative to the `sources` directory
|====

_[Note that the header files `fmi3PlatformTypes.h` and `fmi3FunctionTypes.h/fmi3Functions.h` are not included in the FMU because:_

_pass:[]`fmi3PlatformTypes.h` makes no sense in the `sources` directory, because if sources are provided, then the importer defines this header file and not the FMU._ +
_This header file is not included in the `binaries` directory, because it is implicitly defined by the platform directory (for example, `i686-windows` for a 32-bit machine or `x86_64-linux` for a 64-bit machine)._

_pass:[]`fmi3FunctionTypes.h` / `fmi3Functions.h` are not needed in the `sources` directory, because they are implicitly defined by attribute `fmiVersion` in file <<modelDescription.xml>>._
_Furthermore, in order that the C compiler can check for consistent function arguments, the header file from the importer should be used when compiling the C sources._
_It would therefore be counter-productive (unsafe) if this header file was present._ +
_These header files are not included in the `binaries` directory, since they are already utilized to build the executable of the simulation environment._
_The version number of the header file used to construct the FMU can be deduced via attribute `fmiVersion` in file <<modelDescription.xml>> or via function call <<fmi3GetVersion>>.]_

====== Library

The `<Library>` element defines a static library required to link the model binary.
An importer of the FMU has to link every library of the matching <<BuildConfiguration>>.

.Library attribute details.
[[table-Library-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Name of the library

|`version`
|Version specifier of the library as defined in https://www.python.org/dev/peps/pep-0440/#version-specifiers[PEP 440].
The characters `>` (greater-than) and `<` (less-than) must be escaped as `&gt;` and `&lt;`.
 _[For example `2.5`, `>=2.0,<3.0` or `>=1.0,!=1.2`]_.

|`external`
|Boolean attribute that determines wether the library is contained in the `binaries/<platform_tuple>` directory (`false`) or if it has to be provided by the environment (`true`).
The default is `false`.

|`description`
|Description of the library definition option
|====

====== Examples

.A minimal build configuration
[source, xml]
----
include::examples/build_description_simple.xml[]
----

.Multiple complex build configurations
[source, xml]
----
include::examples/build_description_complex.xml[]
----

===== Directory Binaries [[binaries-directory]]

====== Platform Tuple Definition [[platform-tupe-definition]]

The names of the binary directories are standardized by the "platform tuple".
Further names can be introduced by vendors.
Dynamic link libraries must include all referenced resources that are not available on a standard target machine _[for example, DLLs on Windows that are built with Visual Studio should be compiled with the `/MT` option to include the required symbols from the Visual C runtime in the DLL, and not use the option `/MD` where this is not the case]_.
When compiling a shared object on Linux, `RPATH="$ORIGIN"` has to be set when generating the shared object in order that shared objects used from it, can be dynamically loaded.

The binaries must be placed in the respective <platformTuple> directory with the general format `<arch>-<sys>{-<abi>{<abi_ver>}{<abi_sub>}}`.

Architecture `<arch>`::
+
[width="50%",cols="1,5",options="header"]
|====
|Name
|Description

|aarch32
|ARM 32-bit Architecture

|aarch64
|ARM 64-bit Architecture

|i386
|Intel 3rd generation x86 32-bit

|i586
|Intel 5th generation x86 32-bit w/o SSE

|i686
|Intel 6th generation x86 32-bit with SSE2

|x86_64
|Intel/AMD x86 64-bit
|====

Operating system `<sys>`::
+
[width="50%",cols="1,5",options="header"]
|====
|Name
|Description

|darwin
|Darwin (macOS, iOS, watchOS, tvOS, audioOS)

|linux
|Linux

|windows
|Microsoft Windows
|====

Application Binary Interface (ABI) `<abi>`::
+
[width="50%",cols="1,5",options="header"]
|====
|Name
|Description

|elf
|ELF file format

|gnu
|GNU

|android
|Android

|macho
|Mach object file format

|msvc
|Microsoft Visual C
|====

ABI version `<abi_ver>`::
+
[width="50%",cols="1,5",options="header"]
|====
|Name
|Description

|80
|Visual Studio 2005 (MSVC++ 8.0)

|90
|Visual Studio 2008 (MSVC++ 9.0)

|100
|Visual Studio 2010 (MSVC++ 10.0)

|110
|Visual Studio 2012 (MSVC++ 11.0)

|120
|Visual Studio 2013 (MSVC++ 12.0)

|140
|Visual Studio 2015 (MSVC++ 14.0)

|141
|Visual Studio 2017 (MSVC++ 15.x)

|142
|Visual Studio 2019 (MSVC++ 16.x)
|====

Sub-ABI `<abi_sub>`::
+
[width="50%",cols="1,5",options="header"]
|====
|Name
|Description

|md
|Visual Studio with /MD

|mt
|Visual Studio with /MT

|mdd
|Visual Studio with /MDd

|mtd
|Visual Studio with /MTd
|====

_[Typical scenarios are to provide binaries only for one machine type (for example, on the machine where the importer is running and for which licenses of run-time libraries are available) or to provide only sources (for example, for translation and download for a particular micro-processor).]_

====== External Libraries [[external-libraries]]

If run-time libraries are needed by the FMU that have to be present on the target machine and cannot be shipped within the FMU (e.g., due to licensing issues), then automatic processing is likely impossible.
In such cases special handling is needed, for example, by providing the run-time libraries at appropriate places by the receiver.
The requirements and the expected processing should be documented in the `documentation` directory in this case. +

===== Directory Resources [[resources-directory]]

In the optional directory `resources`, additional data can be provided in FMU specific formats, typically for tables and maps used in the FMU.
This data must be read into the model at the latest during initialization (that is, before <<fmi3ExitInitializationMode>> is called).
The actual file names in the ZIP file to access the data files can either be hard-coded in the generated FMU functions, or the file names can be provided as string arguments via the `fmi3SetString` function.
_[Note that an URI pointing to the resources directory is provided by the initialization functions._
_If the environment is not able to do so, a NULL pointer will be provided instead, and the FMU can react with an error, if it requires access to the content of the resources folder.]_
In the case of an FMU implementation of `needsExecutionTool = true` type, the `resources` directory can contain the model file in the tool specific file format.

===== Directory Extra [[extra-directory]]

The ZIP archive may contain additional entries with the prefix `extra/` that can be used to store additional data and meta-data.
In order to avoid ambiguities and conflicts, the extra files should be provided in subdirectories using a reverse domain notation of a domain that is controlled by the entity defining the semantics and content of the additional entries _[(for example `extra/com.example/SimTool/meta.xml` or `extra/org.example.stdname/data.asd`)]_.
The use of subdirectories beginning with `org.modelica` and `org.fmi-standard` is explicitly reserved for use by MAP FMI-defined layered standards, i.e. other uses must not use subdirectory names beginning with these prefixes.
It is explicitly allowed for tools and users other than the original creator of an FMU to modify, add or delete entries in the `extra/` directory without affecting the validity of the FMU in all other aspects.
Specifically all validation or digital signature schemes used to protect the content of the FMU should take the variability of extra file content into account _[(for example by having separate checksums or signatures for FMU core content and extra content, or not having signatures at all for extra content)]_.

==== Multiple Interface Types

Exporters may support multiple FMI types in one FMU, so it can be used in differently capable simulation algorithms and for different use cases.
To indicate support for a specific interface type, the `<fmiModelDescription>` must have the respective element present, irrespective if a specific interface is contained in binary or source format.

_[The described multi-mode support is often based on wrapping functionality into the <<fmi3DoStep>> function by emulating missing features of the Model Exchange and Scheduled Execution interface types.]_

----
[Example of different libraries:
   binaries
     x86_64-windows
        MyModel_ModelExchange.dll      // modelIdentifier of <ModelExchange> =
                                       //    "MyModel_ModelExchange"
        MyModel_CoSimulation.dll       // modelIdentifier of <CoSimulation> =
                                       //    "MyModel_CoSimulation"
]
----

Support of multiple interface types in one FMU is possible only, if the interface variables are identical.

==== Dependency on Installed Tool [[dependency-on-exteranl-tool]]

FMI provides the means for two kinds of implementation: `needsExecutionTool = true` and `needsExecutionTool = false`.
In the first case, a tool specific wrapper DLL/SharedObject/Source is part of the FMU.
In the second case, all components necessary for execution of the FMU are included with the FMU.

==== Import Examples

The following code examples demonstrate how to access the FMI functions of FMUs that are implemented as a shared library or static library / source code.

===== Accessing FMI Functions in Shared Libraries

[source, C]
----
include::Reference-FMUs/examples/import_shared_library.c[]
----

===== Accessing FMI Functions in Static Libraries and Source Code

[source, C]
----
include::Reference-FMUs/examples/import_static_library.c[]
----
