=== FMU Distribution [[fmu-distribution]]

An FMU consists of several files, that are stored in a ZIP file with a pre-defined structure.
The implementation of the FMI C-API may be distributed in source code and/or in binary format.
The FMU must be distributed with at least one implementation, in other words, either sources or one of the binaries for a particular machine.
It is also possible to provide the sources and binaries for different target machines together in one ZIP file.
The FMU must implement all common API functions according to <<general-mechanisms>> and the functions for at least one of the interface types.
Especially it is required that all functions that are part of the specified interface type are present, even if they are only needed for optional capabilities that the FMU does not support.
The behavior of those functions is unspecified, so while calling environments can rely on the functions being present, they cannot rely on any particular behavior for functions only needed for capabilities the FMU does not support.
Additional functions may be present in the FMU, as for example required by the OS ABI, for layered standards, or future FMI versions.
All symbols starting with the prefix `fmi3` are reserved for use in future minor releases of FMI 3.0.
The extension of the ZIP file must be `.fmu` _[, for example, `HybridVehicle.fmu`]_.
The compression method for all files stored in the ZIP archive must be either 8 (`deflate`), or 0 (`store`).
Only files stored using compression method 8 (`deflate`) may be stored with general purpose bit 3 set.
The field `version needed to extract` of the archive must not be higher than 2.0, and encryption must not be employed.
The archive must not be a split or spanned ZIP archive.
Links must not be used inside the ZIP archive.
 _[These restrictions ensure broad compatibility of the archive with common ZIP processing tools and libraries.)]_

_[Note: especially section 4.4.17 of https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT[the ZIP format specification] states that backslashes "\" are forbidden as path separator, only forward slashes "/" are allowed._ +
_Non-ASCII directory names are not explicitly forbidden, but might pose a problem on different operating systems and are thus discouraged.]_

Every FMU is distributed with its own ZIP file.

==== Structure of the ZIP file [[structure-of-zip]]

.Structure of the ZIP file of an FMU
[[figure-zip-structure]]
----
modelDescription.xml                // description of FMU (required file)
documentation                       // directory containing the documentation (optional)
   index.html                       // entry point of the documentation
   diagram.png                      // descriptive diagram view of the model (optional)
   diagram.svg                      // if provided, diagram.png is also required (optional)
   externalDependencies.{txt|html}  // documentation of external resources required to load
                                    // or simulate the FMU
   <other documentation files>
   licenses                         // directory for licenses (optional)
      license.{txt|html}            // entry point for license information
      <license files>               // for example BSD licenses (optional)
   staticLinking.{txt|html}         // entry point for static link information (optional)
terminalsAndIcons                   // FMU and terminal icons (optional)
   terminalsAndIcons.xml            // description of terminals and icons (optional)
   icon.png                         // image file of icon without terminals (optional)
   icon.svg                         // if existing the icon.png is required (optional)
                                    // all terminal and fmu icons referenced in the
                                    // graphical representation
sources                             // directory containing the C sources (optional)
   buildDescription.xml
binaries                            // directory containing the binaries (optional)
   x86_64-windows                   // binaries for Windows on Intel 64-bit
      <modelIdentifier>.dll         // shared library of the FMI implementation
      <other DLLs>                  // the DLL can include other DLLs
   x86-linux                        // binaries for Linux on Intel 32-bit
      <modelIdentifier>.so          // shared library of the FMI implementation
   aarch32-linux                    // binaries for Linux on ARM 32-bit
      <modelIdentifier>.so          // shared library of the FMI implementation
   x86_64-darwin                    // binaries for macOS
      <modelIdentifier>.dylib       // shared library of the FMI implementation
resources                           // resources used by the FMU (optional)
extra                               // Additional (meta-)data of the FMU (optional)
----

===== Directory `documentation` [[documentation-directory]]

Figure <<figure-zip-structure>> defines the files expected in the `documentation` directory.
If the FMU depends on external resources _[e.g. shared libraries, files, or servers]_ to be loaded or simulated `documentation/externalDependencies.{txt|html}` must be present to document these dependencies and how to provide them.

====== Directory `licenses` [[license-information]]
This optional subdirectory can be used to bundle all license texts for the code, binaries or other material (documentation, content of resources folder) contained in the FMU.
If it is present, it must contain either a https://spdx.dev[license.spdx], `license.txt` or `license.html` file as entry point.

_[It is strongly recommended to include all license and copyright related information in the licenses folder of an FMU (especially but not only for contained open source software) - the `license.{txt|html}` file can serve as an entry point for describing the contained licenses._
_This will help the users to comply with license conditions when passing source or binary code contained in an FMU to other persons or organizations.]_

===== Directory `terminalsAndIcons` [[terminalsAndIcons-directory]]

See <<fmiTerminalsAndIcons>> for a definition of the directory `terminalsAndIcons`.

===== Directory `sources` [[sources-directory]]

A source code FMU contains the sources of the model in the `sources` directory together with a `buildDescription.xml` that contains at least one <<BuildConfiguration>> element for the supported platforms.
The header files `fmi3PlatformTypes.h`, `fmi3FunctionTypes.h` and `fmi3Functions.h` are not included in the FMU, but supplied by the importer to potentially reflect their specific platform and compiler tool set.

===== Directory `binaries` [[binaries-directory]]

A binary FMU must contain the binary files for all supported platforms in this folder.
To use the binaries of a specific platform, all items in that platform-specific binary folder must be unpacked at the same location as the binary `<modelIdentifier>.{dll|dylib|so}`.

====== Platform Tuple Definition [[platform-tupe-definition]]

The names of the binary directories are standardized by the "platform tuple".
Further names can be introduced by vendors.
FMUs should contain all resources that are required to load and execute a shared library, link against a static library, or compile from source.
Shared libraries should be statically linked against their dependencies _[e.g. the Visual Studio C Runtime on Windows]_.
`RPATH="$ORIGIN"` should be set when building ELF binaries to allow dynamic loading of dependencies on the target machine.
All external dependencies must be documented (see <<documentation-directory>>).

The binaries must be placed in the respective `<platformTuple>` directory with the general format `<arch>-<sys>`.

Architecture `<arch>`::
+
[width="50%",cols="1,5",options="header"]
|====
|Name
|Description

|aarch32
|ARM 32-bit Architecture

|aarch64
|ARM 64-bit Architecture

|x86
|Intel/AMD x86 32-bit

|x86_64
|Intel/AMD x86 64-bit
|====

Operating system `<sys>`::
+
[width="50%",cols="1,5",options="header"]
|====
|Name
|Description

|darwin
|Darwin (macOS, iOS, watchOS, tvOS, audioOS)

|linux
|Linux

|windows
|Microsoft Windows
|====

When shipping the implementation as a static library an optional ABI (Application Binary Interface) directory `<arch>-<sys>{-<abi>}` may be added to separate binaries for different toolchains on the same platform and a description must be provided in `documentation/staticLinking.{txt|html}` that contains all necessary information to link against the provided library _[e.g. supported compilers]_.
The ABI directory must only contain lowercase characters `a...z`, digits `0...9`, and underscores `_` and start with a lowercase character `a...z` _[e.g. `x86_64-windows-msvc140mt` for a static library for 64-bit Windows generated with Visual Studio 2015 with `/MT` flag]_.

====== Platform Tuple Examples [[platform-tuple-examples]]

The following table lists the most common platform tuples for shared libraries and the corresponding FMI 2.0 platform.

[width="80%",cols="3,3,5",options="header"]
|====
|Name
|FMI 2.0
|Description

|x86_64-darwin
|darwin64
|macOS on 64-bit x86

|aarch64-darwin
|
|macOS on Apple Silicon

|x86-linux
|linux32
|Linux on 32-bit x86

|x86_64-linux
|linux64
|Linux on 64-bit x86

|aarch64-linux
|
|Linux on ARM64

|x86-windows
|win32
|Windows on 32-bit x86

|x86_64-windows
|win64
|Windows on 64-bit x86

|aarch64-windows
|
|Windows on ARM64
|====

====== External Libraries [[external-libraries]]

If runtime libraries are needed by the FMU that have to be present on the target machine and cannot be shipped within the FMU (e.g., due to licensing issues), then automatic processing is likely impossible.
In such cases special handling is needed, for example, by providing the runtime libraries at appropriate places by the receiver.
The requirements and the expected processing must be documented in the `documentation` directory in the file `externalDependencies.{txt|html}`. +

===== Directory `resources` [[resources-directory]]

In the optional directory `resources`, additional data can be provided in FMU specific formats, typically for tables and maps used in the FMU.
More folders can be added under `resources` (tool/model specific).
For the FMU to access these resource files, the resources directory shall be available in extracted form and the absolute path to this directory is provided via argument <<resourcePath>> of <<fmi3Instantiate>>.
The resources directory must be available for the lifetime of the FMU instance.
The FMU instance must not write to or delete the directory or parts of it.

The `resource` data must be read into the model at the latest during initialization (that is, before <<fmi3ExitInitializationMode>> is called).
The actual file names in the ZIP file to access the data files can either be hard-coded in the generated FMU functions, or the file names can be provided as string arguments via the `fmi3SetString` function.
_[Note that an URI pointing to the resources directory is provided by the initialization functions._
_If the environment is not able to do so, a NULL pointer will be provided instead, and the FMU can react with an error, if it requires access to the content of the resources folder.]_
In the case of an FMU implementation of `needsExecutionTool = true` type, the `resources` directory can contain the model file in the tool specific file format.

===== Directory `extra` [[extra-directory]]

The ZIP archive may contain additional entries with the prefix `extra/` that can be used to store additional data and meta-data.
In order to avoid ambiguities and conflicts, the extra files should be provided in subdirectories using a reverse domain notation of a domain that is controlled by the entity defining the semantics and content of the additional entries _[(for example `extra/com.example/SimTool/meta.xml` or `extra/org.example.stdname/data.asd`)]_.
The use of subdirectories beginning with `org.modelica` and `org.fmi-standard` is explicitly reserved for use by MAP FMI-defined layered standards, i.e. other uses must not use subdirectory names beginning with these prefixes.
It is explicitly allowed for tools and users other than the original creator of an FMU to modify, add or delete entries in the `extra/` directory without affecting the validity of the FMU in all other aspects.
Specifically all validation or digital signature schemes used to protect the content of the FMU should take the variability of extra file content into account _[(for example by having separate checksums or signatures for FMU core content and extra content, or not having signatures at all for extra content)]_.

==== Multiple Interface Types [[multipleInterfaceTypes]]

Exporters may support multiple FMI types in one FMU, so it can be used in differently capable simulation algorithms and for different use cases.
To indicate support for a specific interface type, the `<fmiModelDescription>` must have the respective element present, irrespective if a specific interface type is contained in binary or source format.

_[The described multi-mode support is often based on wrapping functionality into the <<fmi3DoStep>> function by emulating missing features of the Model Exchange and Scheduled Execution interface types.]_

----
[Example of different libraries:
   binaries
     x86_64-windows
        MyModel_ModelExchange.dll      // modelIdentifier of <ModelExchange> =
                                       //    "MyModel_ModelExchange"
        MyModel_CoSimulation.dll       // modelIdentifier of <CoSimulation> =
                                       //    "MyModel_CoSimulation"
]
----

Support of multiple interface types in one FMU is possible only, if the interface variables are identical.

==== Dependency on Installed Tool [[dependency-on-exteranl-tool]]

FMI provides the means for two kinds of implementation: `needsExecutionTool = true` and `needsExecutionTool = false`.
In the first case, a tool specific wrapper DLL/SharedObject/Source is part of the FMU.
In the second case, all components necessary for execution of the FMU are included with the FMU.

==== Import Examples

The following code examples demonstrate how to access the FMI functions of FMUs that are implemented as a shared library or static library / source code.

===== Accessing FMI Functions in Shared Libraries

[source, C]
----
include::Reference-FMUs/examples/import_shared_library.c[]
----

===== Accessing FMI Functions in Static Libraries and Source Code

[source, C]
----
include::Reference-FMUs/examples/import_static_library.c[]
----
