=== Versioning and Layered Standards

The FMI standard uses semantic version numbers, as defined in <<PW13>>, where the standard version consists of a triple of version numbers, consisting of major version, minor version, and patch version numbers _[e.g. 1.2.3 for major version 1, minor version 2 and patch version 3]_.

* Major versions will introduce changes that are neither backward nor forward-compatible, including changes to the XML schemas to include new non-ignorable content.
* Minor versions will only contain clarifications and include new layered standards, which may add new ignorable XML content, as defined below, into the core standard document, indicating that the standard needs to be supported by all conforming implementations.
* Patch versions will only change explanatory text of the standard, make formerly defined content clearer, without any other changes to the XML schemas or other content definitions. For this reason, the version number attribute of all FMI files will only contain major and minor version numbers and not the patch version number: It should never be necessary for an importing tool to know the patch version number of the standard that the generating tool implemented.

In order to enable the backward-compatible extension of the FMI standard in minor releases and between minor releases, MAP FMI intends the use of the layered standard mechanism to introduce new features in a fully backward-compatible and optional way. +
A layered standard defines extensions to the base FMI standard by specifying either standardized annotations, standardized extra files in SSP archives, and/or support for additional MIME types/file formats, as defined in section XXX.  +
A layered standard can include a single or combined set of extension mechanisms from this set. +
The layered standard is thus considered to be layered on top of the definitions and extensions mechanisms provided by this base standard.

Layered standards can fall into three categories:

* Layered standards defined by third parties, without any representations by the FMI project for their suitability or content, or even knowledge by the FMI project about their existence.
* Layered standards defined by third parties that are endorsed by the FMI project and listed on the FMI project website.
* Layered standards can be defined/adopted and published by the FMI project itself, making them FMI project layered standards.

Layered standards that have achieved enough adoption or importance to be included into the base standard set could be incorporated into a new minor or major release version of the base standard as an optional or mandatory appendix, making support for this layered standard optional or required for conformance with the newly published minor release version of the base standard.
