=== Versioning and Layered Standards [[VersioningLayered]]

The FMI standard uses semantic version numbers, as defined in <<PW13>>, where the standard version consists of a triple of version numbers, consisting of major version, minor version, and patch version numbers _[e.g. 1.2.3 for major version 1, minor version 2 and patch version 3]_.

* Major versions will introduce changes that are neither backward nor forward compatible, including changes to the XML schemas to include new non-ignorable content.
* Minor versions will only contain clarifications and include new layered standards, which may add new ignorable XML content, as defined below, into the core standard document, indicating that the standard needs to be supported by all conforming implementations.
* Patch versions will only change explanatory text of the standard, make formerly defined content clearer, without any other changes to the XML schemas or other content definitions. For this reason, the version number attribute of all FMI files will only contain major and minor version numbers and not the patch version number: It should never be necessary for an importer to know the patch version number of the standard that the generating tool implemented.

In order to enable the backward-compatible extension of the FMI standard in minor releases and between minor releases, the FMI project intends the use of the layered standard mechanism to introduce new features in a fully backward-compatible and optional way.

A layered standard defines extensions to the base FMI standard by specifying, for example:

* <<Annotations,standardized annotations>>,
* <<extra-directory,standardized extra files in the FMU>>,
* support for additional <<mimeType,MIME types>>,
* new values for <<matchingRule>> or <<terminalKind>> for <<Terminals,Terminals>> and/or
* adding C-API functions/variables.

Any FMU following a layered standard on top of FMI 3.0 must still be a compliant FMI 3.0 FMU.

Layered standards can fall into one of three categories:

* defined by third parties, completely independent from the <<MAP>> FMI,
* defined by third parties that are endorsed by the FMI project and listed on the FMI project website, and
* defined/adopted and published by the <<MAP>> FMI project itself, making them FMI project layered standards.

Layered standards that have achieved enough adoption or importance to be included into the base standard could be incorporated into a new minor or major release version of the base standard, making support for this layered standard optional or required for conformance with the newly published release of the FMI standard.
