=== Definition of Source Code

A source code FMU contains the sources of the model in the `sources` directory together with a `buildDescription.xml` that contains at least one `<BuildConfiguration>` element for the supported platforms.
Each `<BuildConfiguration>` provides the necessary information to compile and link the sources of the model into a dynamic library or as part of an executable.
An FMU importing tool may not regard more than one `<BuildConfiguration>` when building the FMU for a specific `<platform>`.
The importer chooses the matching `<BuildConfiguration>` based on the `<platform>` and `<modelIdentifier>` attributes.

.BuildConfiguration attribute details.
[[table-BuildConfiguration-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`modelIdentifier`
|The attribute `modelIdentifier` of the `<ModelExchange>`, `<CoSimulation>` or `<ScheduledExecution>` elements this build configuration is associated with.

|`platform`
|Platform tuple of the platform the `<BuildConfiguration>` is intended for (e.g. `x86_64-linux`).
All `platform` attributes defined in the `<BuildConfiguration>` elements for the same `<modelIdentifier>` must be unique.
For each `platform` there can only be one matching `<BuildConfiguration>`.
This attribute is optional.
Thus there must not be more than one `<BuildConfiguration>` without a `platform` attribute.
If a `<BuildConfiguration>` without a `platform` attribute is provided this is the fallback `<BuildConfiguration>` an importer can use if it cannot find any other `<BuildConfiguration>` with a matching `platform` attribute.

|`description`
|Description of the build configuration
|====

==== SourceFileSet

The `<SourceFileSet>` element groups source files that can be compiled with the same compiler and compiler options.
Every build configuration must contain at least one `<SourceFileSet>`.
An importer of the FMU has to regard every `<SourceFileSet>` of the matching `<BuildConfiguration>`.

.SourceFileSet attribute details.
[[table-SourceFileSet-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Name of the `<SourceFileSet>`

|`language`
|Language of the source files (e.g. `C99`, `C++11`)

|`compiler`
|The compiler to compile the sources (e.g. `VisualC`, `gcc`, `clang++`)

|`compilerOptions`
|The compiler flags that have to be used when compiling the sources (e.g. `-fno-rtti`, `/Od`)
|====

===== SourceFile

.SourceFile attribute details.
[[table-SourceFile-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Path of the source file relative to the `sources` directory
|====

===== PreprocessorDefinition

The `<PreprocessorDefinition>` element defines a preprocessor definition that needs to be passed to the compiler when compiling the source files in the `<SourceFileSet>`.

.ProcessorDefintition attribute details.
[[table-ProcessorDefinition-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Name of the preprocessor definition

|`value`
|Value of the preprocessor definition

|`optional`
|Determines wether the definition is optional (default is `false`)

|`description`
|Description of the preprocessor definition
|====

===== PreprocessorDefinition/Option

The `<Option>` element defines a possible value for the `<PreprocessorDefinition>`.
If a `<PreprocessorDefinition>` contains `<Option>` elements, its default value must be contained in the options.

.PreprocessorDefintition attribute details.
[[table-PreprocessorDefinition-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`value`
|Value of the preprocessor definition option

|`description`
|Description of the preprocessor definition option
|====

===== IncludeDirectory

The `<IncludeDirectory>` element defines the include directories that need to be passed to the compiler when compiling the source files in the `<SourceFileSet>`.

.IncludeDirectory attribute details.
[[table-IncludeDirectory-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Path of the include directory relative to the `sources` directory
|====

==== Library

The `<Library>` element defines a static library required to link the model binary.
An importer of the FMU has to link every library of the matching `<BuildConfiguration>`.

.Library attribute details.
[[table-Library-details]]
[cols="1,3a",options="header"]
|====
|Attribute
|Description

|`name`
|Name of the library

|`version`
|Version specifier of the library as defined in https://www.python.org/dev/peps/pep-0440/#version-specifiers[PEP 440].
The characters `>` (greater-than) and `<` (less-than) must be escaped as `&gt;` and `&lt;`.
 _[For example `2.5`, `>=2.0,<3.0` or `>=1.0,!=1.2`]_.

|`external`
|Boolean attribute that determines wether the library is contained in the `binaries/<platform_tuple>` directory (`false`) or if it has to be provided by the environment (`true`).
The default is `false`.

|`description`
|Description of the library definition option
|====

==== Examples

.A minimal build configuration
[source, xml]
----
include::examples/build_description_simple.xml[]
----

.Multiple complex build configurations
[source, xml]
----
include::examples/build_description_complex.xml[]
----
