== Common Concepts [[fmi-common-concepts]]

The concepts defined in this chapter are common for Model Exchange and Co-Simulation interface types.
In both cases, FMI defines an input/output block of a dynamic model or a subsystem where the distribution of the block/subsystem, the platform dependent header file, several access functions, as well as the schema files, are identical.
The definitions that are specific to the particular cases are defined in <<fmi-for-model-exchange>>, <<fmi-for-co-simulation>>, and <<fmi-for-scheduled-execution>>.
We now introduce some basic concepts.

The FMI defines the following interface types: FMI for Model Exchange, Co-Simulation, and Scheduled Execution.
The term _FMU_ (Functional Mock-up Unit) denotes an implementation (or any mix) of interface type FMI for Model Exchange, Co-Simulation or Scheduled Execution interface.
The same FMU can implement multiple interface types.

The interfaces implemented by each FMU are invoked by a (co-)simulation algorithm, running in a simulation environment.
Communication between FMUs is thus achieved by the (co-)simulation algorithm.

In the following, we assume that the reader is familiar with the basics of the C programming language and the basics of numerical simulation.
Please refer to the glossary in <<glossary>> for the most commonly used terms.
