== Common Concepts [[fmi-common-concepts]]

The concepts defined in this chapter are common for Model Exchange and Co-Simulation interface types.
In both cases, FMI defines an input/output block of a dynamic model or a subsystem where the distribution of the block/subsystem, the platform dependent header file, several access functions, as well as the schema files, are identical.
The definitions that are specific to the particular cases are defined in <<fmi-for-model-exchange>>, <<fmi-for-basic-co-simulation>>, <<fmi-for-hybrid-co-simulation>>, and <<fmi-for-scheduled-co-simulation>>.
We now introduce some basic concepts.

The FMI defines the following interface types: FMI for Model Exchange, Basic Co-simulation, Hybrid Co-Simulation, and Scheduled Co-Simulation.
The term _FMU_ (Functional Mock-up Unit) denotes an implementation of interface type FMI for Model Exchange, or an implementation of all or any subset of the Co-Simulation interface types (Basic Co-Simulation, Hybrid Co-Simulation or Scheduled Co-Simulation).
The same FMU can implement multiple interface types.

The interfaces implemented by each FMU are invoked by a target simulator, running in a simulation environment. Communication between FMUs is thus achieved by the target simulator.
We often denote the target simulator as master algorithm, and the FMUs as slaves, in allusion to the master/slave communication approach.

In the following, we assume that the reader is familiar with the basics of the C programming language and the basics of numerical simulation.
Please refer to the glossary in <<glossary>> for the most commonly used terms.