=== Concepts [[concepts-model-exchange]]

==== Event Handling

Integration algorithms for differential equations assume continuous behavior of variables.
In hybrid ODEs, there are points during the simulation, when this assumption is violated.
A hybrid ODE solver must therefore:

* locate exactly when such a discontinuity (event) happens and enter <<EventMode>>.
This is trivial for <<time-event,time events>>.
For <<state-event,state events>> event indicators are used.
* handle such events in <<EventMode>>.
* restart the integration algorithm when leaving <<EventMode>>.

[[state-event,state event]]An <<fmi3GetEventIndicators,event indicator>> signals a <<state-event>> with the change from latexmath:[\mathbf{z}_j > 0] to latexmath:[\mathbf{z}_j \leq 0] or vice versa. +
_[This definition is slightly different from the usual standard definition of state events:_ latexmath:[\mathbf{z}(\mathbf{t}) \cdot \mathbf{z}(\mathbf{t}_\mathit{i-1}) \leq 0] _which has the severe drawback that the value of the event indicator at the previous event instant,_ latexmath:[\mathbf{z}(\mathbf{t}_\mathit{i-1}) \neq 0], _must be non-zero and this condition cannot be guaranteed._
_The often used term "zero crossing function" for latexmath:[\mathbf{z}] is misleading (and is therefore not used in this document), since a state event is defined by a change of a domain and not by a zero crossing of a variable.]_

The FMU must guarantee that after leaving <<EventMode>> latexmath:[\mathbf{z}_j \neq 0], for example, by shifting latexmath:[\mathbf{z}_j] with a small value. +
_[All event indicators should be continuous between events._
_Furthermore, latexmath:[\mathbf{z}_j] should be scaled in the FMU with its nominal value (so all elements of the returned vector `eventIndicators` should be in the order of 1).]_

.An event occurs when the event indicator changes its domain from latexmath:[\mathbf{z}>0] to latexmath:[\mathbf{z} \leq 0] or vice versa.
[#figure-events]
image::images/Event.svg[width=60%, align="center"]

[[frozen-relations]]
During event localization the FMU might be evaluated after the switch of an event indicator.
Even when an event indicator switches, its corresponding relation must stay "frozen" to assure the continuity assumption of the integration algorithm.
This allows an integration algorithm to properly finish the current integration step.

In <<table-variable-types>>, vector latexmath:[\mathbf{r}] is used to label all relations.
In <<ContinuousTimeMode>> all these relations are "frozen".
This is indicated in <<updateRelations, the mathematical description>> of <<EventMode>> by computing_ latexmath:[{}^\bullet\mathbf{r}] when leaving <<EventMode>> and using latexmath:[{}^\bullet\mathbf{r}] in the right-hand side of latexmath:[{\mathbf{f}_{\mathit{cont}}}] and latexmath:[{\mathbf{f}_{\mathit{comp}}}] in <<table-math-model-exchange,mathematical description>> of <<ContinuousTimeMode>>.

_[Example:_
_An assignment of the form_

----
y = ((x1 > x2) || (x1 < x3)) ? +1 : -1;
----

_can be implemented in the FMU as:_

----
// event indicator computation:
z1 = x1 - x2;
z2 = x3 - x1;

// relations do not change in <<ContinuousTimeMode>>
if <<InitializationMode>> || <<EventMode>> {
  r1 = z1 > 0;
  r2 = z2 > 0;
}
y = (r1 || r2) ? +1 : -1;
----

_Therefore, the original if-clause is evaluated in this form only during <<InitializationMode>> and <<EventMode>>._
_A hysteresis should be added for the event indicators to stabilize the event localization.]_
