== FMI for Model Exchange [[fmi-for-model-exchange]]

FMI for Model Exchange provides a standardized interface for solving ordinary differential equations with events (abbreviated as "hybrid ODE").
In contrast to FMI for Co-Simulation, a Model Exchange FMU implements the model algorithm only, without the required solution method.

The importer controls the data exchange and the synchronization between FMUs.

The solver algorithm itself is not part of the FMI standard.

The solver algorithm is responsible for:

* advancing the overall simulation time,
* exchange input and output data,
* computation of continuous state variables by time integration,
* triggering of input clocks, and
* handling events.

In contrast to Co-Simulation, the FMU is evaluated only at a specific time instant and not from one communication point to the next.
A Model Exchange FMU might consist of discrete-time equations only, for example, describing a sampled-data controller.

FMI for Model Exchange enables the following features:

* fixed or variable step, explicit or implicit integration algorithms,

* exact localization of <<state-event,state events>> using <<fmi3GetEventIndicators,event indicators>>,

* dedicated <<InitializationMode>>, which allows computation of consistent initial conditions over <<algebraic-loops,algebraic loops>>,

* handling of <<Clock,Clocks>> and <<EventMode,events>>,

* solution of algebraic loops involving inputs and output variables of this FMU (see <<algebraic-loops,algebraic loops>>),

* selective computation of FMU variables required by the solver algorithm, e.g. outputs, event indicators, derivatives (see <<selectiv-computation>>),

* the ability of the FMU to provide <<directionDerivatives,directional>> and <<adjointDerivatives,adjoint>> partial derivatives.

Which of the features above are supported by a specific FMU is defined by capability flags of the <<modelDescription.xml>> (see <<model-exchange-schema>>).
