== FMI for Model Exchange [[fmi-for-model-exchange]]

This chapter contains the interface description to access the equations of a dynamic system from a C program.
A schematic view of a model in FMI for Model Exchange format is shown in <<figure-model-exchange-data-flow>>:

.Data flow between the environment and an FMU for Model Exchange
[#figure-model-exchange-data-flow]
image::images/model-exchange-data-flow.svg[width=80%, align="center"]

[blue]*Blue* arrows: Information provided by the FMU. +
[red]*Red* arrows : Information provided to the FMU. +
latexmath:[\mathbf{v}_{\mathit{start}}], latexmath:[\mathbf{u}], latexmath:[\mathbf{y}], and latexmath:[\mathbf{w}], are of a numeric type or string;
latexmath:[\mathbf{t}], latexmath:[\mathbf{x}_c], latexmath:[\mathbf{z}] are of floating point type.

The goal of the Model Exchange interface is to numerically solve a system of differential, algebraic and discrete-time equations.
In this version of the interface, ordinary differential equations in state-space representation with events are handled (abbreviated as "hybrid ODE").
Algebraic equation systems might be contained inside the FMU.
Also, the FMU might consist of discrete-time equations only, for example, describing a sampled-data controller.
