=== Concepts [[concepts-co-simulation]]

==== Smoothness, Continuity and Discontinuity [[smoothness]]

Since inputs will be set at specific communication points by the importing tool, the FMU must make assumptions about the values between these communication points, including points of intermediate updates.

Between communication points, even in *Intermediate Update Mode*, all changes must be assumed to be continuous.
Changes to <<continuous>> variables are only considered discrete in *Event Mode*.

If a <<continuous>> input changes `discontinuously` (e.g. the actual input value deviates too much from the extrapolation polynomial), the co-simulation algorithm must raise an event (if supported) to indicate to the FMU a discontinuous change at an <<continuous>> input.
In the case of Co-Simulation without *Event Mode* (see <<eventModeUsed>> and <<hasEventMode>>), detecting discrete changes to continuous input variables (for instance to reset the integration algorithm within the FMU) requires heuristics.

<<discrete, `Discrete`>> inputs keep their values between communication points.
Furthermore, changing <<discrete>> variables at communication points will likely require special handling within the FMU.
Since the FMU itself can detect such changes, the co-simulation algorithm does not need to enter *Event Mode* in such a case, but must do so, in case event iteration is required.

==== Early Return [[early-return]]

A Co-Simulation FMU is allowed to stop the execution of <<fmi3DoStep>> and return without reaching the predefined communication time, i.e. <<currentCommunicationPoint>> `+` <<communicationStepSize>>.
This mechanism is called <<early-return,"early return">>.

Early return can be used to shorten a communication step because of:

* an event happened inside the FMU which influences its outputs non-continuously.
* the importer requests the stop of the current communication step in *Intermediate Update Mode*. _[E.g. the importer wants to stop a communication step because other parts of the simulation indicate the necessity.]_
* the FMU requests an additional communication point. _[E.g. the FMU wants to communicate extrema of outputs or prevent model inconsistencies, like negative pressure values, caused by extrapolation of inputs.]_

For details see <<earlyReturn>>.

The following capability flags describe which features the FMU supports:  <<canReturnEarlyAfterIntermediateUpdate>> and <<hasEventMode>>.

The argument <<earlyReturnAllowed>> of <<fmi3InstantiateCoSimulation>> signals to the FMU if the importer allows <<early-return,"early return">>.
