=== Co-Simulation Feature Selection [[co-simulation-feature-selection]]

The following co-simulation modes are supported in FMI 3.0

. Basic Co-Simulation (`fmi3ModeCoSimulation`, section <<co-simulation>>)
. Hybrid Co-Simulation (`fmi3ModeHybridCoSimulation`, section <<co-simulation-with-early-return>> and section <<clocked-co-simulation>>)
. Scheduled Execution Simulation (`fmi3ModeScheduledExecutionSimulation`, section <<scheduled-execution-simulation>>)

Each mode defines a specific set of features explained in the referenced subsections.

In each co-simulation mode also the intermediate variable access option can be activated, if the FMU and the master supports this. More information can be found in section <<intermediate-variable-access>>

It is required that the co-simulation master signals to the FMU which features shall be used for the current use of the FMU.

For that the following function is used: 

[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=Instantiate]
----

For details about this function please refer to section <<fmi-application-programming-interface>>.

The co-simulation master must set the function parameter `fmuType` to `fmi3CoSimulation` in order to activate the co-simultion use in general.

Additionally the co-simulation master has to configure the co-simulation mode used for the current instance of the FMU via setting the parameter `fmuCoSimulationConfiguration`.
This parameter is a struct 

[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=CoSimulationConfiguration]
----

that contains the enumeration variable `coSimulationMode` that is of type `fmi3CoSimulationMode` which has to be set to the co-simulation mode used for this FMU instance.

[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=CoSimulationMode]
----

The master can only activate co-simulation modes for an FMU that the FMU defines as supported via modelDescription.xml.
The modelDescription has to include the Element with name `CoSimulation` to be allowed to set the `fmuType` to `fmi3CoSimulation`. 

For setting the FMU to certain co-simulation modes the following capability flags (i.e. attribues) would have to be set to true.

[cols="1,2"]
|===
|*Co-Simulation Mode*
|*Attributes the mode requires to be true*

|`fmi3ModeCoSimulation`
|-

|`fmi3ModeHybridCoSimulation`
|`providesHybridCoSimulation`,

only if model internal information shall be transported between communication points: `providesIntermediateUpdates`, `canReturnEarlyAfterIntermediateUpdate`

|`fmi3ModeScheduledExecutionSimulation`
|`providesScheduledExecutionSimulation`,
 
only if model internal information shall be transported between communication points: `providesIntermediateUpdates`
|===

A detailed description of the capability flags is given in the following sections.

If the FMU can not provide a support for a co-simulation mode it has to refuse this mode via return value NULL for `fmi3Instantiate()`.

==== Multiple Co-Simulation Mode Support in one FMU

If the fmuType is `fmi3CoSimulation`, then an FMU should support multiple co-simulation modes so it can be used in differently capable co-simulation master implementations and for different use cases.
_[That improves the reusability of FMUs.   
A common application of this multiple mode support is the reuse of FMUs for real-time and non-real-time simulations.]_ 

The described multi mode support is based on wrapping functionality into the `fmi3DoStep()` function via emulating missing features of the mode the FMU has been originally exported for.

Generally it is assumed that an FMU always supports the co-simulation mode `fmi3ModeCoSimulation`. 
If that is not possible for an FMU
- e.g. if the FMU can not provide an emulation of inferred clock tick occurences -
it has to include the capability flag `canNotUseBasicCoSimulation` equals true in the modelDescription.XML.

_[Remark:_
_Wrapping towards other co-simulation modes can influence the simulation results._ 
_Depending on the model especially wrapping towards the mode fmi3ModeCoSimulation may result in divergent simulation results._
_Especially aperiodic inferred clocks can not always be sufficiently emulated in modes that do not directly support clocks._
_Therefore it is recommended that the FMU provides logging information to the user about the influence of the current mode on simulation results, if non-optimal modes are used by the simulation environment.
]_
