=== Concepts [[concepts-co-simulation]]

==== Smoothness, Continuity and Discontinuity [[smoothness]]

Since inputs are set at specific communication points by the importer, the FMU must make assumptions about the values between these communication points, including points of intermediate updates.

Between communication points, even in <<IntermediateUpdateMode>>, all changes must be assumed to be continuous.
Changes to <<continuous>> variables are only considered discrete in <<EventMode>>.

If a <<continuous>> input changes discontinuously (e.g. the actual input value deviates too much from the extrapolation polynomial), the co-simulation algorithm of the importer must raise an event (if supported) to indicate to the FMU a discontinuous change of a <<continuous>> input.
In the case of Co-Simulation without <<EventMode>> (see <<eventModeUsed>> and <<hasEventMode>>), detecting discrete changes to continuous input variables (for instance to reset the integration algorithm within the FMU) requires heuristics.

<<discrete, `Discrete`>> inputs keep their values between communication points.
Furthermore, changing <<discrete>> variables at communication points will likely require special handling within the FMU.
Since the FMU itself can detect such changes, the co-simulation algorithm does not need to enter <<EventMode>> in such a case, but must do so, in case event iteration is required.

==== Getting Derivatives of Continuous Outputs [[getting-output-derivatives]]

In FMI for Co-Simulation, the n-th <<derivative,`derivatives`>> with respect to time of continuous <<output,`outputs`>> may be retrieved with <<fmi3GetOutputDerivatives>>, for example, to allow interpolation/extrapolation of connected input variables between communication points by the importer in <<IntermediateUpdateMode>>. +

Whether the FMU is able to provide the <<derivative,`derivatives`>> of <<output,`outputs`>> is given by the capability flag <<maxOutputDerivativeOrder>> that represents the maximum order of the <<output>> <<derivative, `derivatives`>>.
If the actual order is lower (because the order of integration algorithm is low), the retrieved value is 0.

The returned values correspond to the derivatives at the current time of the FMU.
For example, after a successful call to <<fmi3DoStep>>, the returned values are related to the end of the communication step.

Function `fmi3GetOutputDerivatives`::

[[fmi3GetOutputDerivatives,`fmi3GetOutputDerivatives`]]
[source, C]
----
include::../headers/fmi3FunctionTypes.h[tags=GetOutputDerivatives]
----

--
* `valueReferences` is a vector of value references that define the variables whose <<derivative,`derivatives`>> shall be retrieved.
If multiple derivatives of a variable shall be retrieved, list the value reference multiple times.

* `nValueReferences` is the dimension of the arguments `valueReferences` and `orders`.

* `orders` contains the orders of the respective <<derivative>> (1 means the first <<derivative>>, 2 means the second <<derivative>>, ..., 0 is not allowed).
If multiple derivatives of a variable shall be retrieved, its value reference must occur multiple times in `valueReferences` aligned with the corresponding `orders` array.

* `values` is a vector with the values of the <<derivative,`derivatives`>>.
The order of the `values` elements is derived from a twofold serialization: the outer level corresponds to the combination of a value reference (e.g., `valueReferences[k]`) and order (e.g., `orders[k]`), and the inner level to the serialization of variables as defined in <<serialization-of_variables>>.
The inner level does not exist for scalar variables.

* `nValues` is the size of the argument `values`.
`nValues` only equals `nValueReferences` if all corresponding output variables are scalar variables.
--

_[ Example:_ +
_Assuming an FMU has outputs latexmath:[y_1][2*3] with value reference 1, latexmath:[y_2] with value reference 2, latexmath:[ y_3][2] value reference 3, latexmath:[y_4] with value reference 4 and `maxOutputDerivativeOrder`=2._ +
_With `valueReferences`= [1, 1, 3, 3, 4, 4], and `orders`= [1, 2, 1, 2, 1, 2], <<fmi3GetOutputDerivatives>> will provide first and second time derivatives of the outputs y1, y3, y4, which in `values` are serialized in the following way:_
_((array serialization of latexmath:[\dot y_1]), (array serialization of latexmath:[\ddot y_1]), (array serialization of latexmath:[\dot y_3]), (array serialization of latexmath:[\ddot y_3]), latexmath:[\dot y_4], latexmath:[\ddot y_4]).]_

==== Early Return [[early-return]]

A Co-Simulation FMU is allowed to stop the execution of <<fmi3DoStep>> and return without reaching the predefined communication time, i.e. <<currentCommunicationPoint>> `+` <<communicationStepSize>>.
This mechanism is called <<early-return,"early return">>.

Early return can be used to shorten a communication step because of:

* an event happened inside the FMU which influences its outputs non-continuously.
* the importer requests the stop of the current communication step in <<IntermediateUpdateMode>>. _[E.g. the importer wants to stop a communication step because other parts of the simulation indicate the necessity.]_
* the FMU requests an additional communication point. _[E.g. the FMU wants to communicate extrema of outputs or prevent model inconsistencies, like negative pressure values, caused by extrapolation of inputs.]_

For details see <<earlyReturn>>.

The following capability flags describe which features the FMU supports:  <<canReturnEarlyAfterIntermediateUpdate>> and <<hasEventMode>>.

The argument <<earlyReturnAllowed>> of <<fmi3InstantiateCoSimulation>> signals to the FMU if the importer allows <<early-return,"early return">>.
