=== State Machine for Co-Simulation [[state-machine-co-simulation]]

The state machine in <<figure-co-simulation-state-machine>> defines the supported calling sequences.

.Calling sequence of Co-Simulation C functions.
[#figure-co-simulation-state-machine]
image::images/state-machine-co-simulation.svg[width=80%, align="center"]

Each state of the state machine corresponds to a certain phase of a simulation.
Common states are defined in <<common-state-machine>>, such as super states <<FMUStateSetable,*FMU State Setable*>> and  <<Initialized,*Initialized*>>, states <<Instantiated,*Instantiated*>>, <<ConfigurationMode,*Configuration Mode*>>, <<ReconfigurationMode,*Reconfiguration Mode*>>, <<InitializationMode,*Initialization Mode*>>, <<Terminated,*Terminated*>> and <<IntermediateUpdateMode,*Intermediate Update Mode*>>.

==== State: Step Mode [[state-step-mode-co-simulation]]

This state is used by the importer to progress simulation time.

[#table-math-co-simulation]
[cols="2,1",options="header",]
|====
|Equations and Actions
|Functions Influencing Equations

|Set <<tunable>> <<parameter,`parameters`>> latexmath:[\mathbf{p}_{\mathit{tune}}] (and do not set other <<parameter,`parameters`>> latexmath:[\mathbf{p}_{\mathit{other}}])
|`fmi3Set{VariableType}`

|Set continuous-time and discrete-time <<input,`inputs`>> latexmath:[\mathbf{u}_{d+c}(t_i)]
|`fmi3Set{VariableType}`

|latexmath:[\begin{matrix} t_{i+1} := t_i + h_i \\ (\mathbf{y}_{c+d}, \mathbf{y}_c^{(j)}, \mathbf{w}_{c+d}) := \mathbf{f}_{\mathit{doStep}}(\mathbf{u}_{c+d}, \mathbf{u}_u,  t_i, h_i, \mathbf{p}_{\mathit{tune}}, \mathbf{p}_{\mathit{other}})_{t_i} \\ t_i := t_{i+1} \end{matrix}] +
latexmath:[\mathbf{f}_{\mathit{doStep}}] is also a function of the internal variables latexmath:[\mathbf{x}_c], latexmath:[^{\bullet}\mathbf{x}_d]
|`fmi3DoStep` +
`fmi3Get{VariableType}` +
`fmi3GetOutputDerivatives` +
`fmi3CallbackIntermediateUpdate`

|====

Allowed Function Calls::

Function <<fmi3EnterConfigurationMode>>::
Changes state to *Reconfiguration Mode*.
This function must not be called if the FMU contains no <<tunable>> <<structuralParameter,`structural parameters`>> (i.e. with <<causality>>= <<structuralParameter>> and <<variability>> = <<tunable>>).

Function <<fmi3EnterEventMode>>::
Changes state to *Event Mode*.
This function must not be called, if <<fmi3InstantiateCoSimulation>> signaled `eventModeUsed = fmi3False`, which implies that the capability flag `hasEventMode = true`.

Function <<fmi3DoStep>>::
Within <<fmi3DoStep>> the FMU may call <<fmi3CallbackIntermediateUpdate>>
* If the function returns with <<fmi3OK>> or <<fmi3Warning>> the FMU stays in this state.
* The importer must call <<fmi3DoStep>> with <<communicationStepSize, `communicationStepSize > 0.0`>>.
* If the function returns with <<earlyReturn,`earlyReturn == fmi3True`>> the FMU will change to states depending on the flags of <<fmi3CallbackIntermediateUpdate>>.
* The FMU may return immediately from <<fmi3DoStep>> with <<lastSuccessfulTime,`lastSuccessfulTime == currentCommunicationPoint`>> if an event was detected immediately at the <<currentCommunicationPoint>>.
Such an event might be caused by the change of an input during the communication point, or may be pending after the initialization.

Function `fmi3Set{VariableType}`::
For variables with:
* <<causality>> = <<input>>, or
* <<causality>> = <<parameter>> and <<variability>> = <<tunable>>

It is not allowed to call `fmi3Get{VariableType}` functions after `fmi3Set{VariableType}` functions without an <<fmi3DoStep>> call in between.

_[The reason is to avoid different interpretations of the caching, since contrary to FMI for Model Exchange, <<fmi3DoStep>> will perform the actual calculation instead of `fmi3Get{VariableType}`, and therefore, dummy algebraic loops at communication points cannot be handled by an appropriate sequence of `fmi3Get{VariableType}` and `fmi3Set{VariableType}` calls as for Model Exchange._

_Examples:_

.Examples for calling sequences.
[[table-example-calling-sequence]]
[cols="3,4",options="header"]
|====
|_Correct calling sequence_
|_Wrong calling sequence_

|_fmi3Set{VariableType} on inputs_ +
_fmi3DoStep_ +
_fmi3Get{VariableType} on outputs_ +
_fmi3Set{VariableType} on inputs_ +
_fmi3DoStep_ +
_fmi3Get{VariableType} on outputs_ +

|_fmi3Set{VariableType} on inputs_ +
_fmi3DoStep_ +
_fmi3Get{VariableType} on outputs_ +
_fmi3Set{VariableType} on inputs_ +
_fmi3Get{VariableType} on outputs // not allowed_ +
_fmi3DoStep_ +
_fmi3Get{VariableType} on outputs_ +
|====
_]_
