=== Early Return [[co-simulation-with-early-return]]
:DOSTEP: fmi3DoStep()
 
In FMI-3, an FMU is allowed to stop the execution of `{DOSTEP}` and return without reaching the predefined communication instant, i.e. `currentCommunicationPoint + communicationStepSize`.
This mechanism is called early-return.
With the early return feature, an FMU shall be able to signal triggered clock events or internal state changes, i.e., discontinuity events to the co-simulation master at any time (not only at the end of `{DOSTEP}` function calls). 
When an FMU internal event happens at a time instant, the FMU informs the master that a new communication point for the co-simulation can (or will) be created.
Note that, an event signal is not seen in the narrow sense of solver induced discontinuity events but in the general sense of a simulation event that has to be handled by the co-simulation master (e.g. state changes that require extended handling).
In this way multiple event types and also triggered clock ticks or interrupts are covered.

