=== Code Examples

==== Basic Co-Simulation

[source, C]
----
include::Reference-FMUs/examples/simulate_fmi3_cs.c[tags=CoSimulation]
----

The plot below shows the output for the https://github.com/modelica/Reference-FMUs[BouncingBall Reference FMU] with a communication step size of 0.1 s.
Note that the points where the ball hits the floor are missed.

image::images/BouncingBall_cs.svg[width=100%]

==== Early Return

[source, C]
----
include::Reference-FMUs/examples/cs_early_return.c[tags=EarlyReturn]
----

The plot below shows the output for the https://github.com/modelica/Reference-FMUs[BouncingBall Reference FMU] with a communication step size of 0.1 s.
Note that the points where the ball hits the floor are available, but only the outputs after the events are recorded.

image::images/cs_early_return.svg[width=100%]

==== Event Mode

[source, C]
----
include::Reference-FMUs/examples/cs_event_mode.c[tags=EventMode]
----

The plot below shows the output for the https://github.com/modelica/Reference-FMUs[BouncingBall Reference FMU] with a communication step size of 0.1 s.
Note that the points where the ball hits the floor are available and the outputs before and after the event are recorded.

image::images/cs_event_mode.svg[width=100%]

==== Intermediate Update

[source, C]
----
include::Reference-FMUs/examples/cs_intermediate_update.c[tags=IntermediateUpdateCallback]
----

The plot below shows the output for the https://github.com/modelica/Reference-FMUs[BouncingBall Reference FMU] with a communication step size of 0.1 s.
Note that the outputs at all intermediate steps are recorded, too.

image::images/cs_intermediate_update.svg[width=100%]

==== Connected FMUs

In the following example, the usage of the FMI functions is sketched in order to clarify the typical calling sequence of the functions in a simulation environment.
We consider two FMUs, where both have one <<continuous>> floating point <<input>> and one <<continuous>> floating point <<output>> which are connected in the following way:

.Connection graph of FMUs.
image::images/co-simulation-connection-of-FMUs.svg[width=30%, align="center"]

We assume no algebraic dependency between input and <<output>> of each FMU.
The code demonstrates the simplest importer as shown in <<state-machine-co-simulation>>:

- Constant communication step size.
- No repeating of communication steps.
- The error handling is implemented in a very rudimentary way.

[source, C]
----
include::Reference-FMUs/examples/co_simulation.c[tags=CoSimulation]
----

==== Clocks [[code-example-clocked-co-simulation]]

In the following example, the usage of the FMI functions is sketched in order to clarify the typical calling sequence of the functions in a simulation environment.
We consider ...

The error handling is implemented in a very rudimentary way.

// TODO: add code example

//[source, C]
//----
//include::examples/c-code/co_simulation_clocked.c[tags=CoSimulation]
//----
