=== FMI Description Schema

The simulation master collects the information about the number and properties of clocks supported by the FMU via analyzing the modelDescription.xml as defined in section 2.2. and 4.3.

Each clock that ticks outside of the FMU is activated for an FMU based on its clockReference. 
There is a direct one-to-one relation for a clock and a model partition.

If clocks are defined and the flag `canHandleScheduledExecutionSimulation` equals true, the co-simulation master can set the fmuType to `fmi3ScheduledExecutionSimulation`. 
If no inferred clocks are defined the flag `canHandleScheduledExecutionSimulation` shall not be set to true.

Please note that the FMU should additionally provide an `fmi3DoStep()` wrapper function that supports the fmuType settings `fmi3ClockedCoSimulation` and `fmi3EarlyReturn` and `fmi3CoSimulation` for computing the model partitions without the need for direct model partition scheduling. 
If the FMU can not provide such wrapping it has to refuse this mode via return NULL in `fmi3Instantiate()` also if the FMU can not provide a wrapping i.e. internal emulation of clock ticks it has to include the flag canEmulateClockTicks = false. 
If `canEmulateClockTicks` equals false, the importing tool has the information that this FMU can not be run in mode  `fmi3CoSimulation` or `fmi3EarlyReturn`.

_[Remark:_
_Note that wrapping towards other co-simulation modes can influence the simulation results._ 
_Depending on the model especially the mode fmi3CoSimulation may result in divergent simulation results._
_Problematic are especially aperiodic inferred clocks_
_Therefore it is recommended that the FMU provides logging information about the influence of wrapping modes, if non-optimal modes are used by the simulation environment.
]_


==== Example XML Description File

The example below is the same one as shown in section [TBD] for a `fmi3ClockedCoSimulation` FMU.

[source, xml]
----
include::examples/co_simulation_scheduled_execution.xml[]
----
