:INSTANTIATE: fmi3Instantiate()

==== FMI Description Schema [[clocked-co-simulation-schema]]

The co-simulation master collects the information about the number and properties of clocks supported by the FMU by analyzing the modelDescription.xml - #[TODO] see section x.x.x#.

The definition of clocks is optional.
If clocks are defined, the co-simulation master can set the `fmuType` to `fmi3CoSimulation` and `fmuCoSimulationConfiguration.coSimulationMode` to `fmi3ModeHybridCoSimulation` at `{INSTANTIATE}`. #[TODO]: Recheck#

Each inferred clock that ticks outside of the FMU, is activated for an FMU based on their _valueReferences_.
Triggered clocks inside of an FMU signal their activation based on their _valueReferences_.

#[TODO]: Comment Andreas Pillekeit: OpenPoint: has to be checked if clocks are defined as variables.#
If dependencies (_fmi3VariableDependency_) are defined in the _Modelstructure_ section of the _modelDescription.xml_, it is recommended to define such dependencies only within a model partition of a model (i.e. between variables that are assigned to the same clock).
If dependencies are defined for variables across model partitions, such variables can not be assigned to a clock via _clockReference_.

For FMI for Co-Simulation, variables that are assigned to a model partition of the model based on _clockReference_ are not necessarily "clocked".
Such variables can be Continuous-time or Discrete-time variables if the clock is of clockType = CPClock.


===== Co-Simulation FMU (CoSimulation) [[clocked-co-simulation-schema-cosimulation]]

#[TODO]: To be removed? Properties of clocks are already described in section 2_2_common_schema.#


===== Example XML Description File [[clocked-co-simulation-schema-example-xml]]

The example below is the same one as shown in #[TODO] section x.x.x for XXX# FMU.
The only difference is #[TODO] ...# .
The XML file may have the following content:

[source, xml]
----
//include::examples/co_simulation_clocked_cosimulation.xml[]
----