==== FMI Description Schema [[clocked-co-simulation-schema]]

The co-simulation master collects the information about the number and properties of clocks supported by the FMU via analyzing the modelDescription.xml - [red]##see section x.x.x##.

The definition of clocks is optional. If clocks are defined, the co-simulation master can set the `fmuType` to `fmi3ClockedCoSimulation`.

Each inferred clock that ticks outside of the FMU is activated for an FMU based on their _valueReferences_.
Triggered clocks inside of an FMU signal their activation based on their _valueReferences_.

If dependencies (_fmi3VariableDependency_) are defined in the _Modelstructure_ section of the modelDescription.xml, it is recommended to define such dependencies only within a model partition of a model (i.e. between variables that are assigned to the same clock).
If dependencies are defined for variables across model partitions, such variables can not be assigned to a clock via _clockReference_.

For FMI for Co-Simulation, variables that are assigned to a model partition of the model based on clockReference are not necessarily “clocked”.
Such variables can be Continuous-time or Discrete-time variables if the clock is of clockType CPClock.


===== Co-Simulation FMU (CoSimulation) [[clocked-co-simulation-schema-cosimulation]]

[red]#---
To be removed? Properties of clocks were described in section 2_2_common_schema
---#


===== Example XML Description File [[clocked-co-simulation-schema-example-xml]]

The example below is the same one as shown in section [red]#x.x.x# for [red]#XXX# FMU.
The only difference is ... .
The XML file may have the following content:

// Dummy:
[source, xml]
----
//include::examples/co_simulation_clocked_cosimulation.xml[]
----