=== Scheduled Execution Simulation [[scheduled-execution-simulation]]

The co-simulation mode `fmi3ModeHybridCoSimulation` provides an indirect control over the computation of model partitions associated to clocks via `fmi3SetClock()` and a subsequent `fmi3DoStep()` call. With the mode `fmi3ModeScheduledExecutionSimulation` it is possible that a simulation master takes direct control over the time of computation (i.e. scheduling) for such model partitions.

The reasons for adding this co-simulation mode are that some simulation use cases require:

. That at any time (even for unpredictable events) an event can be signaled to an FMU
. If multiple FMUs share (execution) resources then the time requirements (e.g. execution time, communication deadlines) of all model partitions have to be observed and respected
.. Time requirements may exist due to communication constraints that are not apparent at FMU simulation level that have to be fulfilled by the simulation master
.. That requires a global excecution order and preemption policy for all model partitions of the multiple FMUs 
.. Priority information provided by the FMUs has to be evaluated and merged to an overall priority for available model partitions
. Data shall move between the different FMU model partitions for the same or next activation time, if direct communication via FMUs exist.
.. Get/set actions must also be possible for the same activation time for different model partitions between the computation of these model partitions.

The aim of this simulation mode for FMI 3.0 is to provide support for a concurrent computation of model partitions via `fmi3ActivateModelPartition()` calls and related `fmi3GetXXX()`,`fmi3SetXXX()` calls (i.e. a support of multiple rates) on a single computational resource (e.g. CPU-core) for an FMU. 
For that a preemptive multitasking regime is intended (cooperative multitasking is not covered by this description!).

_[Please note: A parallel computation of model partitions is not part of the FMI 3.0 API. 
An FMU may still internally use parallel computation on multiple cores, but handling this is (currently) not part of the FMI standard. Such an internal parallel computation is not visible to the simulation master.
It is a tool vendor specific solution that has ties to the used OS and the co-simulation environment]_