=== Mathematical Description

==== Basics

Intermediate output variables has three main uses:

1. *An FMU is able to produce valid output variables at intermediate points
during a communication interval.* This is typically the result of an internal
solver taking multiple integration steps at each communication interval.
The FMU exposes intermediate output variables for the master whenever they are
available. These can be used for e.g. extrapolation, interpolation, filtering
or asynchronous co-simulation.

2. *Intermediate input variables for an FMU is available in the co-simulation
master.* The FMU requests updated intermediate input variables every time they
are required by the internal solver. This can be either at temporary solver
states or after successful integration steps.

3. *Intermediate input variables for the FMU can be computed by the
co-simulation master.* The computation requires intermediate output
variables from the FMU. Whenever the internal solver in the FMU needs
updated intermediate input variables, it provides the intermediate
output variables for and requests the intermediate input variables from
the master.

Combinations of the above methods are also allowed.



//In some cases, intermediate variables for an FMU are available not only before the step, but also at intermediate times during the step
// - Asynchronous co-simulation, where other FMUs have already simulated longer a step so that data is available
// - Anti-aliasing filters
// - Extrapolation algorithms in master
// - Transmission Line Method

//Intermediate input variables may be explicitly available, or need to be computed using intermediate output variables from the FMU

//Important to know if intermediate output variables origins from a temporary state in the internal solver, or if the internal step is finished
//- Step finished: intermediate outputs can be used for computing intermediate inputs, but also forwarded to other connected models
//- Temporary state: intermediate outputs are only valid for the temporary state. They shall only be used for computing intermediate input variables for the same state.
