=== Mathematical Description

==== Basics

Intermediate variable access has three main uses:

1. *An FMU is able to produce valid output variables at intermediate points
during a communication interval.* This is typically the result of an internal
solver taking multiple integration steps at each communication interval.
The FMU exposes intermediate output variables for the master whenever they are
available. These can be used for e.g. extrapolation, interpolation, filtering
or asynchronous co-simulation.

2. *Intermediate input variables for an FMU is available in the co-simulation
master.* The FMU requests updated intermediate input variables every time they
are required by the internal solver. This can be either at temporary solver
states or after successful integration steps.

3. *Intermediate input variables for the FMU can be computed by the
co-simulation master.* The computation requires intermediate output
variables from the FMU. Whenever the internal solver in the FMU needs
updated intermediate input variables, it provides the intermediate
output variables for and requests the intermediate input variables from
the master.

Combinations of the above methods are also allowed.

Access to intermediate variables enables several features such as

* Advanced interpolation/extrapolation techniques
* Asynchronous communication
* Anti-alias filtering
* Smoothing of inputs
