=== FMI Application Programming Interface
:DOSTEP: fmi3DoStep()

In order to support intermediate variable access during `fmi3DoStep` a variable
capability flag in the XML file is required:

`intermediateAccess`  = `true/false` with default value set to `false`

If an FMU has at least one variable with `intermediateAccess=true`, it can
invoke the  `fmi3IntermediateStepFinished()` callback function, so that the
`fmi3IntermediateStepInfo` is sent back to the co-simulation master.

[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=IntermediateStepInfo]
----

The following flags in the `fmi3IntermediateStepInfo`struct are used for
intermediate variable access:

*   `intermediateStepTime` is the simulation time at which the discontinuity
has occurred within the FMU.

*   when `intermediateVariableSetAllowed` is `fmi3True` the co-simulation
master is allowed to provide intermediate input variables by calling `setXXX`
functions for variables with `intermediateAccess=true`.

*   when `intermediateVariableGetAllowed` is `fmi3True` the co-simulation
master is allowed to collect intermediate output variables by calling `getXXX`
functions for variables with `intermediateAccess=true`.

*   when `internalStepFinished` is `fmi3False` the co-simulation master shall
only use intermediate output variables to compute intermediate input variables
at the current state.

Hence, it is important to distinguish intermediate output from successful
internal integration steps from intermediate outputs valid only for temporary
solver states. The figure below shows an overview of the solver states and the
intended use of intermediate variable access.

.Overview of solver states and intermediate variable access during a communication step
[caption="Figure 12: "]
image::images/intermediatevariableaccess.svg[width=400%, align="center"]

==== Pseudo-code Example

In the following example, the usage of the intermediate variable access is
illustrated in order to clarify the typical calling sequence of the functions
in a simulation environment. The example is given in a mix of pseudo-code and
`'C'`, in order to keep it small and understandable.
See pseudocode:
[source, c]
----
include::examples/pseudo_code_co_simulation_intermediate_variable_access.txt[]
----
