== FMI for Co-Simulation [[fmi-for-co-simulation]]

FMI for Co-Simulation provides a standardized interface for execution of simulation models or tools in a co-simulation environment.
In contrast to FMI for Model Exchange, a Co-Simulation FMU implements not only the model algorithm, but also the required solution method.
The data exchange between FMUs is restricted to discrete communication points latexmath:[\mathbf{t}_i].
In the time between two communication points, the subsystem inside an FMU is solved independently by internal means.
This leads to a delay of one communication step for information "traveling through" the FMU, so there cannot be an immediate reaction (direct feedthrough) as in *Initialization Mode*, *Event Mode* or *Continuous-Time Mode*.
The co-simulation algorithm of the importer controls the data exchange and the synchronization between FMUs.

The co-simulation algorithm itself is not part of the FMI standard.

The co-simulation algorithm is responsible for:

* advancing the overall simulation time,
* exchange input and output data,
* triggering of input clocks, and
* handling events.

For FMI for Co-Simulation the co-simulation algorithm is shielded from how the FMU advances time internally.
For example, FMUs containing ODEs and implementing FMI for Co-Simulation require to include an ODE solver inside the FMU to internally advance time between the communication points.
As another example, FMUs representing controller code, an internal scheduling algorithm will trigger tasks at the correct time and order while advancing time to the next communication point.

A schematic view of an FMU for Co-Simulation is shown in <<figure-co-simulation-data-flow>> (<<KS00>>).

.Data flow between the co-simulation algorithm of the importer and the FMU for Co-Simulation
[#figure-co-simulation-data-flow]
image::images/co-simulation-data-flow.svg[width=80%, align="center"]

FMI for Co-Simulation enables the following features, allowing co-simulation algorithms of arbitrary sophistication:

* variable or constant communication step sizes latexmath:[\mathbf{h}_i] (see <<communicationStepSize>>),

* reject and repeat communication steps (see <<get-set-fmu-state>>), e.g. with reduced communication step size or a different set of input values,

* update inputs at intermediate points within a communication step (see <<IntermediateUpdateMode>>),

* return early from <<fmi3DoStep>> at latexmath:[\mathbf{t} \leq \mathbf{t}_{i+1}], because, for example, an event influencing the environment was detected by the FMU (see <<early-return>>),

* handling of <<clock,clocks>> and <<EventMode,events>>,

* the ability to provide <<derivative,`derivatives`>> of <<output,`outputs`>> w.r.t. time, to allow approximation techniques (<<getting-output-derivatives>>), and

//TODO: Christian: is this the correct formulation?
* the ability to provide <<directionDerivatives,directional>> and <<adjointDerivatives,adjoint>> partial derivatives.

Which of the features above are supported by a specific FMU is defined by capability flags of the <<modelDescription.xml>> (see <<co-simulation-schema>>).
