== FMI for Co‑Simulation [[fmi-for-co-simulation]]

This chapter defines the Functional Mock-up Interface (FMI) for the coupling of two or more simulation models in a co-simulation environment (FMI for Co-Simulation).
It is designed both for coupling with subsystem models, which have been exported by their simulators together with its solvers as runnable code (<<figure-co-simulation-with-generated-code>>), and for coupling of simulation tools (simulator coupling, tool coupling (<<figure-co-simulation-with-tool-coupling>> and <<figure-co-simulation-with-generated-code>>)).
Co-simulation is a rather general approach to the simulation of coupled technical systems and coupled physical phenomena in engineering with focus on instationary (time-dependent) problems.

In FMI version 3.0 the following new features have been added:  

* Signal clock ticks (i.e. events/interrupts) from FMU to simulation environment
* Signal clock ticks from simulation environment to FMU
* Define multiple model rates (periodic, variable/triggerable) in one FMU
* Access intermediate values of FMU variables between two communication points.

Please refer to the different fmuType sections for a more detailed explanation of the motivation and use of the new features.

* Co-Simulation (<<co-simulation>>)
* Co-Simulation with Early Return (<<co-simulation-with-early-return>>)
* Clocked Co-Simulation (<<clocked-co-simulation>>)
* Scheduled Execution Simulation (<<scheduled-execution-simulation>>)
* Intermediate Variabe Access (<<intermediate-variable-access>>)


.Co-simulation with generated code on a single computer (for simplicity shown for one slave only).
[#figure-co-simulation-with-generated-code]
image::images/co-simulation-single-slave.svg[width=50%, align="center"]

.Co-simulation with tool coupling on a single computer (for simplicity shown for one slave only).
[#figure-co-simulation-with-tool-coupling]
image::images/co-simulation-tool-coupling.svg[width=70%, align="center"]

In the tool coupling case the FMU implementation wraps the FMI function calls to API calls which are provided by the simulation tool (for example, a COM or CORBA API).
Additionally to the FMU the simulation tool is needed to run a co-simulation.

In its most general form, a tool coupling based co-simulation is implemented on distributed hardware with subsystems being handled by different computers with different OS (cluster computer, computer farm, computers at different locations).
The data exchange and communication between the subsystems is typically done using one of the network communication technologies (for example, MPI, TCP/IP).
The definition of this communication layer is not part of the FMI standard.
However, distributed co-simulation scenarios can be implemented using FMI as shown in <<figure-distributed-co-simulation>>.

.Distributed co-simulation infrastructure (for simplicity shown for one slave only).
[#figure-distributed-co-simulation]
image::images/co-simulation-distributed-infrastructure.svg[width=90%, align="center"]

The master has to implement the communication layer.
Additional parameters for establishing the network communication (for example, identification of the remote computer, port numbers, user account) are to be set via the GUI of the master.
These data are not transferred via the FMI API.
