=== Application Programming Interface [[scheduled-execution-api]]

This section contains the description of the Scheduled Execution interface for a C program.

The direct scheduling of model partitions based on <<clock>> ticks requires an additional handling mode for FMUs.
The FMU signals its support for direct model partition scheduling in the <<modelDescription.xml>> via the element `<fmiModelDescription><ScheduledExecution>`.
The Co-Simulation master signals to the FMU that it supports and has recognized the <<clock>> and model partition scheduling capabilities of the FMU by instantiating it as Scheduled Execution.

Error, reset or terminate information is a global state of the FMU.
If e.g. an function returns <<fmi3Discard>> or <<fmi3Error>> this is also assumed for all active or preempted model partitions.
In case of <<fmi3Discard>> or <<fmi3Error>> no repetition of the step is possible, the only possible way to go forward is to enter the *Terminated* state and to end or to reset the simulation or - if supported - to set the FMU back to a former state.

==== Transfer of Input/Output Values and Parameters in Scheduled Execution

The simulation master sets and gets variable values as defined in <<get-and-set-variable-values>>.

Before scheduling a model partition it is allowed to set all variables assigned to that model partition via its associated <<clock>> (including all global variables that are not associated to a <<clock>>) via `fmi3Set{VariableType}`.
After the computation of a model partition (call of <<fmi3ActivateModelPartition>> with the <<clockReference>> and <<clockElementIndex>> of the <<clock>> that is associated to the model partition) all variables that are assigned to this model partition (including all global variables that are not associated to a <<clock>>) can be retrieved via `fmi3Get{VariableType}`.
Set/get operations have to be atomic for a single variable.

_[The value of global variables can be influenced by more than one model partition if multiple model partitions are active at the same time.]_

The computational effort has to be predictable, thus all computationally expensive operations needed to calculate a model partition have to be contained within the <<fmi3ActivateModelPartition>> function.
The simulation master can assume that `fmi3Get{VariableType} and fmi3Set{VariableType}` operations are not computationally expensive.
In Scheduled Execution the handling of <<fmi3CallbackIntermediateUpdate>> callbacks is the same as in <<fmi-for-co-simulation>>.
The only difference is that an early return has no meaning in this mode and no additional event handling based on <<fmi3NewDiscreteStates>> is conducted.
All internal events that shall be handled by the Co-Simulation master are signaled via <<fmi3CallbackIntermediateUpdate>>.
_[In this mode it is recommended to restrict such updates by the FMU to <<outputClock>> ticks for reducing the computational load in real-time simulations.]_

==== Computation in Scheduled Execution

If this mode is set, the master has to directly control the time of computation of model partitions associated to <<inputClock,`input clocks`>>.
The activation states of <<outputClock,`output clocks`>> are transported via <<fmi3CallbackIntermediateUpdate>> and <<fmi3GetClock>>.

[[fmi3ActivateModelPartition, `fmi3ActivateModelPartition`]]
Each <<fmi3ActivateModelPartition>> call is now associated to the computation of a (publicly disclosed, externally controlled) model partition of the model and therefore to a single defined <<inputClock>>.

[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=ActivateModelPartition]
----

The <<fmi3ActivateModelPartition>> function has the following arguments:

- `fmi3Instance instance`: same meaning as for other `fmi3*` functions

- `fmi3ValueReference` <<clockReference>>: <<valueReference>> of an <<inputClock>> variable defined in the <<modelDescription.xml>> which shall be activated

- `size_t` <<clockElementIndex>>:: The element index of the <<inputClock>> variable which shall be activated.
For a scalar <<clock>> variable this must be 0; for array <<clock>> variables the element clock to activate is specified using the 1-based element index.
Using the element index 0 means all elements of the <<clock>> variable.
(Note: If an array has more than one dimension the indices are serialized in the same order as defined for values).

- `fmi3Float64 activationTime`: value of the <<independent>> variable of the assigned <<inputClock>> tick time latexmath:[t_i] _[typically: simulation (i.e. virtual) time]_ (which is known to the Co-Simulation master).

Scheduling of <<fmi3ActivateModelPartition>> calls for each FMU is done by the simulation master.
Calls are based on ticks of <<periodic>> or <<periodic,aperiodic>> <<inputClock,`input clocks`>>.
These <<inputClock>> ticks can be based on <<clock>> ticks from FMU external sources (e.g. <<outputClock,`output clocks`>> of other FMUs) or other external <<clock,`clocks`>>/events/interrupts assigned via the simulation master configuration (such external events can be based on a potentially unpredictable process or can be just simulation time based events e.g. the planned communication point).
The <<inputClock>> ticks can also be based on <<outputClock,`output clock`>> ticks of the same FMU.
Refer to <<math-scheduled-execution>> and <<clock-types-for-evaluation-of-clocked-model-partitions>>.
The <<fmi3ActivateModelPartition>> function is not called for <<outputClock,`output clocks`>> of an FMU.

Note that this is a different timing concept compared to <<fmi3DoStep>> calls.
A <<fmi3ActivateModelPartition>> call will compute the results of the model partition defined by <<clockReference>> and <<clockElementIndex>> (i.e. <<valueReference>> of the variable that defines a <<clock>> and an element index into that for arrays) for the current <<clock>> tick latexmath:[t_i].

If required, the FMU can internally derive the <<clock>> interval latexmath:[\Delta T_i] based on the last <<clock>> tick time latexmath:[t_{i-1}] i.e. last `activationTime` for this <<clockReference>> and <<clockElementIndex>> (based on last <<fmi3ActivateModelPartition>> call).

Consecutive calls to <<fmi3ActivateModelPartition>> for a <<clockReference>> and <<clockElementIndex>> (i.e. <<valueReference>> of <<clock>> variable and element index into that for arrays) must have strictly monotonically increasing `activationTime` latexmath:[t_i].

==== State Machine for Scheduled Execution [[state-machine-scheduled-execution]]

This section summarizes the available states and the allowed function calls in the respective states.

.Calling sequence of Scheduled Execution C functions in form of a UML 2.0 state machine.
[#figure-scheduled-execution-state-machine]
image::images/state-machine-scheduled-execution.svg[width=80%, align="center"]

If the master intends to enter the state *Terminated* it must ensure that all tasks related to model partitions of the FMU have ended.
Hence if in states *Clock Activation Mode*, *Intermediate Update Mode*, or *Reconfiguration Mode* a function returns <<fmi3Fatal>> the master may prematurely end all tasks related to the computation of model partitions of this FMU.
If in these states a function returns <<fmi3Discard>> or <<fmi3Error>> the master may wait until all other tasks of the model partitions of this FMU have ended, but new tasks must not be started.

In Scheduled Execution the following functions must not be called: <<fmi3DoStep>>, <<fmi3NewDiscreteStates>>, <<fmi3SetClock>>, <<fmi3SetIntervalDecimal>>, <<fmi3SetIntervalFraction>>, <<fmi3EnterEventMode>>, <<fmi3EnterStepMode>> including all functions that are specific to the Model Exchange interface.

The states *Configuration Mode*, *Instantiated*, *Initialization Mode*, and *Terminated* are handled in the same way as in Co-Simulation, with the exception that the generally not allowed functions of Scheduled Execution must not be called.

===== State: FMU State Setable

In all states of this super state it is allowed to call <<fmi3GetFMUState>>, `fmi3SetFMUState`, `fmi3FreeFMUState`, <<fmi3SerializedFMUStateSize>>, <<fmi3SerializeFMUState>>, <<fmi3DeSerializeFMUState>>, <<fmi3Reset>>, <<fmi3GetVersion>>, `fmi3SetDebugLogging` and <<fmi3FreeInstance>>.
If any function returns with <<fmi3Fatal>> the FMU enters the state *Terminated*.

===== State: Under Evaluation

This super state is entered by the FMU when <<fmi3Instantiate>> is called.
If any function returns <<fmi3Error>> or <<fmi3Discard>> the FMU enters state *Terminated*.

===== State: Initialized

This super state is entered by the FMU when `fmi3ExitInitializatoinMode` is called.
If the function <<fmi3Terminate>> is called, the FMU enters state *Terminated* from all states of this super state.
The FMU enters state *Terminated* only after all other tasks related to the computation of model partitions of this FMU have ended.
After <<fmi3Terminate>> has been called no new tasks can be started (e.g. related to <<outputClock>> ticks) and all other function calls for this FMU must return <<fmi3Error>> until the state *Terminated* is reached.

===== State: Clock Activation Mode

The FMU enters this state when the master calls <<fmi3ExitInitializationMode>> in state *Initialization Mode* or <<fmi3ExitConfigurationMode>> in state *Reconfiguration Mode*.
In this state the master can create multiple concurrent tasks related to an FMU and in each task the master can activate one or multiple <<inputClock,`input clocks`>> of an FMU based on the defined <<clock>> properties via a <<fmi3ActivateModelPartition>> call for each <<clock>>.

Allowed Function Calls::

<<fmi3ActivateModelPartition>>::
It is recommended to call `fmi3Set{VariableType}` and `fmi3Get{VariableType}` in the same task as <<fmi3ActivateModelPartition>> for setting and retrieving variable values associated with the same <<clock>> activation.

<<get-and-set-variable-values,`fmi3Set{VariableType}`>>::
This function can be called before the start of the computation of a model partition.

<<get-and-set-variable-values,`fmi3Get{VariableType}>>`, `fmi3GetOutputDerivatives`, <<fmi3GetDirectionalDerivative>>::
These functions can be called after the end of the computation of a model partition.

For <<get-and-set-variable-values,`fmi3Set{VariableType}`>> <<get-and-set-variable-values,`fmi3Get{VariableType}>>`, `fmi3GetOutputDerivatives` and <<fmi3GetDirectionalDerivative>> it is not allowed to access variables associated to clocks other than the model partition's <<inputClock>>.
The restrictions related to variable <<causality>> and <<variability>> defined for *Step Mode* in <<fmi-for-co-simulation,`Co-Simulation`>> apply.

It is not allowed to call `fmi3Get{VariableType}` functions after `fmi3Set{VariableType}` functions without an <<fmi3ActivateModelPartition>> call in between.

_[The reason is to avoid different interpretations of the caching, since contrary to <<fmi-for-model-exchange, `FMI for Model Exchange`>>, <<fmi3ActivateModelPartition>> will perform the actual calculation instead of `fmi3Get{VariableType}`, and therefore, dummy algebraic loops at communication points cannot be handled by an appropriate sequence of `fmi3Get{VariableType}` and, `fmi3Set{VariableType}` calls as for Model Exchange._

_Example:_

[cols="3,4",options="header"]
|====
|_Correct calling sequence for a model partition_
|_Illegal calling sequence_

|_fmi3Set{VariableType} on inputs_ +
fmi3ActivateModelPartition +
_fmi3Get{VariableType} on outputs_ +
_fmi3Set{VariableType} on inputs_ +
fmi3ActivateModelPartition +
_fmi3Get{VariableType} on outputs_ +

|_fmi3Set{VariableType} on inputs_ +
fmi3ActivateModelPartition +
_fmi3Get{VariableType} on outputs_ +
_fmi3Set{VariableType} on inputs_ +
_fmi3Get{VariableType} on outputs // not allowed_ +
fmi3ActivateModelPartition +
_fmi3Get{VariableType} on outputs_ +
|====

_]_

<<fmi3CallbackIntermediateUpdate>>::
Only in this state the FMU is allowed to call the callback <<fmi3CallbackIntermediateUpdate>>.
The callback may be called from concurrent tasks within <<fmi3ActivateModelPartition>>.
The function must not return <<fmi3Discard>>.

<<fmi3EnterConfigurationMode>>::
This function must not be called if the FMU contains no <<structuralParameter,`structural parameters`>> or other tasks related to the computation of model partitions of this FMU are currently active or preempted.
Thus this function can not be called concurrently for model partitions of an FMU but only for the whole FMU instance.
+
If the function returns with <<fmi3OK>> or <<fmi3Warning>> the FMU goes into state *Reconfiguration Mode*.

`fmi3Terminate`, `fmi3Reset`, <<fmi3FreeInstance>>::
These functions can not be called concurrently for model partitions of an FMU but only for the whole FMU instance.
If these functions are called while a model partition of an FMU is currently active or preempted, the FMU changes its state after the computation of all model partitions of this FMU has ended.

<<fmi3GetFMUState>>, <<fmi3SetFMUState>>, <<fmi3FreeFMUState>>,<<fmi3SerializedFMUStateSize>>, <<fmi3SerializeFMUState>>, <<fmi3DeSerializeFMUState>>::
These functions can be called if no other task related to the computation of model partitions of this FMU is currently active or preempted and the prerequisites defined for these functions in Co-Simulation are fulfilled.
Thus these functions can not be called concurrently for model partitions of an FMU but only for the whole FMU instance.

Forbidden Function Calls::
Additionally to the generally forbidden functions in Scheduled Execution as listed above, the following functions must not be called in this state: <<fmi3ExitConfigurationMode>>, <<fmi3Instantiate>>, <<fmi3EnterInitializationMode>>, <<fmi3ExitInitializationMode>>.

===== State: Intermediate Update Mode

The FMU transports activation states of <<outputClock,`output clocks`>> to the master by calling <<fmi3CallbackIntermediateUpdate>> and providing <<fmi3GetClock>>.
The master provides the implementation of <<fmi3CallbackIntermediateUpdate>>.
If the master detects that an <<outputClock,`output clocks`>> ticked and this <<outputClock,`output clock`>> is configured to <<triggeredBy,`trigger`>> an <<inputClock,`input clock`>> the master schedules a task associated to this <<inputClock,`input clock`>>.

The FMU enters this state by calling <<fmi3CallbackIntermediateUpdate>>  within <<fmi3ActivateModelPartition>> and leaves the state towards state *Clock Activation Mode* if the function returns <<fmi3OK>> or <<fmi3Warning>>.
If the function returns <<fmi3Error>> the FMU enters state *Terminated*.
If the function returns <<fmi3Fatal>> the FMU enters the terminal state.

Forbidden Function Calls::
The same functions which are not allowed to be called in *Clock Activation Mode* must not be called in this state. Additionally the following functions must not be called <<fmi3ActivateModelPartition>>, <<fmi3EnterConfigurationMode>>, <<fmi3Terminate>>.

Allowed Function Calls::
For an <<outputClock>> only the first call of `fmi3GetClock` for a specific activation of this <<clock>> signals `fmi3ClockActive`.
The FMU sets the reported activation state immediately back to `fmi3ClockInactive` for the following `fmi3GetClock` calls for that <<clock>> (in the same or other model partitions of the FMU) until this <<outputClock>> is internally activated again.
The master can call `fmi3Set{VariableType}` and `fmi3Get{VariableType}` during the callback for variables associated to a <<outputClock>> that is active during this callback.
Also intermediate variable access is allowed as defined in <<state-intermediate-update-mode-co-simulation>>

Functions called in this state must not return <<fmi3Discard>>.

_[Based on the FMI standard it cannot be determined which part of the code of an FMU has called the callback function <<fmi3CallbackIntermediateUpdate>>._
_This is especially the case for Scheduled Execution where multiple model partitions can be active at the same time._
_This causes no issues since all function call prerequisites are connected to the activation state of <<clock,`clocks`>>, <<modelDescription.xml>> information and additionally available information from <<fmi3CallbackIntermediateUpdate>>]_

===== State: Reconfiguration Mode

In this state <<structuralParameter,`structural parameters`>> with <<variability>> = <<tunable>> can be changed.
This state is entered from state *Clock Activation Mode* by calling <<fmi3EnterConfigurationMode>> and left back to *Clock Activation Mode* by calling <<fmi3ExitConfigurationMode>>.

Allowed Function Calls::
- <<fmi3ExitConfigurationMode>>
- `fmi3Set{VariableType}`: Only for variables with <<causality>> = <<structuralParameter>> and <<variability>> = <<tunable>>.

Forbidden Function Calls::
Additionally to the generally forbidden functions in Scheduled Execution listed above the following functions must not be called in this state: <<fmi3EnterConfigurationMode>>, <<fmi3Instantiate>>, <<fmi3EnterInitializationMode>>, <<fmi3ExitInitializationMode>>, <<fmi3ActivateModelPartition>>, <<fmi3GetDirectionalDerivative>>, `fmi3GetOutputDerivatives`, `fmi3Get{VariableType}`.

==== Preemption Support [[preemption-support]]

For real-time applications the simulation time equals the real wall <<clock>> time, thus each <<fmi3ActivateModelPartition>> computation step has to be finished in real-time within its current period time length (computation time is not only defined by the runtime of <<fmi3ActivateModelPartition>> but also by the time for setting and getting variables and related operations).
Usually a preemptive scheduling of the <<fmi3ActivateModelPartition>>, `fmi3Get{VariableType}`, `fmi3Set{VariableType}` calls is required for respecting this constraint.

The FMU's code has to be prepared for being able to correctly handle preemptive calls of <<fmi3ActivateModelPartition>>, `fmi3Get{VariableType}`, `fmi3Set{VariableType}`.
That requires a secured internal and external access to global states and variable values.
Thus in Scheduled Execution a support for a correct handling of the preemption of model partition computations is required.
That also requires that the FMU reports the active state of a <<outputClock>> only with the first call of <<fmi3GetClock>> for a specific activation of this <<clock>> and sets the reported activation state immediately back to `false` for the following <<fmi3GetClock>> calls for that <<clock>> until this <<outputClock>> is internally activated again.

If a preemptive multitasking regime is intended an individual task (or thread -- task and thread are used synonymously here) for each model partition (associated to an <<inputClock>>) has to be created.
The task for computing each <<fmi3ActivateModelPartition>> is created and controlled by the simulation master, not by the FMU.
So the FMU exporting tool does not need to take care for that (except for preparing its code to support preemption).

_[If only one single model partition (<<inputClock>>) is available via the interface of an FMU, preemptive calls of the related <<fmi3ActivateModelPartition>> function are possible by default since there are no external cross dependencies within one model partition between communication points.]_

Based on the <<inputClock>> settings defined in the XML the master calls `fmi3Set{VariableType}`, <<fmi3ActivateModelPartition>>, `fmi3Get{VariableType}` calls.
Set/get calls for each task are only allowed for variables that are associated to the <<inputClock>> associated to that task or - here preemption issues become important - to variables that are associated to no <<clock,`clocks`>> (global variables), based on the XML information (see <<clock-type-definition>>).

_[The recommendation is to avoid global variable associations as much as possible in the XML._
_It is also recommended to reduce dependencies (defined in XML model structure) between variables located in different model partitions of one FMU, since this also requires in most cases that the related variables have to be global variables.]_

The Co-Simulation master has no knowledge about the FMU internal communication between the model partitions of a single FMU and does not handle it.

The simulation master schedules the <<fmi3ActivateModelPartition>> (as well as related `fmi3Get{VariableType}` and `fmi3Set{VariableType}`) calls based on given priorities for <<inputClock,`input clocks`>> defined in the <<modelDescription.xml>>.

Priority (see <<clock-type-definition>>):

- Same priority: Model partitions (e.g. tasks) cannot preempt each other. Arbitrary evaluation order is possible for model partitions of the same priority.
- Different priorities: Model partitions of a higher priority preempt partitions of a lower priority as soon as the higher priority partition needs to be computed.

_[If multiple tasks are needed to be scheduled for computation at a certain time instant a master must schedule a task of a higher priority always before a task of a lower priority]_

<<input,`Input`>> <<clock>> ticks (see <<variants-of-clocks>>):

- (<<strict>>) <<periodic>> (period can be predefined by FMU or be defined by master, depending on XML information)
- <<periodic,aperiodic>> (based on external possibly unpredictable events or on an <<outputClock>> of the same FMU)

Based on the period and priority definitions the exporting tool can restrict the code evaluation order.
It nevertheless has to secure its code against concurrent evaluation _[not against parallel evaluation, as this is not supported for model partitions of an FMU in the interface description of this mode]_ along the defined priority restrictions.
Mostly this is required for internal inter-model-partition communication and in general for the joint use of global variables within the FMU.
The exporting tool has to consider external events i.e. interrupts (if <<input>> <<periodic,aperiodic>> <<clock,`clocks`>> are defined) and the influences of computing speed, so the exact preemption occurrence points cannot be foreseen (within the given priority and period restrictions).

To provide more options to secure the code against unwanted preemption new callback functions are defined that can be used to prevent preemption for certain code parts.
The preemption lock has to be actively locked and unlocked in the FMU's code.
Such locks should be used with care and only for securing very short code parts that cannot be secured otherwise.

A lock can be created and released to prevent preemption of that task (i.e. model partition):

[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=CallbackPreemptionLock]
----

Even if the Co-Simulation master does not support preemption and Scheduled Execution, at least an empty implementation of these callback functions is required.

Example for the use of `fmi3CallbackLockPreemption` and `fmi3CallbackUnlockPreemption` callback functions in the FMU code:

[source, C]
----
Int16 DataBuffer[3];   // global buffer


void Task1(void) //low priority
{
   ...
   // write data to DataBuffer
   fmi3CallbackLockPreemption();
   DataBuffer[0] = internal_out_RootSys1_1;
   DataBuffer[1] = internal_out_RootSys1_2;
   DataBuffer[2] = internal_out_RootSys1_3;
   fmi3CallbackUnlockPreemption();
   ...
 }

...
void Task2(void) //high priority
{
   ...
   // read data from DataBuffer
   fmi3CallbackLockPreemption();
   internal_in_RootSys2_1 = DataBuffer[0];
   internal_in_RootSys2_2 = DataBuffer[1];
   internal_in_RootSys2_3 = DataBuffer[2];
   fmi3CallbackUnlockPreemption();
   ...
}
----

==== Pseudo-Code Example for Scheduled Execution

In the following example, the usage of the FMI functions is sketched in order to clarify the typical calling sequence of the functions in a simulation environment.
The example is given in a mix of pseudo-code and C, in order to keep it small and understandable.
We consider one slave with three model partitions. Two model partitions associated to two <<periodic>> <<inputClock,`input clocks`>> (<<clock>> periods 1 ms and 2 ms) and one <<periodic,aperiodic>> <<inputClock>>.

[source, c]
----
include::examples/pseudo_code_co_simulation_scheduled_execution_simulation.txt[]
----
