=== Hybrid Co-simulation Application Programming Interface [[hybrid-co-simulation-api]]

If the boolean capability flag `providesHybridCoSimulation` and `canReturnEarlyAfterIntermediateUpdate = true` the Co-Simulation master can use the interface `fmi3HybridCoSimulation`.

==== Communication of event time and input/output values

The <<fmi3CallbackIntermediateUpdate>> callback described in section <<earlyreturn-co-simulation>> is also used in order to communicate the <<input>> and <<output>> and, in particular, the event and <<clock>> time from the FMU to the Co-Simulation master.
The <<fmi3CallbackIntermediateUpdate>> callback allows internal events (e.g. associated to <<outputClock>> ticks) to be signaled from an FMU to the Co-Simulation master.
If `fmu3Type` is set to `fmi3HybridCoSimulation`, the <<fmi3CallbackIntermediateUpdate>> callback must be defined in <<fmi3CallbackFunctions>> in <<fmi3Instantiate>>.
In other cases a NULL pointer can be assigned to the <<fmi3CallbackIntermediateUpdate>> callback, such as if the `fmu3Type` is set to  `fmi3ModelExchange`.

The <<fmi3IntermediateUpdateInfo>>  argument in the <<fmi3CallbackIntermediateUpdate>> function is a structure which is used to signal <<outputClock>> ticks and internal events to the master.
Whenever the FMU invokes the <<fmi3CallbackIntermediateUpdate>> callback function, it fills the <<fmi3IntermediateUpdateInfo>> structure to pass information concerning the call to the Co-Simulation master.
The structure is defined as follows:

[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=IntermediateUpdateInfo]
----

* `intermediateUpdateTime` is the internal simulation time of the FMU at which the callback has been called.
If an event happens or a <<outputClock>> ticks, `intermediateUpdateTime` is the time of event or <<outputClock>> tick.
If the FMU signals an `earlyReturn = fmi3True` and `fmi3OK` after returning from <<fmi3DoStep>> then `intermediateUpdateTime` is the internal simulation time of the FMU of the last <<fmi3CallbackIntermediateUpdate>> call that signaled `canReturnEarly = fmi3true`.
`intermediateUpdateTime` is also the time of intermediate steps of the internal FMU solver.

The following `fmi3Boolean` variables define the reasons for the <<fmi3CallbackIntermediateUpdate>> call.
Several variables can be set by the FMU.
Default value of variables is `fmi3False`.

* when `eventOccurred` is `fmi3True`, the master must call <<fmi3DoEarlyReturn>> to do an early return and handle the event via entering *Event Mode*.
In this case, `earlyReturnTime` argument of <<fmi3DoEarlyReturn>> is ignored.
In *Event Mode* the master shall call the <<fmi3NewDiscreteStates>> function for gathering <<fmi3EventInfo>> related information about the event occurred at `intermediateUpdateTime`.

* when `clocksTicked`  is `fmi3True`, it means that <<fmi3GetClock>> function should be called for gathering all <<clock>> related information about ticking <<outputClock,`output clocks`>> at `intermediateUpdateTime`.
If this flag is `fmi3True` the master must call <<fmi3DoEarlyReturn>> to do an early return and handle the <<clock>> event in *Event Mode*.
In this case, `earlyReturnTime` argument of <<fmi3DoEarlyReturn>> is ignored.

* when `intermediateVariableSetAllowed` is `fmi3True`, the FMU signals that intermediate output values can be collected by the Co-Simulation master.

* when `intermediateVariableGetAllowed` is `fmi3True`, the FMU signals that intermediate input values can be set by the Co-Simulation master.

* when `intermediateStepFinished` is `fmi3True`, the FMU signals that the internal solver step for this time instant is complete.

* when `canReturnEarly` is `fmi3True` the master can request the FMU to return early at the current `intermediateUpdateTime` time instant via calling <<fmi3DoEarlyReturn>> within the callback function <<fmi3CallbackIntermediateUpdate>>.
If `canReturnEarly` is `fmi3False` the FMU will not do the early return, regardless of the master request.

Note that only the first discontinuity event at a Newtonian time instant shall be signaled that way.
But in *Event Mode*, there may be an event iteration at a Newtonian time instant and have super dense time instants.

Based on the information delivered in <<fmi3IntermediateUpdateInfo>>, additional information about the discontinuity at that time instant can be obtained from the <<fmi3EventInfo>> structure after calling  <<fmi3NewDiscreteStates>>  and/or <<fmi3GetClock>>.

The FMU must not call the <<fmi3CallbackIntermediateUpdate>> callback function with a `intermediateUpdateInfo.intermediateUpdateTime` value that is smaller than the `intermediateUpdateInfo.intermediateUpdateTime` value given in a previous call of <<fmi3CallbackIntermediateUpdate>> with `intermediateUpdateInfo.intermediateStepFinished` is `fmi3True`.

==== Handling a Successful Early-Return by the Co-Simulation Master in fmi3HybridCoSimulation

If the FMU is successful in conducting an early return, the return value of the `earlyReturn` argument in <<fmi3DoStep>> is `fmi3True`, otherwise `fmi3False`.
If the FMU returns from <<fmi3DoStep>> with the `earlyReturn = fmi3True` the Co-Simulation master has to call <<fmi3EnterEventMode>> for that FMU.

[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=EnterEventMode]
----

The Co-Simulation master can also call <<fmi3EnterEventMode>> at communication instants to handle input events, as will be discussed in following sections.

If an FMU provides the early-return capability that includes the handling of events in *Event Mode*, the FMU signals this via `canReturnEarlyAfterIntermediateUpdate` and `providesHybridCoSimulation = true` in the modelDescription.
The master should indicate to the FMU that this early-return feature is also supported by the master.
The Co-Simulation master signals to the FMU that it supports and has recognized the early return Co-Simulation capabilities of the FMU by setting the CoSimulation interface to `fmi3HybridCoSimulation` in the <<fmi3Instantiate>> function.

The FMU stops computation at the first encountered internal event (if any) and the event time is provided through `intermediateUpdateInfo.intermediateUpdateTime`.
If <<fmi3DoStep>> returns with `earlyReturn = fmi3True` and an event has happened, i.e. `intermediateUpdateInfo.eventOccurred` is `fmi3True`, then an event handling has to be done by the Co-Simulation master.
In order to start event handling the Co-Simulation master has to call <<fmi3EnterEventMode>> for that FMU to push the FMU into *Event Mode*.
In this mode the Co-Simulation master is supposed to catch all events through the <<fmi3NewDiscreteStates>> function and the <<fmi3EventInfo>> structure.

If the early-return request of the Co-Simulation master is ignored by the FMU, then <<fmi3DoStep>> returns with `earlyReturn = fmi3False`.
The master can start a resynchronization of FMUs at an event time, if the `currentCommunicationPoint` has passed the event time, the master can roll-back the FMU and repeat the step with a suitable `communicationStepSize` (if the FMU supports the roll-back).

In *Event Mode* and only after <<fmi3DoStep>> returns with `earlyReturn = fmi3True` a <<fmi3NewDiscreteStates>> call returns <<fmi3EventInfo>> structure as a return argument.
Not all elements of <<fmi3EventInfo>> are relevant and only the following elements may be considered:

- when `newDiscreteStatesNeeded = true` it means that the master should stay in *Event Mode* and another call to <<fmi3NewDiscreteStates>> is required.

- when `nextEventTimeDefined = true` it means that an event time is available and the value is given by the `nextEventTime` value.
This is the case when the model can report in advance the accurate time of the next predictable time event.

- when `terminateSimulation = true` it means that the model wants to stop integration and the Co-Simulation master should call <<fmi3Terminate>>.

In *Event Mode* it is allowed to `fmi3Get{VariableType}` variable values of the FMU after the call of <<fmi3NewDiscreteStates>> and it is allowed to `fmi3Set{VariableType}` variable values before calling <<fmi3NewDiscreteStates>>.
The FMU leaves *Event Mode* when the master calls <<fmi3EnterStepMode>> for that FMU.

It is not allowed to call <<fmi3EnterEventMode>> or <<fmi3EnterStepMode>> for an FMU with interface `fmi3CoSimulation` or `fmi3ScheduledCoSimulation`.

==== Co-Simulation with Clock Support in fmi3HybridCoSimulation [[api-clocked-co-simulation]]

In this section, signaling and retrieving <<clock>> ticks as well as the interface for supporting <<clock,`clocks`>> in FMI for Co-Simulation will be discussed.
If an FMU for Co-Simulation declares <<clock,`clocks`>> and clocked variables in the `modelDescription.xml` file, it supports <<clock,`clocks`>>.
The Co-Simulation master should indicate the FMU that the master has recognized the <<clock>> capabilities of the FMU and supports the <<clock>> handling by setting the Co-Simulation interface to `fmi3HybridCoSimulation` in <<fmi3Instantiate>>.
Note, even if no <<clock>> is defined by an FMU in `modelDescription.xml`, the master is allowed to set the interface to `fmi3HybridCoSimulation` to be able to do early return with event handling in *Event Mode*.

If an FMU provides <<clock,`clocks`>>, but the Co-Simulation master does not support or does not want to support early-return or <<clock,`clocks`>>, by setting the interface to `fmi3CoSimulation`, the activation of model partitions inside of the FMU has to be handled internally within <<fmi3DoStep>>.

_[Remark: Wrapping towards other Co-Simulation interfaces can influence the simulation results._
_Depending on the model especially wrapping towards `fmi3CoSimulation` may result in divergent simulation results._
_Especially aperiodic <<inputClock,`input clocks`>> can not always be sufficiently emulated in modes that do not directly support <<clock,`clocks`>>._
_Therefore it is recommended that the FMU provides logging information to the user about the influence of the current mode on simulation results, if non-optimal modes are used by the simulation environment.]_

[[fmi3EnterStepMode,`fmi3EnterStepMode`]]
[source, C]
----
include::../headers/fmi3FunctionTypes.h[tag=EnterStepMode]
----

===== Transfer of Input / Output Values and Parameters in fmi3HybridCoSimulation [[transfer-of-input-output-and-parameters-clocked-co-simulation]]

If the Co-Simulation master supports <<clock,`clocks`>>, all <<inputClock,`input clocks`>> of the model should be handled and <<inputClock>> events should be scheduled by the master.
If an <<outputClock>> ticks, the FMU invokes the <<fmi3CallbackIntermediateUpdate>> callback and sets `intermediateUpdateInfo.clocksTicked` to `fmi3True`.
Then the master must call <<fmi3DoEarlyReturn>> to do an early return from <<fmi3DoStep>>.
Then the master should push the FMU into *Event Mode* by calling <<fmi3EnterEventMode>>.
Once the FMU is in *Event Mode*, the activation status of <<outputClock,`output clocks`>> are retrieved by <<fmi3GetClock>> function.
Then <<fmi3SetClock>> (and <<fmi3SetIntervalDecimal>> or <<fmi3SetIntervalFraction>> if necessary) should be invoked to enable the ticked <<inputClock,`input clocks`>>.
Each <<clock>>, that ticks outside of the FMU (i.e. <<inputClock>>), is activated for an FMU based on its <<clockReference>> and an associated <<fmi3SetClock>> in *Event Mode*.
<<fmi3SetClock>> can activate multiple <<clock,`clocks`>> with each call.
An event iteration is possible.
Once all <<clock>> events are handled for this time instant, the FMU should be pushed into *Step Mode* by calling <<fmi3EnterStepMode>>.
In *Step Mode*, the Co-Simulation master can call <<fmi3DoStep>> for the time interval from the current event time instant until the next input event instant.
Note that <<fmi3DoStep>> may not reach the next input event instant because an early return may occur.

The simulation master sets and gets <<clock>> variable values similar to the FMI for Model Exchange, as defined in <<fmi-api-setting-getting-clock-activation-state>>.

===== Computation in fmi3HybridCoSimulation [[computation-clocked-co-simulation]]

Similar to FMI for Model Exchange, in order to activate <<inputClock,`input clocks`>> of an FMU, it is required to push the FMU into *Event Mode* by calling <<fmi3EnterEventMode>>.
If <<fmi3DoStep>> returns with `earlyReturn = fmi3True` and `intermediateUpdateInfo.eventOccurred` or `intermediateUpdateInfo.clocksTicked` is `fmi3True`, the FMU must be pushed into the *Event Mode* by calling <<fmi3EnterEventMode>>.

In order to retrieve the status of <<outputClock,`output clocks`>>, <<fmi3GetClock>> and <<fmi3GetIntervalDecimal>> or <<fmi3GetIntervalFraction>> need to be called in the *Event Mode*.
If the <<fmi3DoStep>> return value is `fmi3OK` and `earlyReturn = fmi3False`, the calling of <<fmi3GetClock>>, <<fmi3GetIntervalDecimal>>, <<fmi3GetIntervalFraction>>, <<fmi3NewDiscreteStates>> is only meaningful after <<fmi3SetClock>> in the case of super-dense time iterations are desired.

Similar to the Model Exchange case, the allowed call order is <<fmi3GetClock>>, <<fmi3GetIntervalDecimal>>, <<fmi3GetIntervalFraction>>, `fmi3Get{VariableType}`, `fmi3Set{VariableType}`.
Function calls of this call order can be omitted.

The handling of return values of function calls is identical to `fmi3CoSimulation`.

If `eventInfo.terminateSimulation` becomes `fmi3True` after calling <<fmi3NewDiscreteStates>> then the co-simulation should be terminated by calling <<fmi3Terminate>>.
Once handling of the <<clock>> events finished, the master calls <<fmi3EnterStepMode>> for that FMU to push it into *Step Mode*.
Note that it is not allowed to call <<fmi3EnterEventMode>> or <<fmi3EnterStepMode>> in `fmi3CoSimulation` or `fmi3ScheduledCoSimulation`.

_[Usually the Co-Simulation master should be able to derive (but is not forced to do so) the correct communication point times for <<inputClock,`input clocks`>> in advance and thus it should be able to set the proper `communicationStepSize` for <<fmi3DoStep>>._
_This might not be possible if an aperiodic <<inputClock>> of an FMU depends on the ticking of an aperiodic <<outputClock>> of another FMU or other aperiodic tick sources.]_

==== State Machine of Calling Sequence from Master to Slave in fmi3HybridCoSimulation [[state-machine-calling-sequence-clocked-co-simulation]]

The following state machine defines the supported calling sequences.

.Calling sequence of Hybrid Co-Simulation interface.
image::images/state-machine-hybrid-co-simulation.svg[width=80%, align="center"]
[#figure-hybrid-co-simulation-state-machine]

In this Co-Simulation interface the following functions must not be called: <<fmi3ActivateModelPartition>> including all functions that are specific to fmuType `fmi3ModelExchange`.

Unlike the state machine in section <<state-machine-co-simulation>> the entry state after *Initialization Mode* is the *Event Mode* in order to allow the FMU to handle the very first discrete event.
Each state of the state machine corresponds to a certain phase of a simulation as follows:

===== State: Slave Setable FMU State

This super state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-slave-setable-fmu-state-co-simulation>>.

===== State: Slave Under Evaluation

This super state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-slave-under-evaluation-co-simulation>>.

===== State: Slave Initialized

This super state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-slave-initialized-co-simulation>>.

===== State: Instantiated

This super state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-instantiated-co-simulation>>.

===== State: Configuration Mode

This state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-configuration-mode-co-simulation>>.

===== State: Initialization Mode

This state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-initialization-mode-co-simulation>>.

===== State: Event Mode

The master and the FMU enter this state when the master calls <<fmi3ExitInitializationMode>> in state *Initialization Mode* or <<fmi3ExitConfigurationMode>> in state *Reconfiguration Mode* or <<fmi3EnterEventMode>> in state *Step Mode*.
In order to handle discrete events and <<clock>> ticks, the FMU is pushed into the *Event Mode* by calling <<fmi3EnterEventMode>>

Allowed Function Calls::
<<fmi3Terminate>>::
Upon return of <<fmi3NewDiscreteStates>>, if `fmi3EventInfo->terminateSimulation = fmi3True`, the master should finish the Co-Simulation by calling `fmi3Terminate` on all FMUs.

<<fmi3EnterConfigurationMode>>::
With this function call the *Reconfiguration Mode* is entered.
This function must not be called if the FMU contains no <<tunable>> <<structuralParameter,`structural parameters`>> (i.e. with <<causality>> = <<structuralParameter>> and <<variability>> = <<tunable>>).

<<fmi3NewDiscreteStates>>::
In order to handle discrete events <<fmi3NewDiscreteStates>> is called.
This function returns the `fmi3EventInfo* eventInfo` structure.
When `eventInfo.newDiscreteStatesNeeded = true`, the FMU should stay in *Event Mode* and another call to <<fmi3NewDiscreteStates>> is required.

<<fmi3EnterStepMode>>::
Once all events are handled and <<fmi3NewDiscreteStates>> returns with `eventInfo.newDiscreteStatesNeeded = false`, the FMU should return back to the *Step Mode*, unless the FMU requests to terminate the Co-Simulation by setting  `fmi3EventInfo->terminateSimulation` to `true`.
In order to push the FMU into the *Step Mode*, the <<fmi3EnterStepMode>> function is used.
In this case, a new step can be started from the current communication point time.

<<fmi3GetClock>>::
The status of <<clock,`clocks`>> can be inquired by this function.

<<fmi3SetClock>>::
For <<inputClock,`input clocks`>>, <<fmi3SetClock>> is called after entering *Event Mode* to set the activation status of <<clock,`clocks`>>.
For both <<input>> and trigerred <<clock,`clocks`>>, this function can be called several times, only if recomputations of clock state are needed during *Event Mode*.

<<fmi3GetIntervalDecimal>> & <<fmi3GetIntervalFraction>>::
For both <<outputClock,`output clocks`>> and <<inputClock,`input clocks`>> it is allowed to call these functions during *Event Mode*.

<<fmi3SetIntervalDecimal>> & <<fmi3SetIntervalFraction>>::
It is not allowed to call these functions for <<output>>, aperiodic and strictly periodic <<clock,`clocks`>>.
For <<input>> periodic <<clock,`clocks`>>, these functions are called after the first <<clock>> activaion.

===== State: Step Mode

This state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-step-mode-co-simulation>>.

===== State: Intermediate Update Mode

This state in Hybrid Co-Simulation differ from Co-Simulation described in section <<state-step-mode-co-simulation>> as following:

Allowed Function Calls::

<<fmi3DoEarlyReturn>>::
`intermediateUpdateInfo->canReturnEarly` is `fmi3True`, the Co-Simulation master can request the FMU to end the <<fmi3DoStep>> and to do an early return by calling this function.

Forbidden Function Calls::
All API functions not listed in the allowed function list, including <<fmi3GetClock>> and  <<fmi3SetClock>> are forbidden in this mode.

===== State: Reconfiguration Mode

This state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-reconfiguration-mode-co-simulation>>.

===== State: Step Discarded

This state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-step-discarded-co-simulation>>.

===== State: Terminated

This state in Hybrid Co-Simulation does not differ from Co-Simulation described in section <<state-terminated-co-simulation>>.

// TODO: Update table. Remove stepComplete, stepInProgress, stepCanceled? Where is the state Error described in the state machine?

_[The allowed function calls in the respective states are summarized in the following table (functions marked in [yellow-background]#"yellow"# are only available for Co-Simulation, the other functions are available both for Model Exchange and Co-Simulation):_

[cols="10,1,1,1,1,1,1,1,1,1,1,1,1,1,1",width="40%"]
|====
.2+.>|*Function*
14+|*FMI 3.0 for Co-Simulation*
|[vertical-text]#start, end#
|[vertical-text]#Instantiated#
|[vertical-text]#Configuration Mode#
|[vertical-text]#Initialization Mode#
|[vertical-text]#Event Mode#
|[vertical-text]#Reconfiguration Mode#
|[vertical-text]#Step Mode#
|[vertical-text]#stepComplete#
|[vertical-text]#stepInProgress#
|[vertical-text]#Step Discarded#
|[vertical-text]#Intermediate Update Mode#
|[vertical-text]#stepCanceled#
|[vertical-text]#Terminated#
|[vertical-text]#error#

|<<fmi3GetVersion>>           |x |x |  |x |  |  |  |x |x |  |x |x |x |x
|<<fmi3SetDebugLogging>>          |  |x |  |x |  |  |  |x |x |  |x |x |x |x
|<<fmi3Instantiate>>              |x |  |  |  |  |  |  |  |  |  |  |  |  |
|<<fmi3FreeInstance>>             |  |x |  |x |  |  |  |x |  |  |x |x |x |x
|<<fmi3SetupExperiment>>          |  |x |  |  |  |  |  |  |  |  |  |  |  |
|<<fmi3EnterInitializationMode>>  |  |x |  |  |  |  |  |  |  |  |  |  |  |
|<<fmi3ExitInitializationMode>>   |  |  |  |x |  |  |  |  |  |  |  |  |  |
|<<fmi3Terminate>>                |  |  |  |  |  |  |  |x |  |  |x |  |  |
|<<fmi3Reset>>                    |  |x |  |x |  |  |  |x |  |  |x |x |x |x
|fmi3GetReal                  |  |  |  |2 |  |  |  |x |  |  |8 |7 |x |7
|fmi3GetInteger               |  |  |  |2 |  |  |  |x |  |  |8 |7 |x |7
|fmi3GetBoolean               |  |  |  |2 |  |  |  |x |  |  |8 |7 |x |7
|fmi3GetString                |  |  |  |2 |  |  |  |x |  |  |8 |7 |x |7
|fmi3SetReal                  |  |1 |  |3 |  |  |  |6 |  |  |  |  |  |
|fmi3SetInteger               |  |1 |  |3 |  |  |  |6 |  |  |  |  |  |
|fmi3SetBoolean               |  |1 |  |3 |  |  |  |6 |  |  |  |  |  |
|fmi3SetString                |  |1 |  |3 |  |  |  |6 |  |  |  |  |  |
|<<fmi3GetFMUState>>              |  |x |  |x |  |  |  |x |  |  |8 |7 |x |7
|<<fmi3SetFMUState>>              |  |x |  |x |  |  |  |x |  |  |x |x |x |x
|<<fmi3FreeFMUState>>             |  |x |  |x |  |  |  |x |  |  |x |x |x |x
|<<fmi3SerializedFMUStateSize>>   |  |x |  |x |  |  |  |x |  |  |x |x |x |x
|<<fmi3SerializeFMUState>>        |  |x |  |x |  |  |  |x |  |  |x |x |x |x
|<<fmi3DeSerializeFMUState>>      |  |x |  |x |  |  |  |x |  |  |x |x |x |x
|<<fmi3GetDirectionalDerivative>>|  |  |  |x |  |  |  |x |  |  |8 |7 |x |7
|<<fmi3EnterStepMode>>            {set:cellbgcolor:yellow} |  {set:cellbgcolor!} |  |  |  |  |  |  |  |  |  |  |  |  |
|<<fmi3SetInputDerivatives>>      {set:cellbgcolor:yellow} |  {set:cellbgcolor!} |x |  |x |  |  |  |  |x |  |  |  |  |
|<<fmi3GetOutputDerivatives>>     {set:cellbgcolor:yellow} |  {set:cellbgcolor!} |  |  |  |  |  |  |  |x |  |8 |x |x |7
|<<fmi3DoStep>>                   {set:cellbgcolor:yellow} |  {set:cellbgcolor!} |  |  |  |  |  |  |  |x |  |  |  |  |
|<<fmi3ActivateModelPartition>>   {set:cellbgcolor:yellow} |  {set:cellbgcolor!} |  |  |  |  |  |  |  |  |  |  |  |  |
|<<fmi3DoEarlyReturn>>            {set:cellbgcolor:yellow} |  {set:cellbgcolor!} |  |  |  |  |  |  |  |  |x |  |  |  |
|<<fmi3GetDoStepDiscardedStatus>> {set:cellbgcolor:yellow} |  {set:cellbgcolor!} |  |  |  |  |  |  |  |  |  |x |  |  |
|====

_]_

==== Code Example for fmi3HybridCoSimulation [[code-example-clocked-co-simulation]]

In the following example, the usage of the FMI functions is sketched in order to clarify the typical calling sequence of the functions in a simulation environment.
We consider ...

// TODO: Description of code example. Explained once validated, after examples are ready?

The error handling is implemented in a very rudimentary way.

[source, C]
----
include::examples/c-code/co_simulation_clocked.c[tags=CoSimulation]
----
