=== Hybrid Co-Simulation Description Schema [[hybrid-co-simulation-schema]]

The Co-Simulation master collects the information about the number and properties of <<clock,`clocks`>> supported by the FMU by analyzing the `modelDescription.xml`, see <<clock-type-definition>>.

The definition of <<clock,`clocks`>> is optional.

Each <<inputClock>> that ticks outside of the FMU, is activated for an FMU based on their <<valueReference>>.
<<outputClock,`Output clocks`>> inside of an FMU signal their activation based on their <<valueReference>>`.

_[If <<dependencies>> (`fmi3VariableDependency`) are defined in the `ModelStructure` section of the `modelDescription.xml`, it is recommended to define such <<dependencies>> only within a model partition of a model (i.e. between variables that are assigned to the same <<clock>>).]_

If <<dependencies>> are defined for variables across model partitions, such variables can not be assigned to a <<clock>> via <<clockReference>>.

For FMI for Co-Simulation, variables that are assigned to a model partition of the model based on <<clockReference>> are not necessarily `clocked`.
Such variables can be Continuous-time or Discrete-time variables if the <<clock>> is of `clockType = communicationPoint`.

==== Capability Flags [[xml-flags-clocked-co-simulation]]

If the XML file defines an FMU for Hybrid Co-Simulation, element `CoSimulation` must be present as described in section <<basic-co-simulation>>.

In order to provide a Hybrid Co-Simulation, the attribute `providesHybridCoSimulation` has set to be set to `true`.

==== Example XML Description File [[xml-example-clocked-co-simulation]]

The example below is the same one as shown in <<xml-example-co-simulation>> for a Co-Simulation FMU.
The only differences are, that `providesHybridCoSimulation` is set to `true` and <<clock,`clocks`>> are defined in the `modelDescription.xml`. #[TODO]: Recheck later#
The XML file may have the following content:

[source, xml]
----
//include::examples/co_simulation_clocked_cosimulation.xml[]
----
