=== Code Example [[example-scheduled-execution]]

The FMU `ThreeInputClocks` sketches the usage of the Scheduled Execution.
The example consists of one FMU with three model partitions.
Two model partitions are associated with two <<periodic-clock,periodic Clocks>> `10msClock` and `50msClock` (periods 10 ms and 50 ms) and one is associated with an aperiodic <<countdown-aperiodic-clock,countdown clock>> `AperiodicClock`.

During the execution of the model partition of <<Clock>> `10msClock`, the FMU changes the `interval` for <<countdown-aperiodic-clock,countdown clock>> `AperiodicClock` and calls <<fmi3ClockUpdateCallback>> to inform the importer that the interval has changed.
The importer retrieves this interval and activates the corresponding model partition.

In this example, the calls to <<fmi3ActivateModelPartition>> (as well as related <<get-and-set-variable-values,`fmi3Get{VariableType}`>> and `fmi3Set{VariableType}`) for each associated Clock are placed into a task.
A task can be thought of as a simple interface of the scheduler that allows to connect the FMU interface by implementing a void/void function and set up the priorities of the tasks as derived from the respective <<Clock>> configurations of the FMU.

As a result of the FMU's configuration and implementation the following can be observed:
The task of <<countdown-aperiodic-clock,countdown clock>> `AperiodicClock` is waiting for the task of <<Clock>> `10msClock` to finish.
Likewise the task of `AperiodicClock` is suspended when the task of higher priority is scheduled again.
The example also depicts how a task associated with an even lower priority <<Clock>> (`50msClock`) is delayed several times by tasks of higher priority.
Note that the point in time when the task was scheduled is the <<activationTime>> of <<fmi3ActivateModelPartition>> (...Activate...(<<inputClock>>, <<activationTime>>)).

.Scheduled Execution Example `ThreeInputClocks`
[[figure-scs_example]]
image::images/se_example.svg[width=90%, align="center"]

==== Simulation Algorithm Implementation

Depending on the particular configuration the simulation algorithm uses the interface of a scheduler to set up tasks for every <<inputClock>>.
Periodic tasks can be scheduled on initialization of the simulation application.
Aperiodic tasks are scheduled explicitly during the execution.
When executed, each task calls <<fmi3ActivateModelPartition>> (as well as related <<get-and-set-variable-values,`fmi3Get{VariableType}`>> and `fmi3Set{VariableType}`) for each associated Clock.
The <<activationTime>> is provided by the simulation algorithm.

[source, C]
----
include::examples/snippets.c[tags=SE_sa_task10ms]
----

The FMU requests to schedule the model partition of `AperiodicClock`.
It calls <<fmi3ClockUpdateCallback>> to enable the importer to check whether the FMU has defined a new interval for `AperiodicClock`.
By evaluating the returned values <<qualifiers>> and <<intervals>> of <<fmi3GetInterval>> the simulation algorithms determines if the respective task has to be scheduled and which delay has to be applied.

[source, C]
----
include::examples/snippets.c[tags=SE_sa_clockUpdate]
----

==== FMU Implementation

The FMU implements <<fmi3ActivateModelPartition>> regarding every <<inputClock>> so the code might look like this:

[source, C]
----
include::examples/snippets.c[tags=SE_fmu_activateMP]
----

In the task being executed every 10 ms, the FMU initiates the scheduling of a task by setting a new interval to <<countdown-aperiodic-clock,countdown Clock>> `AperiodicClock` and evoking <<fmi3ClockUpdateCallback>>.

[source, C]
----
include::examples/snippets.c[tags=SE_fmu_activateMP10ms]
----

In <<fmi3GetIntervalDecimal>> the Clock's interval qualifier is reset to <<fmi3IntervalUnchanged>>.
To ensure consistency the FMU may need to prevent preemption.
In this example it is actually not needed since CallbackClockUpdate is only called from one model partition.

[source, C]
----
include::examples/snippets.c[tags=SE_fmu_getIntervalDecimal]
----

In the aperiodic model partition the interval qualifier is reset to <<fmi3IntervalNotYetKnown>>.

[source, C]
----
include::examples/snippets.c[tags=SE_fmu_activateMPAperiodic]
----

If <<fmi3GetClock>> is called for a certain <<outputClock>> the <<outputClock>> is reset.
As for <<fmi3GetIntervalDecimal>> it may be necessary for the FMU to ensure that the code is not preempted.
Here it is just as well not needed for the same reason.

[source, C]
----
include::examples/snippets.c[tags=SE_fmu_getClock]
----
