== FMI for Scheduled Execution [[fmi-for-scheduled-execution]]

The Scheduled Execution interface provides support for concurrent computation of <<model-partition, model partitions>> on a single computational resource (e.g. CPU-core).
The FMU exposes model partitions defined by its associated Clocks while the <<importer>> is enabled to explicitly schedule each model partition's execution.
As mentioned in <<advancing-time>>, it is the importer respectively its scheduler that controls how time is progressing.

The following use cases and requirements motivate the introduction of this interface type:

* The scheduler can execute a model partition at any time.
It can execute model partitions periodically (either according to virtual time or real time) or reacting to an <<event>>, e.g. an event of an external I/O or an event sent from an FMU (see below).

* The scheduler can run model partitions of one FMU together with model partitions of other FMUs or model partitions provided by other sources such as other models or functions in a single process.

* The scheduler respects <<priority, priorities>> of the model partitions defined by the FMU.

* The Scheduled Execution interface allows the scheduler to preempt the execution of an FMU's model partition.
The <<importer>> is providing lock/unlock functions to the FMU to secure sections that should not be interrupted (e.g. the exchange of data between two model partitions of the same FMU).

* The Scheduled Execution interface allows the FMU to send an event to the scheduler while a model partition is executed.

A parallel computation of model partitions is not part of the FMI 3.0 API.
An FMU may still internally use parallel computation on multiple cores, but handling this is (currently) not part of the FMI standard.
