== Hybrid Co-Simulation [[hybrid-co-simulation]]

==== Co-Simulation with Clock Support [[math-clocked-co-simulation]]

The notion of <<clock>> in FMI for Model Exchange has been extended to the FMI for Co-Simulation.

Both <<outputClock,`output clocks`>> and <<inputClock,`input clocks`>> are supported in Co-Simulation with <<clock,`clocks`>>.
In order to handle <<inputClock,`input`>> and <<outputClock,`output clocks`>> in Co-Simulation, a new *Event Mode* has been introduced.

The concept and the way <<inputClock,`input`>> and <<outputClock,`output clocks`>> are handled are very similar in Model Exchange and Co-simulation.
In order to handle <<inputClock,`input clocks`>>, the Co-Simulation master schedules <<inputClock,`input clocks`>> and adjusts the communication steps in such a way that <<inputClock>> ticks become communication points.
At these communication points, the FMU is pushed to the *Event Mode* and <<inputClock,`input clocks`>> are handled.

<<outputClock,`Output clocks`>>, on the other hand, are detected by the FMU.
The FMU detects an <<outputClock>> and informs the master by invoking a callback in which the event time and the event type is communicated to the master.
Then FMU stops the current Co-Simulation step and returns back from <<fmi3DoStep>>.
Then the FMU is pushed to the *Event Mode* and the event is handled.
Note that, since output events time instants are not known in advance, at output event time instants, new communication steps are created.