:numbered!:

[appendix]
## Glossary [[glossary]]

This glossary is a subset of (_MODELISAR Glossary, 2009_) with some extensions.

[cols="1,3"]
|====
|Term
|Description

|_argument_
|Refers to a function parameter.
Not to be confused with _parameter_.

|_capability flag_
|Capability flags are used to indicate to the importer what optional functionality the FMU supports.

|_clock_
|A variable to report events or trigger events or model partitions.

|_clock tick_
|When the <<Clock>> ticks an event is present, otherwise the event is absent.
This document calls a <<Clock>> tick a <<Clock>> activation.

|_communication points_
|Time grid for data exchange between importer and FMU(s) in a (co-)simulation environment.

|_communication step size_
|Distance between two subsequent _communication points_.

|_continuous-time instant_
|See <<time-instant>>.

|_co-simulation_
|Coupling of several _simulation programs_ in order to compute the global behavior of a system that consists of several subsystems.
The subsystems are coupled in the sense that the behavior of each subsystem depends on the behavior of the remaining subsystems, so that the co-simulation must be computed in a step-by-step fashion.
Each simulation program is responsible for computing the behavior of a subsystem, using the outputs produced by the other simulation programs.
Synonyms: dynamic mutual-exchange, simulator coupling, and coupled simulation.

|_direct feedthrough_
|Direct feedthrough describes that values of output variables depend directly on values of input variables.

|[[dynamic-state-selection,dynamic state selection]]_dynamic state selection_
|Dynamic State Selection is a method to solve differential algebraic equations (DAEs).
The FMU checks whether the dynamically selected states are still numerically appropriate.
If not, a new mapping between states and variables is computed.
For details see <<MS93>>.

|_ECU_
|Electronic Control Unit (Microprocessor that is used to control a technical system).

|_event_
|Something that occurs instantaneously at a specific time or when a specific condition occurs.
At an event, numerical integration is suspended and variables may change their values discontinuously.
Internal events occur inside the FMU and should be signaled to the environment without any delay and can cause event handling and/or the activation of an output clock.
Input clocks are activated by the environment to inform the FMU about the exact moment an event across FMUs has to be handled.
See <<state-event>>, <<step-event>> and <<time-event>>.

|[[eventIndicator,event indicator]]_event indicator_
|A variable that changes sign exactly at an event.
See <<state-event,event indicator>>.

|_event iteration_
|An importer can iteratively call <<get-and-set-variable-values,`fmi3Set{VariableType}`>> and <<get-and-set-variable-values,`fmi3Get{VariableType}`>> e.g. to solve _algebraic loops_ during an event and during a _super-dense time instant_.
When reaching a consistent state, changes to discrete variables may be triggered.
Such a discrete (state) change may require another solution of an algebraic loop in the next super-dense time instant.
These discontinuous changes can repeat until the participating FMUs or the master decide that no further iteration is needed.
An example for a system that can be simulated with event iteration is a powertrain with multiple clutches distributed in several FMUs.
The decision which clutch is open, which is closed and which is slipping can be determined with event iteration.

|_exporter_
|A program that creates an FMU.

|_external scheduler_
|See _scheduler_.

|_feedthrough_
|See _direct feedthrough_.

|_FMI_
|Functional Mock-Up Interface: +
Interface of a functional mock-up in form of a model.
In analogy to the term digital mock-up (see _mock-up_), functional mock-up describes a computer-based representation of the functional behaviour of a system for all kinds of analyses.

|_FMI functions_
|The function of the FMI C-API.

|_FMI for co-simulation_
|Functional Mock-Up Interface for Co-Simulation: +
One of the MODELISAR _Functional Mock-Up Interface types._ It connects the _importer_ with one or more _FMU_.

|_FMI for model exchange_
|Functional Mock-Up Interface for Model Exchange: +
One of the MODELISAR _Functional Mock-Up Interface types._ It consists of the _model description_ and the _C API_. +

|_FMU_
|Functional Mock-Up Unit: +
A "model class" following the interface type FMI for Model Exchange, or a model following the interface types FMI for Co-Simulation or FMI for Scheduled Execution).
An FMU is one ZIP file as defined in <<fmu-distribution>>.
The zip file comprises essentially an XML file that defines the model variables, and a set of C function implementations (see <<general-mechanisms>>).
The implementations can be in source or binary form.

|_FMU clock_
|See <<Clock>>.

|_importer_
|The tool that imports or loads one or more FMUs.
Also called simulation environment, environment, calling environment, (co-)simulation algorithm, target platform, target environment, integrator (in ME).

|_independent variable_
|All variables are a function of this <<independent>> variable, typically time.

|[[input-event,input event]]_input event_
|An input event occurs when a discrete input variable changes, a continuous input variable has a discontinuity or a <<tunable>> <<parameter>> changes its value.
_[Note that if an FMU A is connected to an FMU B, and an event is triggered for A, then potentially all <<output,`outputs`>> of A will be discontinuous at this time instant._
_It is therefore advisable to move B into <<EventMode>> at this time instant too if an <<output>> of A is connected to B._
_This means to call <<fmi3EnterEventMode>> on B.]_

|_integration algorithm_
|The numerical algorithm to solve differential equations.

|_integrator_
|A _software component_, which implements an _integration algorithm_.

|_interface_
|An abstraction of a _software component_ that describes its behavior without dealing with the internal implementation.
_Software components_ communicate with each other via interfaces.

|_machine epsilon_
|Smallest floating point value.

|_mock-up_
|A full-sized structural, but not necessarily functional model built accurately to scale, used chiefly for study, testing, or display.
In the context of computer aided design (CAD), a digital mock-up (DMU) means a computer-based representation of the product geometry with its parts, usually in 3-D, for all kinds of geometrical and mechanical analyses.

|_model_
|A model is a mathematical or logical representation of a system of entities, phenomena, or processes.
Basically a model is a simplified abstract view of the complex reality. +
It can be used to compute its expected behavior under specified conditions.

|_model description file_
|The model description file is an XML file, which supplies a description of all properties of a _model_ (for example, <<input>> / <<output>> variables).

|_model description interface_
|An interface description to write or retrieve information from the _model description file_.

|_Model Description Schema_
|An _XML_ schema that defines how all relevant, non-executable, information about a "model class" (_FMU)_ is stored in a text file in _XML_ format.
Most important, data for every variable is defined (variable name, handle, data type, variability, unit, etc.), see <<fmi-description-schema>>.

|_model rate_
|Inverse of time interval between two communication points associated to an exposed model partition within the FMU (i.e. <<Clock>> is defined in interface).
In general multiple rates i.e. multiple model partitions can be defined for an Co-Simulation FMU.

|[[model-partition,model partition]]_model partition_
|Model partitions can be associated to a discrete or (piecewise) continuous part of the FMU.
The computation of model partitions can be externally controlled based on <<Clock>> ticks of associated <<inputClock,`input clocks`>>.

Not all FMU internal model partitions have to be exposed in the Co-Simulation interface as <<Clock>> and can also be handled FMU internally (e.g. internal subsampling).
Nevertheless, it is assumed that the activation of all exposed <<inputClock,`input clocks`>> results in the computation of the complete FMU.

As stated above, continuous parts of the FMU are also associated to model partitions that define the communication points for the <<continuous>> values.

|_ODE_
|see _Ordinary Differential Equation_

|_Ordinary Differential Equation_
|Differential equation containing one or more functions of one independent variable (typically time) and the derivatives of those functions.

|_output points_
|Tool internal time grid for saving output data to file (in some tools also known as "_communication points_" - but this term is used in a different way in FMI for Co-Simulation, see above).

|_output step size_
|Distance between two subsequent _output points_.

|_parameter_
|A quantity within a _model_, which remains constant during _simulation (<<fixed>> <<parameter>>) or may change at event instances (<<tunable>> <<parameter>>)_.
Examples are a mass, stiffness, etc.
These parameters are different from <<calculatedParameter,calculated parameters>>, because they can be changed independently (according to their <<variability>>).

|_runtime environment_
|See co-simulation environment

|_scheduled execution_
|FMI type that externalizes the scheduler to run _model partitions_, potentially synchronized between more than one FMU and exchanging input and output variables accordingly.

|_simulation_
|Compute the behavior of one or several _models_ under specified conditions. +
(see also _co-simulation_)

|_simulation model_
|see _model_

|_simulation program_
|Software to develop and/or solve simulation _models_.
The software includes a _solver_, may include a user interface and methods for post processing (see also: _simulation tool_, _simulation environment_). +

|_simulation tool_
|see _simulation program_

|_simulator_
|A simulator can include one or more _simulation programs_, which solve a common simulation task.

|_simulator coupling_
|See _tool coupling_.

|_solver_
|_Software component,_ which includes algorithms to solve _models_, for example, _integration algorithms_ and _event handling_ methods.

|_state_
|The continuous <<state,`states`>> of a model are all variables that appear differentiated in the model and are independent from each other. +
The discrete-time states of a model are time-discrete variables that have two values in a model: The value of the variable from the previous _event_ instant, and the value of the variable at the actual event instant.

|_state event_
|The time of <<state-event,state _events_>> is not known apriori.
<<fmi3GetEventIndicators,Event indicators>> are used to allow the importer finding the time of these state events precisely.

|[[step-event,step event]]_step event_
|_Event_ that might occur at a completed integrator step signaled by calling <<fmi3CompletedIntegratorStep>>.
Step events are, for example, used to change the mapping of the continuous states to variables (<<dynamic-state-selection>>).

|_structural parameter_
|A parameter influencing the size and/or dimensionality of an array variable of an FMU.

|[[super-dense-time,super-dense time]]_super-dense time_
|A precise definition of time taking into account iterations at an event.
For an _FMU_, the <<independent>> variable time latexmath:[\mathbf{t} \in \mathbb{T}] is a tuple latexmath:[\mathbf{t} = (\mathbf{t}_R, \mathbf{t}_I)] where latexmath:[\mathbf{t}_R \in  \mathbb{R}, \mathbf{t}_I \in \mathbb{N} = \{0,1,2,\ldots\}].
The real part latexmath:[\mathbf{t}_R] of this tuple is the <<independent>> variable of the FMU for describing the continuous-time behavior of the model between events.
During continuous-time integration latexmath:[\mathbf{t}_I = 0].
The integer part latexmath:[\mathbf{t}_I] of this tuple is a counter to enumerate (and therefore distinguish) the events at the same continuous-time instant latexmath:[\mathbf{t}_R].

|_super-dense time instant_
|See <<time-instant>> and <<super-dense-time>>.

|_task_
|Special kind of _model partition_ that is used in control code.

|[[time-event,time event]]_time event_
|_Event_ that is defined by a predefined time instant.
Since the time instant is known in advance, the integrator can select its step size so that the event point is directly reached.
Therefore, this event can be handled efficiently.

|[[time-instant,time instant]]_time instant_
|A moment in time, either a continuous-time instant latexmath:[\mathbf{t} = \mathbf{t}_R], or a super-dense time instant latexmath:[\mathbf{t} = (\mathbf{t}_R, \mathbf{t}_I)], see also <<super-dense-time>>.

| TLM
| _see Transmission Line Method_

| Transmission Line Method
|A mathematical method which uses physically motivated time delays to decouple an equation system into independent parts during a specified time frame without compromising numerical stability.
Also known as the _bi-lateral delay line_ method.

|_user interface_
|The part of the simulation program that gives the user control over the simulation and allows watching results.

|_XML_
|eXtensible Markup Language (http://www.w3.org/XML/[www.w3.org/XML], http://en.wikipedia.org/wiki/Xml[en.wikipedia.org/wiki/XML]) - An open standard to store information in text files in a structured form.

|====

[appendix]
== Acknowledgements

Until Dec. 2011, this work was carried out within the ITEA2 MODELISAR project (project number: ITEA2-07006, https://itea3.org/project/modelisar.html).

Daimler AG, DLR, ITI GmbH, Martin Luther University Halle-Wittenberg, QTronic GmbH and SIMPACK AG thank BMBF for partial funding of this work within MODELISAR (BMBF F&#246;rderkennzeichen: 01lS0800x).

Dassault Syst&#232;mes (Sweden) thanks the Swedish funding agency VINNOVA (2008-02291) for partial funding of this work within MODELISAR.

LMS Imagine and IFPEN thank DGCIS for partial funding of this work within MODELISAR.

Since Sept. 2012 until Nov. 2015, this work is partially carried out within the ITEA2 MODRIO project (project number: ITEA 2-11004, https://itea3.org/project/modrio.html).

- DLR, ITI GmbH, QTronic GmbH and SIMPACK AG thank BMBF for partial funding of this work within MODRIO (BMBF F&#246;rderkennzeichen: 01IS12022E).

- Dassault Syst&#232;mes (Sweden), Link&#246;ping University and Modelon AB thank the Swedish funding agency VINNOVA (2012--01157) for partial funding of this work within MODRIO.

- Siemens PLM Software (France) and IFPEN thank DGCIS for partial funding of this work within MODRIO.
