= CAN Bus Communication with FMI
:sectnums:
:sectnumlevels: 5
:toc: left
:toc-title: Contents
:toclevels: 5
:xrefstyle: short
:docinfo: shared
:docinfodir: docs
:stylesheet: docs/fmi-spec.css
:stem: latexmath
:source-highlighter: highlightjs
:nofooter:
:favicon: images/favicon.ico
:revdate: unreleased
:revnumber: 3.0
:icons: font

This standard defines how to describe input and output variables of 3.0 FMUs that are signals of Automotive CAN Buses.

{empty} +
{empty}

Copyright (C) 2008-2011 MODELISAR Consortium and 2012-2020 The Modelica Association Project FMI.

This document is licensed under the Attribution-ShareAlike 4.0 International license.
The code is released under the 2-Clause BSD License.
The licenses text can be found in the https://raw.githubusercontent.com/modelica/fmi-standard/master/LICENSE.txt[LICENSE.txt] file that accompanies this distribution.

{empty}

== Introduction

=== Intend of this document

Automotive CAN is a bus technology that has been applied successfully over many years by all automotive OEMs world wide.
Virtualizing electronic control units (ECUs) and then simulating multiple such vECUs requires connecting them using a virtual version of the bus technology.
Reusing standard bus topology description formats, such as DBC and ARXML, is required for efficiency and testing reasons alike.

This document describes how to use standard description formats for CAN bus topologies on top of the FMI 3.0 Standard.
vECUs following this standard can then easily be connected in importing tools because the bus description files declare which signals have what properties and belong to what messages in which of the potentially multiple buses connected to each vECUs.

This document only deals with classic CAN, not CAN-FD.
Signal properties will be extracted from the bus description files and it is assumed that exporters and importers have the same understanding and interpretation of the description files.
This document does not address potential open points of these description formats, it is assumed that such ambiguities will be handled elsewhere.

=== Rough outline of the approach

The bus description files will be placed into the `/extra/org.modelica.fmi.layered_CAN` folder 

